---
title: "Artificial Intelligence"
---

The term artificial intelligence (AI) was first introduced in the 1950s as a branch of computer science concerned with the automation of intelligent behavior (McCarthy, 2007). Since then, AI and associated techniques have developed rapidly to the point that today there is still no fully accepted definition of what AI is. Most frequently, AI is associated with the ability of a machine to sense its environment, learn from experience, make decisions based on input and goals, and ultimately perform human-like tasks. With the swift progress made by Big Data technologies and the ever-increasing capacity of computer storage and lightning-fast speed of data processing machines, AI is being revitalized. Considering those advances AI could also be defined as "the ability (of a computer system) to correctly interpret external data, learn from such data, and use those learnings to achieve specific goals and tasks through flexible adaptation" (Kaplan & Haenlein, 2019). These "intelligent" systems use all kinds of algorithms and machine learning techniques to learn from data and make decisions aimed at achieving specific goals.

After many years of promising expectations, AI is gaining momentum in business organizations all around the world and applications extend to a wideranging variety of fields and contexts: from image recognition, video surveillance, telemedicine, robots, autonomous vehicles, and social media websites, to voice recognition, machine translations, online games, autonomous planning and programming, spam filters, weather forecasts, etc. (Ivanov & Webster,2019). There is no doubt that AI has enormous potential, and that computers and robots are slowly approaching ever closer levels of human intelligence. Does this mean that AI is becoming an increasingly serious competitor for human jobs? The debate is served. Perhaps the day is not far off when human supremacy over machines is questioned. Be that as it may, everything indicates that AI is going to bring great changes to our daily lives and society in general. The impact of AI on tourism firms and employment is expected to be massive, resulting in highly interconnected organizations whose decision-making will be based on analytics and autonomous exploitation of Big Data to cope with increasingly intense global competition.

## Types of Artificial Intelligence

Contrary to popular belief, AI does not make us humans smarter. Certainly it is not going to replace the owners and managers of the firms in making business decisions in the short term. However, AI may make business leaders a little less prone to bias, or at least start to question it, so they can better allocate resources where they're needed and perhaps make organizations more agile (Andersen et al., 2018).

There are three main types of AI according to the literature on the subject:

-   **Narrow artificial intelligence** (also known as weak AI) is that AI with limited learning and adaptation abilities and that can only be used in routine and/or repetitive tasks. Narrow AI is applied in very specific fields where AI is better and works faster than humans (e.g., to identify tumors, play chess games, play a videogame). This type of AI represents the current stage of AI development.

-   **Artificial general intelligence** (known as strong AI) is more powerful than weak AI and is focused on more complex tasks that involve the processing and learning of Big Data. Therefore, it is an AI very close to human intelligence and can even surpass it in some specific fields (Lv et al., 2021).

-   **Artificial superintelligence** is the self-aware AI, i.e., the AI that performs better than humans in all areas. For now, this AI is more science fiction than reality, but it seems that it is the way we are heading.

Another very popular classification of AI is the one proposed by IBM, which differentiates four types of AI according to the degree of human intervention and the type of systems in which the AI runs:

-   **Assisted intelligence** is AI based on systems preprogrammed by humans that do not have the ability to learn from their interactions with the environment in which they operate. This type of AI can perform routine and repetitive tasks at high speed and is therefore good at helping humans perform certain tasks in a more agile and efficient manner.

-   **Automated intelligence** is AI intended to automate manual or cognitive tasks, whether routine or non-routine. This type of AI is good when it comes to automating existing tasks that don't involve creating new ways of doing things.

-   **Augmented intelligence** aims to help people make better decisions. It is an AI oriented to constantly learn from humans and the context that surrounds them.

-   **Autonomous intelligence** is AI focused on automating decision-making processes, for which it adapts to the different contexts and situations that arise. This AI works autonomously (without human intervention), which means that it is the type of AI most similar to the human being.

AI is one of the fields of science that arouses the most admiration today, but it is also one of the most feared, especially when we refer to artificial superintelligence. Hollywood productions are tapping into this burgeoning El Dorado as a great source of inspiration and are largely to blame for society's not very favorable image of AI. However, in real life, machines are still in the early days of achieving this kind of superintelligence, and narrow artificial intelligence is as far as software engineers have come. This is the kind of AI this book will be referring to.

## General Applications

Perhaps the biggest challenge society and business face when it comes to AI is how to reap the benefits that AI technologies promise and how to seize the opportunities in fields as diverse as the creation of new products and services or the improvement of productivity, while avoiding the dangers of job loss and wealth redistribution. Some of the most characteristic applications of AI have to do with improving decision-making, reinventing business models, and reshaping the customer experience. According to Gartner's latest surveys of technology trends, AI ranks at the top of global trends in strategic technologies. This situation contrasts, however, with the fact that only 59% of business organizations worldwide are collecting information to develop their AI strategies.

The new wave of AI technologies is helping to improve the ability of businesses to make predictions using data, with AI being a key driver that is substantially lowering the cost of making predictions and bringing them closer to smaller organizations. In general, both firms and the AI industry seem to agree that AI offers significant opportunities to improve data analytics and decisionmaking, as well as process automation, such as communication with customers, accounting processes, supply chain, reservations, etc. A recent investigation by Davenport and Ronanki (2018) on 152 projects spanning a wide range of functions and business processes based on AI systems, classified AI applications into three categories:

-   **Process automation:** It is the automation of back office and financial processes using robotic process automation (RPA) tools. This is the most common and cheapest type of AI application in firms today (i.e., data transfer from email systems and call centers to registration systems, reconciliation of failures in charging for services, reading of legal conditions and contracts). RPA is a more advanced automation technique than previous tools, since "robots" act like humans, processing vast amounts of information from multiple IT systems.

-   **Cognitive insights:** Detect patterns in large volumes of data and interpret them using machine learning algorithms (i.e., anticipate what a customer is most likely to buy, identify when fraud is about to occur, automate personalized targeting of online ads). It is the second most common type of AI applications among firms.

-   **Cognitive engagement:** These are applications in which employees or customers get involved through chatbots, intelligent agents, and machine learning, tackling issues from password requests to tech support questions to product and service recommendation systems. In general, these types of AI technologies are more used by firms to interact with employees than with customers.

## Applications in Tourism

In the past few years there has been a rapid growth in the adoption of AI technologies by tourism firms. AI technologies have been progressively incorporated into tourism firms on the basis of enabling technologies such as Big Data, analytics, Internet of Things (IoT), cloud computing, voice and facial recognition, service robots, etc. (M. Li et al., 2021). One factor that has favored a higher pace of AI adoption has been the public health emergency caused by COVID-19. The COVID-19 pandemic has made AI technologies go mainstream to prevent, or at least reduce, social interactions in service sectors, which in the process has affected management decision-making and partially replaced some human tasks. From the customer's point of view, AI applications have reduced the level of person-to-person (and face-to-face) interaction and enabled new technology-enabled service encounters. These have impacted customer experiences and behaviors to the point of reshaping service interactions in many cases. In addition, owners and managers have felt compelled to gain insight into what AI-enabled service encounters look like and how they may affect customer service performance. Some of the main applications that AI technologies are having in tourism firms are presented below, among which recommendation systems and customer sentiment analysis stand out due to the frequency of cases found, followed by prediction solutions, facial and image recognition solutions, and service personalization (Pinheiro et al., 2021).

### Big Data and AI

Big Data technologies are among those that have fostered most the development of AI in recent times and contributed to its current boom. Big Data analytics done by humans is time-consuming and using AI techniques can help make sense of Big Data faster and more effectively. The benefits of adopting Big Data strategies with AI in tourism firms range from greater efficiency in processes and improved productivity levels to improved customer experience, which can also be more personalized (Samara et al., 2020). Despite these well-known benefits of the combined use of AI and Big Data, there remains a pressing need to better understand the synergies between the two, given the increasingly important role they are playing for tourism business competitiveness and resilience (Duan et al., 2019).

#### Sentiment analysis in online reviews

The increasing use of social media is making consumers increasingly willing to share their experiences and opinions about the tourism products and services they consume. The volume of online reviews that appear on social media and specialized blogs on different aspects of tourism activities has not stopped growing and consumers are increasingly using them to inform themselves and make decisions about their next trip. This information is of great value to tourism firms, which by knowing the comments (positive and negative) of tourists, can address issues relevant to the business and make decisions on specific aspects of their value offering and service delivery.

#### Personalized recommendation systems

The huge amount of information that is continuously generated about places, attractions, activities, accommodations, restaurants, and the ratings provided by tourists have made travel planning a highly demanding and time-consuming task. Consumers use recommendation systems as decision support systems, as well as a mechanism to overcome information overload. These systems are increasingly used through online platforms with the aim of actively recommending relevant information to customers, based on an increasingly precise knowledge of behavior patterns and particular interests of consumers.

### Demand forecasting

Forecasting visitors' demand is important for business owners and managers to understand what is driving consumption of their products and services, how they can respond to increased (decreased) demand, and how they can anticipate certain future events. With this knowledge in their pocket, tourism firms can establish much more effective management strategies that help them maintain a quality offer and adjusted pricing policies, allocating their capacity and the working hours of their staff more efficiently.

### Cancellations forecasting

In the hotel industry, for example, reservation cancellations affect management decisions and prevent firms from making accurate demand forecasts and effective revenue management. To mitigate these undesirable effects, many hoteliers resort to overbooking strategies and cancellation policies that are restrictive, which in turn can have a negative impact on revenues and on the firms' own reputation. When reservations that are likely to be canceled are identified early enough, hotels can take action in advance to avoid cancellation by offering extra services, discounts, or other benefits that customers like.

### Monitor price changes

It is important that owners and managers are aware of the factors that affect the market in which they operate and closely monitor price changes as they occur. By monitoring prices, they can anticipate changes that may unexpectedly affect their business. This is especially important because tourism products and services cannot be stored and must be consumed on the go. The issue of prices also has a direct relationship with the online reputation of firms, since part of the experience perceived by customers depends on the relationship between the value and the perceived quality of tourist services.

### Image recognition

Image recognition has become an innovative tool to identify and classify people and scenarios in many industries. It has been around for some time since mobile apps began helping visitors to national parks in South Africa identify animals, and as a way to captivate visitors while there was a lack of professional rangers. Today, these types of AI-based tools are used for facial recognition and to analyze emotions or measure customer satisfaction when tourists consume a product or service. Other use cases of AI in tourism include identifying influential attributes of a place, evaluating how online reviews affect firm performance, evaluating employee satisfaction, and market segmentation. The use of chatbots for recommendations and the application of facial recognition systems in hotels, attractions, or airports is also becoming very common.

## Service Encounters and AI

A service encounter is the type of social exchange that has traditionally taken place between service actors in person-to-person mode. This double-sided view has so far emphasized the role of customers and employees, ignoring nonhuman factors involved in service interactions, such as service facilities, atmosphere, or the environment. However, with the introduction of AI technologies, service encounters have started to change drastically. These changes have been further accelerated by the COVID-19 pandemic, which has seen many tourism business owners and managers implement AI for the benefits it offers in the new post-COVID-19 business environment. The question to be elucidated is how service encounters are going to change after the implementation of AI in frontline services.

With Big Data entering the scene, AI has rapidly penetrated service processes in a quest for tourism firms to remain competitive. More and more tasks are being automated and becoming "smarter" as customers play a more prominent role in services due to AI and co-creation of service value. Ultimately, human--AI interactions have been embedded in service encounters, the quality of which depends not only on customers and employees, but on smart technologies. Today, AI applications facilitate, guide, replace, and even enhance human--robot interactions by providing information that is relevant to the customer. This is driving tourism firms to deepen their knowledge of the specific attributes of AI that can favor these interactions and improve the experience of customers and users. Based on the new features of service encounters and AI, four modes of AI-based service encounters can be defined (M. Li et al., 2021).

-   **Supplemented with AI:** These encounters take place when AI and human employees serve customers separately and independently. Among the main capabilities that AI can provide is that of offering guidance, i.e., the AI integrated into a mobile application can guide a hotel guest when ordering a meal, although it will be the human employees who will serve the food on the table. When AI is combined with Big Data and machine learning technologies in mobile applications, service providers can gain more flexibility to interact with customers and, in the process, provide smart recommendations based on the customer's search and browsing patterns or the purchase history. Smart recommendations are based on built-in AI that automatically matches customer needs with services based on customer information. AI-enhanced service encounters on social media platforms take place through the exchange of ratings and recommendations. Virtual reality is another relevant application of AI that can be used to complement employee service encounters, creating a simulated world that customers can immerse themselves in and enhance the service experience. Smart virtual reality service encounters can bridge the gap between customers' service expectations and actual service performance, as well as add novel experiences for tourists.

-   **Generated by AI:** AI technologies are so powerful that they can independently serve customers at service points without the presence of employees. AI can replace routine human work and decision-making and directly engage with customers in a fast and personalized way. In the end, AI service encounters reduce unnecessary human interaction and provide customers with efficient and convenient services (i.e., when queuing), creating novel experiences, and achieving greater flexibility and customer satisfaction. Technologies in this category include self-service devices, smart home systems, and chatbots. As far as employees are concerned, AI-generated service encounters lack the human touch.

-   **Mediated by AI:** These are technology-mediated remote service encounters that expand the capabilities of human employees, such as when a robot performs production or distribution tasks (i.e., robots that deliver food and drinks in a hotel). In this mode, the AI is used to overcome the barriers of time and space of services and reduce costs for customers and service providers. For example, customers can book accomodation through online services offered by social media. Compared to traditional face-to-face service encounters, AI-mediated services can lead to decreased customer satisfaction. However, combining the right AI attributes with employee personality can offset this adverse effect.

-   **Enabled by AI:** These are service encounters where AI technologies and employees jointly provide services to customers. These services are based on cooperation and interaction between AI, employees, and customers. AI can register information about customer preferences and access Big Data over the internet, which can better feed a customer relationship management system (CRM) and deliver more efficient and personalized customer services. This modality differs from the previous ones in that the robots have a higher level of autonomy, intelligence, as well as a greater storage and data retrieval capacity. Special attention must be paid to the design of the robots (i.e., its operability, way of making notifications), the characteristics of the customers (i.e., cultural, socio-economic level, personality) and service policies (i.e., complaint management, levels of service) as these are key factors for customer acceptance and satisfaction with the service.

Owners and managers must reflect on the AI technologies that best fit their business processes and services. For example, there are hotels that have implemented contactless smart services to allow customers to check in quickly, locate their rooms by following service robots, have an informal conversation with chatbots, or get information without interacting face-to-face with employees. It is important that when evaluating AI technologies, owners and managers assess those factors related to customer segments, internal business processes, and the market in which they operate in order to transform threats into opportunities.

## Challenges of Artificial Intelligence

The rise of AI has sparked many controversial opinions in recent years. On one side are those, like former IBM CEO Ginni Rometty, who argue that AI technologies will help us become better and elevate the kind of things the human condition can achieve. On the other hand, relevant figures such as Stephen Hawking or Bill Gates have stressed that the development of complete AI could mean the end of the human race and that this should concern us all. Surely what these very different views are telling us is that it is essential that we humans continue to dig deeper into how people can co-exist with AI and how we can minimize the negative impact of these technologies.

Both AI developers and large corporations in the tech industry continually make claims about the great benefits and substantial impacts that AI is going to have for consumers and firms. Even some surveys, such as Davenport and Ronanki (2018), have estimated that three-quarters of firms believe that AI will substantially transform their business in about 3 years. But, what are the main challenges facing business organizations in relation to AI? One of the main challenges is decision-making. It is widely believed that AI can help employees in organizations to make better decisions, increase their analytical skills, and, in general, increase their creative capacity and respond to changes in the environment. However, with the advent of AI, what appears on the horizon is a new human--machine symbiosis that leaves questions such as: How can humans and AI complement each other in organizational decision-making? And, how can firms optimize the collaboration between humans and AI and work effectively in the human--machine interface? The answers to these questions are not simple, even more so when most AI systems do not reveal their functioning or how the algorithms work. This lack of transparency prevents AI users from knowing why decisions are made in a certain way. Solving this problem requires both researchers and industry to make AI more understandable and explain how the algorithms work. Most likely we will have to wait a few years to answer all these questions with clear evidence. Furthermore, most claims about the great impact that AI is going to have are not sufficiently supported by empirical evidence or rigorous academic research, so it is still difficult to know precisely how, why, and to what extent AI systems are going to affect tourism firms.

We could add the problem of how to measure the benefits (and impacts) that AI has on decision-making, encompassing the social, economic, and business perspectives (Duan et al., 2019). As with most technologies in the smart ecosystem, both researchers and the technology industry have focused on selling the great benefits of the application of AI in the different contexts of tourism, such as travel, destinations, and hospitality. However, much less effort has been devoted to measuring the impact that AI has on the firm and delving into the transformation of organizations. This is all the more relevant as it is clear that organizations committing to the use of AI face more than the usual hurdles when adopting any unproven and largely unknown technology.

To harness the full potential of AI, tourism organizations will need to reorganize themselves differently from within. They will also need to implement new management techniques and interact with new scientific methods that allow them to respond more quickly and effectively to their environment (Andersen et al., 2018). Before embarking on AI initiatives, tourism firms need to have a good understanding of what type of technologies do what tasks, and the strengths and limitations of each of them, as well as the barriers to implementation and the critical success factors.

The advancement of AI technologies continues at breakneck speed, with faster and more advanced systems appearing every day that can tackle more complex tasks that require cognitive skills, such as sensing emotions, making unspoken judgments, and executing processes without human supervision. In short, the changes brought about by AI are likely to be as disruptive as those of the Industrial Revolution, if not more. The speed at which changes will occur will depend on the rate at which AI technologies can automate and replace non-repetitive mental tasks currently performed by humans, and smart software (capable of developing new programs on its own) becomes available

## The Future Role of Humans

In the new context drawn by smart technologies and AI, business owners and managers are starting to ask themselves: What will be the role of humans when computers and robots can perform practically all our tasks the same or better and much cheaper? What will we humans do then (Makridakis, 2017)? There are four scenarios that can give us some answers to these questions:

-   **The optimists:** The optimists led by Ray Kurzweil (Kurzweil, 2005; Kurzweil et al., 1990) predict a utopian future dominated by genetics, nanotechnology and robotics (GNR) that revolutionizes everything and in which humans are capable of taking advantage of speed, memory, and the ability to share knowledge through their brains connected to the cloud. Genetics would make it possible for humans to change their genes to prevent disease and delay aging; nanotechnology, through 3D printers, would allow virtually any physical product to be created from cheap materials and information, leading to unlimited wealth creation; and, ultimately, robots would do all the real work, leaving it up to humans to decide how to spend their time doing activities of their choosing.

-   **The pessimists:** They argue that the most powerful technologies of the 21st century (robotics, genetic engineering, and nanotechnology) are a real threat to humans to the point of becoming an endangered species (Joy, 2000). For them, the optimists underestimate the true magnitude of the challenge and the risks that thinking machines and intelligent robots entail. As social problems become more complex and machines more intelligent, people will tend to let machines make important decisions for humans, in the belief that decisions made by machines will get better results than those made by humans. Machines will eventually take control of all important decisions for people, who will be reduced to second-class status, some say even the equivalent of computer pets. What will then happen to society and our daily lives when non-conscious but highly intelligent algorithms know us better than we know ourselves (Harari, 2016)?

-   **The pragmatists:** They believe that humans should learn to exploit the power offered by computers to increase their own capabilities and always be one step ahead of AI, or at least not be at a disadvantage (Markoff, 2016). In case of danger, pragmatists suggest that all thinking machines can be disabled to render them inoperable and propose that AI technologies always be controllable through "OpenAI" and effective regulation.

-   **The doubters:** They do not believe that AI will even be possible and that it will ever pose a real threat to humanity. For them, human intelligence cannot be replicated or captured in formal rules and AI is nothing more than a fad brought by the computer industry (Dreyfus, 1972). Moreover, computers will never be able to be creative, as this would require breaking the rules and become anti-algorithmic (Jankel, 2015). It is true that some of the criticisms of the doubters have been valid for much of the last century, but today in the face of new developments in AI it is much more difficult to maintain them. For example, they criticized Herbert Simon's prediction that a computer would be able to beat the chess champion in a few years, and Deep Blue became the world chess champion in 1997. Moreover, we are not too far from machines being able to do all the work that humans can do, as there are autonomous vehicles, robot-nurses that take care of the elderly, and Google Search, which knows what we are looking for better than we do.

The scenarios outlined above provide arguments of all kinds for and against the adoption of AI technologies. It is perhaps too early to opt for any of these scenarios considering that we are still at a very early stage in the development of AI. Furthermore, uncertainty surrounds everything that is going to happen in the coming years with AI and how tourism firms will be affected. Müller and Bostrom (2016) posed the following question to hundreds of AI experts in a series of conferences: "\[...\] assume that human scientific activity continues without major negative interruption. By what year would you see a (10%/50%/90%) probability for such HLMI (high-level machine intelligence) to exist?" The median answer for the 10% chance was 2022, the 50% chance was 2040, and the 90% chance was 2075. Ultimately, most AI experts thought that AI was not that far away and more believed that it will have a positive effect on humanity.

## Discussion Questions

-   What implications will AI have for the owners and managers of tourism firms?

-   What do you think the role of humans will be when computers and robots can do their job as well or better, and much cheaper?

-   What are the main applications that AI is having in the tourism firm? What will be the next applications?

-   Which actors of the tourism ecosystem are the most benefited (affected) by the implementation of AI?

-   What negative effects can the application of AI-based technologies have on the experience of tourism consumers? How can these effects be avoided?

-   What internal and external factors does the implementation of AI in tourism firms depend on? What role does leadership play in them?

-   What are the consequences of the adoption of AI-based technologies for the people and internal resources of the organization?
