---
title: "Managing Transformative Change"
---

Smart transformation initiatives have the potential to structurally change tourism organizations. This requires the implementation of new management practices based on the incorporation of dynamic capabilities, ambidexterity, and greater organizational agility, which means that cross-functional collaboration within the organization plays a crucial role (Vial, 2019). While it is an old recurring theme that has been at the forefront of organizational transformation management discussions for years, the truth is that even today it is difficult to see these forms of collaboration emerging within business firms to facilitate seamless integration of change strategies with the rest of the firm's key strategies, such as IT strategy or human resources strategy.

To overcome the collaborative gap that persists in most organizations, many firms create separate organizational units giving them greater independence. These units often function with greater autonomy and flexibility than the rest of the firm's organizational units, making it easier for them to focus on innovation while maintaining access to the rest of the organization's resources. Alternatively, other organizations create cross-functional teams that remain under the umbrella of the core organization itself. The fact that a number of multifunctional teams coexist in the same organization is a factor that favors the creation of internal networks based on knowledge and skills that transcend the traditional organizational structure, thus strengthening collaboration and the exchange of knowledge within these networks for the benefit of all. This is just one example of the changes that smart transformation brings with it, so let's examine a few others that tourism business owners and managers will need to consider.

## Changes in the Organizational Structure

For smart transformation to be successful, an organization will need to turn its culture upside down. For example, issues such as the traditional separation between the business and systems/IT areas, so ingrained in organizations that have been operating for years, will no longer make sense in the context of the smart firm. Instead, the need for the smart firm to work with agility and adapt its value offering quickly and accurately to the changing customer needs and preferences makes it necessary to cultivate a very different culture based on the value of collaboration and shared knowledge. This new "smart" culture must be based on inspiring leadership that attracts the interest of all members of the organization towards an innovation-focused vision, regardless of the department or area to which each individual belongs. Smart firms need smart leaders, who work to build an agile organizational culture focused on innovation and encourage people to cultivate an appetite for experimenting and taking risks, being aware of all the benefits that people can bring to the organization as a whole.

At times, smart firms will have to create new leadership roles that assume the responsibility of scaling the smart transformation processes and technologies to the rest of the organization, while keeping them aligned with the rest of the firm's strategies and the principles of agile work. New roles such as the Chief Digital Officer (or Chief Transformation Officer) aimed at ensuring that digital technologies are used appropriately and in line with the organization's objectives, reveal the strategic value of digital transformation for many organizations. In other cases, Chief Data Officers take on the role of extracting value from data and provide refined insights to improve decision-making by business leaders. Most of the time these roles are created by smart organizations with the intention of transcending their own departmental boundaries and implementing actions that transcend the organizational logic to achieve superior collaboration between the organization's business and technology functions. In the context of the smart transformation, all changes in the organization's structure and culture inevitably lead employees to take on new roles that were traditionally outside their duties. Many of the attributions and responsibilities of employees based on their position within the hierarchy of the organization will become blurred, and organizations will focus more on the individual skills of each employee, their leadership capacity, and the value that their initiatives can have for the organization. For example, employees who were previously not part of the IT function will start leading technologyintensive projects in smart organizations, just as IT function specialists will take on more business-related roles.

As organizational structural changes advance in the tourism firm, it is important for owners and managers to be aware of the need to improve the skills and abilities of employees. For example, people will need to increase their data analytics and technology skills to solve increasingly complex problems that involve a large number of interconnected variables. This also includes the redefinition of the professional profiles that the tourism firm will need to boost transformation in the coming years, part of which will come from new hires outside the firm and others from internal promotions within the organization. Leading the employees in the transition to the smart organization will therefore entail important challenges that will surely involve significant changes in the human resources function of the firm.

## Changes in Strategy

Tourism firms need to establish new management practices to govern the set of changes that are taking place and adapt to the new reality emerging from the Smart Revolution. The way in which firms establish and deploy their transformation strategies depends to a large extent on the competitive position of the organization compared to other firms in the ecosystem (Bala, 2018; Reis et al., 2018). Firms should formulate a transformation strategy plan that serves as a core element around which the firm coordinates, prioritizes, and implements all the actions that are aimed at the firm's smart transition.

However, establishing a strategy in an environment as changeable and unpredictable as the one surrounding the tourism firm can be a daunting task. If conditions are constantly changing, even the best plan is almost certain to fail (Andersen et al., 2018). In addition, smart technologies such as Big Data, analytics, and artificial intelligence (AI) are blurring the boundaries that used to exist between technology and business management, and new concepts and tools are emerging that change the way firms address management challenges, innovate, build relationships, and behave (Vaska et al., 2021). Therefore, tourism firms must approach their business transformation strategy by making it as adaptable and comprehensive as possible.

Organizations that are used to working the "agile way" and that know how to extract value from data will be in a better position to establish a smart transformation strategy. They will find it easier to adopt experimental approaches under conditions of uncertainty and will be able to overcome the traditional barriers between strategy formulation and execution, as they are accustomed to working in short iterative cycles rather than sequentially. These organizations usually establish results objectives, assign a development team the responsibility of proposing solutions, and, after these are tested with the customer or users, they decide to implement the ones that work (Andersen et al., 2018). Once the cycle is complete, the firm starts a new cycle of formulation and execution of the strategy.

A smart transformation strategy must necessarily have a wide scope and include far-reaching initiatives. It should seek to integrate and give coherence to the set of apparently independent or unconnected initiatives carried out by the organization, such as those related to products, customers, markets, or distribution. Due to its transversal nature, the smart strategy will cross the boundaries of all other strategies of the firm, including the business and technological strategy. For example, the firm's IT strategy focuses on managing IT within the organization and setting the roadmap for future business applications, infrastructure, and technologies. As such, it is essential for the development of operational activities in the organization and it should remain aligned with the firm's data strategy, which is responsible for the processes aimed at capturing value from data (Fig. 17.1).

![Fig. 17.1. Relationship between smart transformation strategy and other corporate
strategies. Source: own elaboration](/img/fig27.png){width=600}

A smart transformation strategy goes beyond the conventional approach of change strategies focused on processes, since it includes a broad repertoire of changes, some of which are disruptive and can affect products and services, resource allocation, and the business model. Unlike a digitalization strategy, a smart transformation strategy has a much broader scope and pursues more ambitious goals. Furthermore, its effects extend to products, processes, and organizational aspects, which is why it requires a governance framework capable of integrating all the initiatives that result from the integrated use of smart technologies with the power of data and shared knowledge.

That said, there are no guidelines that show firms how they should proceed with their smart transformation initiatives in a specific industry. Furthermore, the tourism business environment is continually evolving and there is great uncertainty regarding the assumptions underlying smart transformation strategies. Therefore, it is important for tourism firms to continually monitor and re-evaluate their transformation strategies, testing initial assumptions and the progress made by transformation (Matt et al., 2015). In the event that expectations are not met or deviate from the goals set, the organization must implement processes that connect evaluation with the formulation of strategies, in a way that the credibility of management is guaranteed, and biases are avoided.

## Changes in People

Due to the wide and diverse scope of smart transformation strategies and the impacts they have on organizational, technological, and operational aspects of the business, it is important to ensure that organizations have the necessary human resources, leadership, and responsibilities to address a strategy like this. If the firm approaches its smart transformation strategy without determination, leadership, or commitment, it will almost certainly lose momentum and start to have operational problems everywhere.

Tourism firms have some peculiarities that distinguish them from firms in other industries, including some related to the human dimension. The strong seasonality of the tourism business and the low-skilled and part-time workforce that are so common in tourism firms affect the way organizations design and implement their transformation strategies. Tourism firms often have difficulties in retaining their staff, which can end up affecting the delivery of quality products and services, and make knowledge management and innovation hard, especially if people continually enter and leave the firm and many resources must be devoted to recruiting and training new staff instead of engaging in higher value-added tasks (Pesonen, 2020).

On the other hand, the tourism firm must ensure that the person (or people) in charge of the smart transformation have sufficient experience in change projects and that their roles and responsibilities are aligned with the objectives and processes of the transformation strategy. Besides hiring the right people, owners and managers must decide how to blend the different leadership roles within the strategy, depending on the depth and duration of the transformation, as well as ensuring that the different roles (e.g., CIO and CDO) remain aligned at all times. The ability to delegate leadership to other people is not a given in tourism firms, where most of the time (especially in SMEs) leadership is exercised by the CEO or the owner of the firm, who is the one who makes most of the decisions that affect the future of the organization.

Tourism firms must redouble their efforts in training their employees as they join the new culture of "smartness". Employees need to develop new skills and abilities related to innovation and new technologies (including hardware and software); be excellent at managing customer relationships and handling digital communication channels; be able to search, organize, and process information from scattered sources; and be autonomous in making decisions about how to organize their work to achieve the established goals. Organizations not only acquire these new skills and capabilities by promoting internal staff, but also by outsourcing services, creating alliances with specialized firms, and even through mergers and acquisitions of other firms highly competent in these fields. According to some studies, the firms that attach more importance to the role of people in transformation processes are the ones that invest the most in training their employees and are better prepared to face the challenges of technological change and innovation (Madera et al., 2017). These firms confirm that the knowledge of the organization and the skills and abilities of the employees are closely related to the performance of the firm, its efficiency, and its competitive capacity.

Owners and managers must therefore keep in mind that human resources' function is critical in the new smart organization. It is responsible for improving the quality of the organization's human resources and ensuring that the skills of the workforce are aligned with the new needs posed by the Smart Revolution. The human resources department can shape the skills, attitudes, and behaviors of employees and make them unlock their full potential and improve their contribution to the business. It is also responsible for establishing the incentives available to employees to contribute to the results of the organization. Notwithstanding the foregoing, a large number of tourism firms, especially the smaller ones, do not have a human resources department, or if they have one, their human resource management practices are flawed when it comes to recruiting, evaluating, and rewarding the employees. This affects the way of managing knowledge within the organization and reduces the firm's chances of hiring the right people to tackle the organizational transformation processes required by the Smart Revolution.

## Changes in Business Models

Smart transformation brings with it a new conceptualization of business models and new requirements for capabilities to create, deliver, and capture value. With the Smart Revolution, new opportunities are created so that firms can co-create value with customers, expand their catalog of products and services (making them more flexible and better adapted to customer tastes and preferences), and accelerate the development of new ecosystems dominated by value networks. In this context, tourism firms must rethink new ways of creating and delivering value, as well as developing abilities and skills to capture value generated from a more intimate and lasting relationship with the customer.

One consequence of the above is that the business models of smart firms, that is, the mechanisms put in place to create, deliver, and capture value, are undergoing a radical change that affects each of its individual components. This is due to the different way in which firms approach the creation of value propositions, deliver value, segment customers, and discover new sources of revenue that did not exist until now. In the end, business models are so relevant that there are authors who affirm that the future of digital firms and, by extension, of smart firms, will be based on value architectures able to cope with constant changes in customer value, rather than on business models as we knew them (Brown & Brown, 2019).

Firms' business models have evolved from rigid structures that are difficult to adapt to changes in the environment, to open and permeable frameworks capable of responding quickly to changes of a business, technological, and market nature that occur in the environment. Some of the components that have traditionally been key in the architecture of business models (i.e., customer segments, channels, key partners) have lost relevance in favor of technology, collaborative relationships with stakeholders, the ability to manage organizational knowledge, and the personalization of value propositions. This reflects how radically different smart firms are approaching the processes of creating, delivering, and capturing value. Unlike the conventional business models, those of smart firms consider data flows to be a core asset of the organization and, as such, they play a central role in the processes of creating and delivering value. A direct connection therefore exists between smart technologies, knowledge management, organizational culture, and business models in the smart firm.

## Barriers to Transformation

Although the Smart Revolution and its effects both in tourism firms and in tourism ecosystems are here to stay, the inertia of organizations and resistance to change are factors that can seriously hinder the progress made by smart transformation. Inertia becomes relevant when the organization's own resources and capabilities become a barrier to the transformation of the firm, limiting its own ability to innovate and hindering the adoption of new technologies that can make processes and practices evolve. These issues are even more apparent when firms have been established for years and have had time to develop habits that are deeply ingrained in the core processes of the organization, such as in production processes, customer and supplier relationships, and decision-making. Over time, some of these practices turn rigid and become part of the employee culture. When this happens, the problem is not that the leaders of the firm are disconnected from reality and do not understand the potential benefits of the Smart Revolution for the organization, but rather that the very culture of the organization and the daily practices that make it work inhibit the capacity for change and the innovative power of smart transformation in the organization.

On the other hand, the resistance of employees to change and the adoption of smart technologies is another powerful barrier that owners and managers must consider. Sometimes resistance is a byproduct of organizational inertia that is embedded in daily work processes and employee mindsets due to their distrust (or even fear) of the unknown consequences of change. Other times, resistance is just a reaction to "innovation fatigue" that arises from the sheer number and rate of changes taking place within the organization. In the end, resistance to change cannot be easily overcome by simply asking employees to behave differently or develop different habits. It requires the processes of the firm to be reconfigured to accommodate flexibility and agility.

Both inertia and resistance to change keep the debate open about what should be the right path and the pace at which smart transformation should be implemented in tourism firms -- a question for which there is still no optimal answer that can work for all firms. The appointment in many organizations of a Chief Digital/Transformation Officer proves to be a lever of change that ensures that new digital and smart technologies are used in a way that is consistent with the culture and objectives of the organization, and that it is possible to achieve a balance between exploiting its potential and acceptance by the firm's employees.

## The Role of Government

Governments have an important role when it comes to promoting the smart transformation of tourism firms, as they have the capacity to create the right conditions that promote the development of new business models and thriving ecosystems (OECD, 2020). The complexity that the regulatory and normative environment has reached around the tourism firm, together with its unique characteristics, can negatively affect the risk perception of the owners and managers and make it difficult for firms to adopt smart technologies. Tourism firms need a public policy framework that is consistent with the real problems of businesses, consumers, and markets, and that addresses the profound changes that are taking place in the ecosystem, providing them with legal certainty to invest in and reap the benefits of the Smart Revolution.

A well-structured public policy framework implies, according to the recommendations formulated by the OECD, combining short- and long-term initiatives that encourage the adoption of digital and smart technologies by tourism firms, reinforce the commitment of SMEs to transform, and encourage new management approaches oriented towards the development of a culture focused on digitalization and the use of data. Some of the policies that the public administration can implement are as follows:

-   Lead the smart transformation policies in tourism. Governments can take the lead in establishing framework conditions that facilitate the development of new business models, value networks, and improved tourism ecosystems through smart technologies. These public policies might include:

    -   Create a support framework for tourism SMEs through the modernization of the regulatory framework that fosters innovation and promotes competition.

    -   Promote the creation of new entrepreneurial initiatives through technology project incubators and start-up accelerators, the facilitation of mentoring services for entrepreneurs, and the transfer of knowledge through technology demonstrators by universities and public R&D centres.

    -   Promote a free market of technological services and knowledge by supporting intermediate agents that serve as a transmission belt for the objectives pursued by public entities.

-   Encourage investment in smart technologies by tourism firms. Public policies could help boost investments by tourism SMEs in smart technologies that improve their productivity, efficiency, and capacity for innovation. The following could be put in place:

    -   Improve the access of tourism SMEs to quality human resources and market intelligence sources that demonstrate the benefits and opportunities that the adoption of smart technologies entails, thus strengthening the individual capacities of SMEs to participate in new smart ecosystems.

    -   Enable the access of tourism firms to digital and smart technologies, tools, and applications in a safe and affordable way, as well as help them with the initial investments and costs of updating and maintaining these technologies.

    -   Gather the necessary knowledge that evidences the needs and the impacts that the smart transformation causes in tourism firms. This could help to incorporate into the design of public policies the incentives, aid, or subsidies that best adapt to the real needs of tourism firms.

-   Promote innovation in business models and ecosystems through convergence, interoperability, and the adoption of smart technologies. These policies are an important complement to articulating a framework of public policies that effectively supports the smart transition of tourism firms. These actions may include:

    -   Extend the access of tourism firms and visitors to high-speed broadband (including 5G) and to data processing infrastructures, in order to promote the creation and delivery of smart tourism experiences and the exchange of knowledge between the actors of the tourism ecosystem.

    -   Promote the creation of public--private partnerships between traditional tourism firms, technology providers, and educational and R&D institutions that contribute to improving the exchange of knowledge and open innovation.

    -   Encourage the meeting of actors dedicated to complementary activities within the tourism ecosystem that encompass technology, tourism activities, and other activities to create collaborative spaces in which both emerging and traditional tourism firms can prosper.

## Discussion Questions

-   Make a list of the management practices that can contribute the most to the smart transformation of the tourism firm. Then present the list to your colleagues and discuss to come up with a consensus list.

-   How should owners and managers plan for the smart transformation process to be successful (what activities, milestones, responsibilities)? Who should be involved in designing the strategy and what roles should there be?

-   What kind of difficulties do tourism firms usually find when it comes to accessing quality human resources? What differences exist between big and small firms?

-   What new business models are an opportunity for the tourism firm in the smart era? Describe some examples and indicate the elements that differentiate them from conventional business models.

-   What type of agents do tourism firms usually turn to in search of support to spur smart transformation? What collaboration frameworks are established most frequently?

-   What intermediate agents do you know that play a relevant role in promoting the smart transformation of tourism firms? Name some examples. What kind of services do they provide that are valued by firms?

-   What public policies or programs that support digital and/or smart transformation are you most familiar with? To what extent are these policies helping to drive smart transformation?
