# A Call to Action

Tourism firms, like many in other industries, are not immune to digital disruptions and the deep structural and behavioral changes that digitalization is bringing about in the business ecosystem and in consumers. These disruptions manifest themselves in many different ways and to varying degrees, including the way tourism firms create value, the competitive landscape of tourism activities, or how firms communicate and engage with partners, suppliers, and customers. The variety, extent, and speed at which these developments are taking place are leaving tourism business owners and managers out of options, as the decision to tackle transformation is no longer a matter of choice, but a must that requires vision, determination, resources, and leadership among key members of the organization.

Firms that do not invest enough in transformation will find it difficult to survive in the future (OECD, 2020), and those who do not achieve a constant pace of technology adoption and renewal will inevitably lose their competitive edge and the big opportunities ahead (i.e., for innovation and value creation). When digital technologies are used wisely, the potential for growth and improvement for tourism firms is phenomenal (Reddy & Reinartz, 2017). On the contrary, when digital technologies are used without intelligence, everything can end disastrously (Kaivo-Oja et al., 2015).

In this cumbersome context, SMEs are at high risk of being left behind, so it is essential that they start by re-examining their business end-to-end and redesigning it if they are to leverage on the promises and gain the benefits of transformation in terms of efficiency, agility, and competitiveness (Busulwa et al., 2020). Doing so requires not only that business owners and managers understand digital technologies and their implications (e.g., the impact of privacy, cybersecurity, business models, interoperability, scalability, ethics, ecosystems, etc.). It fundamentally requires firms to effectively lead transformation internally as a process that spans the entire organization, from senior management, through middle management, to front-line employees. This is no doubt a big ask for tourism SMEs, which surely explains why so many firms fall short of expectations and lag behind in this endurance race of transformation (Lv et al., 2021).

It is obvious that a large number of SMEs do not have anywhere near the resources, talented people, skills, and knowledge necessary to successfully tackle transformation. Although the latest innovations in the field of connectivity, networks, artificial intelligence, Big Data, analytics, and automation, to name just a few examples, are opening new windows of opportunity for SMEs, they are also much more sophisticated and far from the capacity of most SMEs to activate change (Earley, 2014). Furthermore, there are still deeply rooted beliefs in many SMEs about whether it is worth investing the time and money in transformation and turn the organization upside down, since it is hard to predict and quantify the true benefits that transformation can bring and when and where these benefits will emerge. Quite often bad past experiences in the execution of technological projects and mismatches in the realization of expectations have historically contributed to this disbelief.

It cannot be denied that there may be a good justification behind these attitudes. No one can attest today, be they consultants, scholars, or technologists, how much or at what precise moment in time transformation will improve customer satisfaction, or the service experience. Notwithstanding the above, it is equally true that no tourism firm can afford today to lose customers, manage its resources inefficiently, or assume failure simply because it is unable to decide in which direction its organization should point in today's hyper-competitive and technology-centric environment (Nagle et al., 2013). The lack of a clear understanding of the strategic direction that the firm must follow and not having a tourism-specific roadmap focused on creating value (for the organization and the customer) are critical factors that very often prevent firms from advancing in the process of transformation that is needed (Udovita, 2020). Those running a tourism business must understand the fundamental nature of transformation and the implications that technological disruptions are having for organizations. Only after owners and managers are clear on what needs to change to close the gap can it become clear which strategy needs to be executed and which parts of the organization need to take the lead in the new strategic direction. With so much at stake, business leaders need to be aware that failure to act on the opportunities offered by transformation and digital technologies will have lethal consequences for the organization's ability to survive in the future.

For all of the above reasons, this book is fundamentally a call to action for business leaders and organizations alike to get down to work as soon as possible and seize the vast pool of opportunities that exist and grow tourism firms in times of the Smart Revolution. To achieve this there are no shortcuts; only the knowledge, attitude, and resources to implement an action plan can help. That is why you have this book in your hands, so that those who run a tourism SME, or intend to do so, equip themselves with the most relevant knowledge and management practices to devise and implement a smart tourism transformation plan. Firms around the world are looking for leaders who are able to understand this complex world and who know how to address the opportunities of smartization. Now here is your chance to stand out from the crowd.
