---
title: "The Future of Smartization"
---

The advance towards smartization is accelerating in the tourism industry and affects all the actors in the ecosystem, especially tourism firms. Milestones unthinkable a few years ago have been reached that are completely transforming tourism as we know it, generating new oceans of opportunities that will be exploited by a new type of organization with capabilities radically different from today's and whose business models will be built on smart technologies. Eventually, the big question is whether and to what extent the smartization of tourism firms will be good for consumers and firms themselves, and whether it will mark the beginning of an era of wealth and prosperity for all, or what is to come is a painful adjustment process with unpredictable costs in the business, economic, and social spheres for which firms and society are not prepared. In other words, where is the Smart Revolution taking us and what are the implications for the future of tourism?

Many critics of smartization fear the effects of the rate at which job obsolescence will occur due to the mass adoption of smart technologies. They argue that while the impact of the Industrial Revolution was fully felt after two centuries and that of the digital revolution took three or four decades, it may not be more than a decade or two before the world feels the full effects of the Smart Revolution. There are many who fear that the magnitude of the jobs that will be displaced is such (up to 47% of all occupations according to some studies), that the social structure in most countries will not be able to withstand this rapid and profound restructuring of the labor market (Makridakis, 2017). Even if governments were able to launch massive retraining programmes, it would not be easy to avoid major social disruption, as the new jobs will require skills that are not readily available. This concerns labor groups such as taxi drivers and bus drivers, who would surely be among the first to be replaced by autonomous vehicles, but the range of jobs at stake is much broader.

The changes brought by the Smart Revolution will predictably extend to consumer buying habits, which presumably will change so drastically that they will eventually eliminate the need for thousands of jobs. Entire industries have already begun to experience these effects, such as the banking sector, where customer service offices have been closing for a few years and thousands of employees are being laid off or retired; or in retail, where neighborhood stores are closing while the volume of electronic commerce increases. This profound social and economic transformation not only affects less qualified professional profiles, but also highly qualified professions, such as financial advisors, medical specialists, or those related to high-level computing tasks, which could be at risk of being automated using algorithms made available for some time now.

Yet, despite this somewhat daunting perspective, it is perhaps fair to say that the Smart Revolution is not going to be the end of the world as we know it. It is true that the world is going to change a lot and in a short time, but we should not underestimate the ability of human beings and societies to adapt to change. In the end, it has been this ability to adapt that has brought humanity to its greatest levels of wealth. Although it is foreseeable that the vast majority of jobs that involve physical work or that have to do with data processing will disappear (78%), as they are automated or replaced by robots, many others will continue to be difficult to replace, such as those that involve some intellectual expertise (18%) or managing others (9%) (Chui et al., 2016). On the other hand, jobs related to soft skills will become even more important and will grow in the coming years.

The next question we could ask ourselves is: will the new jobs created offset the jobs lost as a result of the Smart Revolution? It is not surprising that there are answers for all tastes. There are those who argue that labor supply is fixed, and that people will compete with the rest of the factors of production (including robots) for a place in the chain. Others think that human desires and needs are infinite, and that entrepreneurs will always devise ways to harness them and create new opportunities. There is nothing wrong with finding reasons to worry, but perhaps we should not waste too much time in sterile debates that lead nowhere, such as whether the jobs emerging from the Smart Revolution will also be automatable, and focus instead on how best to prepare ourselves to face a social, economic, and business context that is going to be radically different and that will create sustainable opportunities for all.

Let us think that the Smart Revolution will surely increase the number of new firms that will exploit Big Data, analytics, and artificial intelligence (AI) technologies, with the support of new tools born from crowdfunding and venture capital that will improve their chances of success. The innovative ideas that are going to shape the Smart Revolution will come from anywhere and will not require large and expensive R&D laboratories to be devised, nor will they require large amounts of funding to be developed or commercialized (Makridakis, 2017). Today, some countries have stepped forward, given the growing importance of innovation and entrepreneurship to their economies, and continually encourage their innovators to start new businesses (e.g., Israel, China, France, United Kingdom, New Zealand). These efforts will lead to a greater openness of innovation processes in firms and will emphasize cooperation between knowledge and innovation centers around the world to accelerate technological innovation. Possibly this new spiral will result in a higher level of competition worldwide, which in turn will favor a more equitable distribution of employment and wealth among nations.

Tourism is going to experience many changes in the coming years and owners and managers must be prepared to know how to manage them. Maybe that's why this book caught your attention. It remains to be seen how the emergence of smart tourism firms will affect tourism value offerings and to what extent the authenticity of the tourist experience will be transformed. For example, in the context of smart tourism augmented reality is being used as an efficient tool to present information and add value to the tourist experience, although the true impact that the new experiences powered by smart technologies will have on authenticity and value to consumers is still unknown. Owners and managers should not forget the role that the attitudes of residents will play in places where smart tourism activities take place. Smart tourism seeks to improve the tourism experience of travelers, but also affects the quality of life of residents (Santos-Júnior et al., 2020), so there will be residents who appreciate it and others who don't. For this reason, it will be necessary for all the actors in the ecosystem to seek combinations that allow a balance to be achieved between smart technologies and the variables that affect the quality of life in local communities, such as accessibility, social inclusion, human and social capital, innovation, sustainability, entrepreneurship, etc.

The following sections examine some of the trends that will have the greatest impact on the future development of smart capabilities in tourism firms, according to the author's own predictions. These include access to the combined capabilities of Big Data, analytics, and AI (BDAI) "as-a-Service", which will bring tourism SMEs closer to realizing the promises offered by the Smart Revolution; the concern for the ethical aspects that emerge from the smartization process and that threaten the balance between firms, people, and society; the development of superior computational capacities through cognitive technologies and quantum computing, which will raise everyone's raw intelligence and bring machines closer to human reasoning (in addition to accelerating the replacement of jobs by machines in a large number of tasks); and the advances towards the connected and autonomous vehicle, which will radically transform the way we move around and experience tourism.

## BDAI "as-a-Service"

The combination of Big Data, analytics, and AI (BDAI) will generate great business opportunities and competitive advantages for tourism firms in the future. Through the integration and interoperability of these technologies, tourism firms will transform their operations and business model and, in the medium and long term, obtain significant gains in efficiency and productivity (Samara et al., 2020). The inclusion of BDAI in the culture of people will better prepare them to open new markets and explore (and exploit) new niches in existing markets, will allow the creation of new value offerings focused on the experiential component and personalization, and, ultimately, will contribute significantly to boosting tourism growth.

With the proliferation of available data and computing capabilities increasing at an exponential rate, BDAI technologies are gaining momentum. The rise of the "as-a-Service" trend is contributing significantly to this growth, with more firms accessing IT infrastructure and applications as a service though the cloud. BDAI-as-a-Service (BDAIaaS) thus represents a source of great opportunities to accelerate the incorporation of tourism firms to the benefits of Smart Revolution, especially tourism SMEs.

### How it works

BDAIaaS is an approach to provide tourism SMEs with access to the infrastructure, hardware, and software necessary for Big Data, analytics, and AI capabilities. Through this model of access and use of IT, SMEs could increase the pace of adoption of smart technologies, instead of keeping it slow. BDAIaaS offers an integrated service that merges different capabilities and technologies that are very complex by nature, making it easy for users to work with them by combining:

-   **Platform as a Service (PaaS),** so that access to the infrastructure, operating system, and databases is managed and scalable depending on the specific needs of the firm at any moment.

-   **Software as a Service (SaaS),** so that machine learning, analytical models, and visualization can be carried out in a public (or private) cloud and the firm would pay only for the services consumed.

Unlike the license fee model where customers would pay high license fees up front to install BDAI on-premises (on their own servers), the "as-a-Service" model offers customers access to BDAI capabilities on demand. In other words, instead of offering BDAI as a product subject to rapid technological obsolescence, BDAI is delivered as a pay-as-you-go service. In this way, firms do not need to make large investments in installations and updates of "packaged" solutions from time to time, thus drastically reducing the time it would normally take an installation (weeks or months). By storing all data and applications in a central hub, firms choosing BDAIaaS could avoid the high price of hard drive space and the need to purchase and maintain their own hardware. BDAI delivery time would also be much shorter, and the usual problems associated with heavy installations would be avoided. In addition, since firms might pay per user, it would be possible to choose which employees would have access to BDAI capabilities rather than buying in bulk for the entire organization, thus making IT purchasing more flexible.

### Benefits

BDAIaaS offers opportunities for data scientists to rapidly process and analyze terabytes of data from widely dispersed sources and varied formats (e.g., text, images, etc.), making possible the flexible use of the capabilities provided by solution providers according to the specific needs of the firm. Firms could have access to endless advanced BDAI capabilities that would always be up to date, through a pay-per-use model in which the firm would be the one to decide which options to "activate" and which ones to "deactivate" according to their needs. BDAIaaS providers would be interested in providing their customers with a wide variety of options that meet their needs, each at a higher price.

Since cloud computing is at the heart of BDAIaaS, tourism firms would have at their fingertips all the shared processing capacity they needed at any given time with the click of a button. Similarly, when firms no longer needed that capacity, they could simply "turn off" the cloud service and stop incurring unnecessary costs. Firms could take advantage of BDAIaaS to minimize the costs of infrastructure and implementation of the different tools, in addition to quickly extracting meaning from complex data sets created from statistical analyses and models (Larson & Chang, 2016). In short, tourism firms would substantially improve the time to value generation. Today research continues on what is the best option to deliver BDAIaaS solutions and how to make them mainstream for firms. Still, the "aaS" model is expected to grow strongly in the coming years, moving beyond the cloud to enter our daily lives through mobile devices, thus creating a rich universe of new services for consumers and businesses.

## Ethics

The ethical considerations that arise from the smartization process often go unnoticed by the owners and managers of tourism firms, as well as by the ICT industry. However, ethical behavior and decision-making in smart contexts will play an increasingly important role in the future for all stakeholders in the tourism ecosystem, since they will provide new perspectives to understand both smartization and the emerging organizational and social impacts.

The development and use of smart technologies depend on the processing of large amounts of heterogeneous data (Big Data) to drive innovation and support competitive advantage. However, smart technologies may raise ethical issues that can undermine the credibility of data-driven smart tourism firms. The importance of ethics is going to be more evident as smart transformation extends to an ever-increasing number of actors and becomes deeper and irreversible for all tourism organizations. How are fundamental values such as privacy, security, equality, transparency, and autonomy going to be affected in a smarter world dominated by Big Data? Should some data be a public good? Will consumers be bound to disclose personal data to some extent to make society safer and more efficient? (Christen et al., 2019; Yarali et al., 2020). Whatever the answers may be, owners and managers will need to decide how ethical smart practices (e.g., ethical Big Data, ethical analytics, ethical AI) are implemented within the organization, and how they are to be communicated inside and outside the organization.

On the other hand, the ethical behavior of the leaders and people of tourism organizations in relation to smart technologies has been little studied, even though there are still many decisions to be made throughout the smartization process. Most of the research on innovation and technology in tourism has focused on the effects they have on innovators, and what factors affect their adoption among users and consumers, and how they can become a source of competitive advantage. However, innovations such as smart technologies have much broader societal and individual impacts that need to be considered. An example is Airbnb, which although it originally emerged as a platform with a well-defined socio-innovative approach to sharing, today has considerable negative impacts on destinations, small firms, and people.

Consequently, ethics must be seen as a complementary approach that helps owners and managers to glimpse multifaceted perspectives of the smartization phenomenon, more so as they are currently poorly studied and have a notorious impact on both the way smart transformation is carried out and the results that are pursued. This does not mean that ethics should be used as a safeguard against the way smart transformation is taking place, but rather as an additional dimension that can help tourism firms strike a better balance between the elements that drive change and sustain performance over time.

### Ethics and employees

Firms must ensure that their business objectives do not conflict with the moral views of their employees, although this can sometimes be contradictory from the perspective of financial objectives (Vial, 2019). As the capabilities offered by smart technologies increase, firms must seek to align business model decisions with the values and principles of employees. To illustrate the relevance of this topic, take the case of Google and see how the company changed its well-known motto "Don't be evil" in the 2018 Code of Ethics revision to its equally popular statement: "And remember ... don't be evil and if you see something that you think isn't right -- speak up!" (Carbone, 2018). Despite this powerful claim, the tech company has come under fire many times in recent years by US regulators and its broad community of critics, to the point that former US Treasury Secretary Steven Mnuchin himself urged the Justice Department to review the power that companies like Google have over the US economy.

### Ethics and performance

As value creation networks in tourism become more complex and involve more varied actors, the possibility for the firm to maintain full control over its level of performance becomes a challenge. In this context, ethics plays a key role as it can guide the design and use of smart technologies to achieve short-term objectives, while making the firm sustain its level of performance in the long term (Vial, 2019). For example, some tourism firms may try to increase their proximity to the customer and personalize their experiences by anticipating latent preferences that are not always made explicit through primary and secondary data sources. Although these practices may be profitable for the firm's performance in the short term, they have sometimes been shown to be undesirable, not because they are illegal, but because some stakeholders consider them morally reprehensible. This is the case with Facebook, which is continually called out for its unethical practices and has led some prominent US business corporations (e.g., Microsoft, Verizon, Coca-Cola, Unilever, Ford, Starbucks) and civil rights organizations (e.g., the National Hispanic Media Coalition, the Anti-Defamation League, Free Press, etc.) to join boycotts on the use of the popular social network, hence the call for people not to use the social network owing to its bad ethical practices (Elgan, 2020).

Tourism firms must remain vigilant to these risks, as customers and other stakeholders are bound to become critical if certain moral values are violated. In addition, it is important for firms to demonstrate that they are using data responsibly and are not only focused on the business case. To assess ethical risks, tourism firms can start by taking the customer's point of view and asking themselves: Would the customer agree to disclose their data if they knew exactly what was being done with it? What are the possible benefits that customers would be willing to accept to provide their data (Christen et al., 2019)? In a context in which smart technologies represent an increasing part of the value proposition of tourism firms, the ethical bases in force until now (i.e., corporate social responsibility) should be reviewed on the basis of smartization, incorporating new areas of interest such as ethical performance, data governance, etc. By doing so, tourism firms will obtain a more complete and richer understanding of the phenomenon of smartization that will surely allow them to address the process with greater success. It should not be forgotten that consumer trust and acceptance are pre-requisites for the successful implementation of smart technologies. This will not only require tourism firms to inform consumers in a transparent and understandable way about how data is collected and used, but firms must also offer them freedom of choice depending on the service.

### Ethics and stakeholders

As value creation networks increase in complexity, tourism firms must satisfy the multiple, sometimes contradictory, demands of value co-creators. This issue becomes even more apparent in digital ecosystems such as platforms that, by definition, rely on multiple parties and for which data is at the core of their competitive value proposition. Firms must balance the demands of multiple parties, without compromising the firm's performance or its ability to sustain its competitive advantages over time. At times this may require the firm to redefine perceptions of what is considered right and wrong. For example, for a platform owner, an ethical challenge may be how to ensure that one party's demands are not met at the expense of others (i.e., if the platform grants access to the data to one party, then the other party should not perceive it as a breach of security and privacy).

## Cognitive Computing

Cognitive computing technologies are fundamentally different from all other forms of computing used so far. Cognitive systems continually learn from their interaction with data (structured and unstructured), contexts, and people, and thus improve their learning and reasoning capabilities over time. They may be considered the third phase of the evolution of AI, which goes from traditional AI through artificial general intelligence to cognitive systems. Similar to how human learning evolves from birth to adulthood, a cognitive system learns and becomes more intelligent over time from the information it gains each time it interacts with its environment and the experience it accumulates.

A cognitive system is different from automated systems, which are those that can sense certain parameters of the environment and perform some action according to the data they detect. For example, the light turns on automatically when we enter a smart room. This is automation. If the light changes its color depending on the moment of time, or the weather, this is cognitive. Conventional automated systems are not able to perceive or communicate human emotions -- basically what they do is process "if-then-what" conditions. Instead, cognitive systems mimic some aspects of human thought: they can learn, reason in some way, and suggest responses, incorporating emotional elements into their interaction with humans. While automated systems are preconfigured and coded by humans and follow rigid rules, cognitive systems can define their own rules through continuous learning and experience (Pramanik et al., 2018).

Cognition is also different from AI. The former emphasizes the learning process and recalls any facts that it has previously learned. AI is the ability of a machine to understand and decide what action to take and when among the given options, but it needs a set of well-defined rules codified by a human being. In other words, AI is based on the human being's perception and anticipation of possible complex scenarios and their ability to codify them in a system.

This paradigm shift from rule-based computing to autonomous learning and reasoning is changing computing forever (Hamm & Kelly, 2013). With the advent of Big Data, cognitive computing promises to unlock a vast amount of knowledge now hidden under the rich and huge amount of data that tourism firms generate. Therefore, the old dilemma about whether man or machine will prevail loses relevance to give way to a new era in which machines would not replace humans but would join them to expand their capabilities and help them make decisions by leveraging Big Data analytics (Castaldi et al., 2018; Gudivada et al., 2019). However, deploying these capabilities requires a major shift in the way business organizations approach problems, use technologies, and operate.

### How it works

Cognitive computing is based on computer systems that mimic the human brain; that is, they have the ability to process natural language, learn from experience, interact with humans, and make decisions based on what they learn. Cognitive computing systems are learning systems that use a wide range of principles and techniques from cognitive science, neuroscience, data science, nanotechnology, machine learning, and cloud computing (Gudivada et al., 2019; Noor, 2015). Cognitive systems incorporate integrated data analytics and automated management that enable iterative interaction with the outside world to capture and analyze data, reason to hypothesize, learn from experience, and interact with humans naturally to achieve specific goals. Throughout a learning process, cognitive computing systems improve over time and produce their own knowledge, reducing errors and improving the quality of analysis and predictions.

Cognitive systems are not programmed by default but can improve themselves by learning through incremental interactions and training based on previous experiences and data sets. Therefore, unlike conventional programmable computers, cognitive computing is not limited to deterministic constraints, but has a dynamic essence by continuously detecting and learning from the environment and improving its decision-making capabilities autonomously (Pramanik et al., 2018). By learning from past errors and successes, cognitive systems enable humans to discover new relationships and behaviors that would otherwise go unnoticed in a large volume of data. This unique combination of analysis, problem solving, and communication with humans in a natural way creates a new way of interacting between humans and machines, turning machines into allies to increase human reasoning ability and support decision making.

### Applications

Cognitive computing started to gain attention in 2011 when IBM's Watson computer played two champions of the TV game show Jeopardy and won. Watson had access to 200 million pages of structured and unstructured information stored on four terabytes of disk and was able to respond directly to questions posed in natural language. Today's new cognitive products span applications from cognitive cyber-physical systems (with built-in intelligence) to mechatronic components (combination of mechanics, electronics, and computation) that can monitor their own state and are capable of self-configuration, self-protection, self-optimization, and self-repair, as well as communicating with other cognitive products (Castaldi et al., 2018). The number of cognitive solutions in the market has not stopped growing, such as Watson from IBM, Azure from Microsoft, Deep Mind, Enterra Solutions, to name a few. Meanwhile, Google, Amazon, and Apple are also working on solutions focused on specific applications.

Cognitive computing technologies are game changers since they carry out some of the functions similar to human cognition (including learning, understanding, planning, solving problems, etc.) and deliver a variety of improvements in business functions, including production processes, logistics, financial management, waste management, and more. Cognitive systems can be key drivers of automation in knowledge management activities and in providing greater intelligence to the firm's products and services (Lytras & Visvizi, 2021; Noor, 2015). By applying new cognitive capabilities to existing automation, core business processes could not only run faster, but could emulate human judgment. This would help firms become more efficient and agile in their business, as well as provide meaningful information for decision makers to solve problems for which they previously had neither the skills nor the necessary resources.

Emerging cognitive systems are incorporating greater abilities to recognize behavioral patterns in Big Data, improvements in natural language processing and complex communication, increased self-learning, and other capabilities that used to be uniquely human. This opens new frontiers for distributed cognitive sensors (e.g., OrCam, Neurocam), robotic applications, and large sociotechnical cognitive systems (e.g., smart cities, cognitive infrastructures, etc.). Chatbots are an example of these systems, which today allow human--machine interaction with a high level of fluidity and dynamism. From the creation of Eliza, the first chatbot in 1966, to the present with Alexa (2015), Cortana (2015), and Woebot (2017), there are thousands of chatbots on the market with applications in fields like marketing, support systems, health care, entertainment, education, and cultural heritage, which are becoming less robotic and more intelligent (Adamopoulou & Moussiades, 2020).

The Internet of Things (IoT) is another breeding ground for the use of cognitive computing. If the IoT is not intelligent and interactive, its capacity is very limited, so Cognitive IoT (CIoT) represents a great opportunity to add more advanced functionalities and autonomous behavior. The CIoT can dynamically interact with connected "things", learn from the environment, generate meaning, make decisions, and transmit them to humans based on the domain in which the IoT is applied. This augmented IoT through cognitive capabilities would mean a giant leap towards the full potential of the IoT and would elevate "things" to a higher level of intelligence and interaction. The recent development of specialized processors for cognitive computing, coupled with advances in Big Data tools and deep learning, are driving new and transformative applications in many industries. IBM's TrueNorth and Intel's Loihi chips have been designed to emulate the functions of a human brain through thousands of neurons that form synapses interconnected through circuitry. Tests have shown that they can be used for speech recognition and pattern identification.

In the app realm, Google has released the Cloud Natural Language API (https://cloud.google.com/natural-language/), part of the larger Cloud Machine Learning API family, which provides developers with natural language understanding technologies, including sentiment analysis and of entities, content classification, and parsing. Google's rival app Microsoft Azure Cognitive Services (https://azure.microsoft. com/es-es/services/cognitive-services) aims to make AI available to all developers and data scientists through an API, which could easily add AI capabilities and accelerate advanced decision-making across a large number of applications.

### Challenges

Neuromorphic systems, which are modeled after the human brain, are among the cutting-edge cognitive computing technologies that have the potential to be more generalizable. These neuromorphic systems, based on the principles of neuroscience, are often pitted against computationdriven machine learning on the road to artificial general intelligence (also known as strong AI). The former intend to take advantage of neuroscience to achieve general intelligence from the development of processing models similar to the human brain. The latter aims to solve practical tasks leaving aside most of the principles of neuroscience in favor of brute force optimization (a problem-solving technique that involves listing all possible solutions and checking which is correct) and the use of a large volume of data (Deng et al., 2021). Nonetheless, with the help of Big Data, high-performance processors, and algorithms based on advanced artificial neural networks, the machine learning pathway has so far achieved better results than neuromorphic computing, especially in terms of accuracy. This is not meant to be a dilemma in which firms must choose between the two technologies. The real challenge lies in rethinking what the advantages of the human brain are and pointing out what should be the objectives to be achieved by neuromorphic computing to bridge the "gap" between neuromorphic computing and machine learning.

New hardware, programming languages, and applications will need to be developed in the coming years to drive cognitive computing forward. The new hardware will include neuromorphic machine technologies to process sensory data (e.g., images and sounds), and respond to changes in the data in ways not specifically programmed. Research is being carried out in the development of new neuromorphic chips that can overcome physical limitations and considerably reduce the power requirements of traditional processors. In 2017, the microprocessor manufacturer Intel developed Loihi, a neuromorphic chip with 128 cores and 130,000 neurons, which integrates memory, computing, and communication and works in parallel. In 2021, Intel introduced its second-generation neuromorphic chip Loihi 2 (Fig. 23.1), together with Lava, an open source software framework for developing neuro-inspired applications. According to the commercial information provided by Intel, Loihi enables accelerated learning in unstructured environments that require autonomous operation and continuous learning, with low power consumption and high performance and capacity (Intel, 2022). Additionally, Intel Labs, the research arm of Intel Corporation, has established the Intel Neuromorphic Research Community (INRC) as a collaborative research environment that brings together academic, government, and industry research teams from around the world with a view to overcoming the challenges of neuromorphic computing.

The confluence of cognitive technologies with Big Data, analytics, the IoT, and cloud computing will greatly expand the number of applications and the impact of cognitive computing. In the course of the coming years, a new generation of cognitive devices and systems will be developed that will be the result of the fusion of cognitive technologies with new tools and devices that will allow users to easily interact in a kind of continuous and dynamic "conversation" with technologies and will impact on the operational processes and decision-making systems of firms. Perhaps this will make it possible for humans and machines to work together in the future to extend human capabilities, especially those associated with knowledge, finding relevant patterns in large dynamic data, and making optimal decisions; and discover a new generation of cognitive products.

## Quantum Computing

The idea of quantum computing arose from the reflection made by scientists about the fundamental limits of computing. They surmised that if technology continued to comply with Moore's Law (which states that the number of transistors in a microprocessor doubles approximately every 2 years), then the shrinking size of the circuits within a silicon chip would eventually reach a point where individual elements would not exceed the size of a few atoms. Consequently, the physical laws that would govern the properties and behavior of circuits on a subatomic scale would no longer be the classical ones but rather quantum mechanics. This gave rise to the possibility of creating a computer based on the principles of quantum physics (Rao et al., 2015). Feynman was one of the first to try to answer this question in 1982 by creating an abstract model showing how a quantum system could be used to do calculations. The model explained how a machine could have the ability to perform quantum physics experiments inside a quantum mechanical computer. Later, in 1985, Deutsch proposed the possibility that a quantum computer could be general purpose and published a theoretical paper that went on to show how a quantum computer could have capabilities far beyond those of a traditional classical computer. After Deutsch published that article, the quest began to find practical applications for such a machine.

In recent years, there has been relentless progress in both quantum hardware and quantum algorithm development that has brought quantum computing much closer to reality. As an emerging paradigm, quantum computing offers the potential to provide a significant computational advantage over conventional classical computing by exploiting the principles of quantum mechanics. The world's leading technology companies such as IBM, Google, Microsoft, and Intel, as well as some ambitious start-ups like Rigetti Computing and IonQ, are racing to develop the first large-scale universal quantum computer that could solve many computationally complex and intractable problems in areas like data science, finance, drug design, etc. (Gill et al., 2020).

### How it works

Unlike classical computers, which store and process information as a series of bits that can take only a binary value ("0" or "1") and are then manipulated through Boolean logic gates arranged in succession to produce a result, the quantum computer encodes information into quantum bits (or qubits). According to the principles of quantum mechanics, qubits can take the values "0", "1", or any ratio of "0" and "1" in the superposition of both states, with a given probability of being a "0" and a given probability of being a "1" (i.e., 1/3 of "0" and 2/3 of "1"). The quantum computer operates on qubits by executing a series of quantum gates on a single qubit or a pair of qubits that are reversible. Therefore, quantum computers have access to an exponentially large computational space, where "n" qubits can be in a superposition state of 2n possible outcomes at any given moment in time. This allows quantum computers to tackle problems where computational complexity is the main bottleneck for classical machines, i.e., quantum computers can tackle problems with very large data sets with only a small number of qubits. The second key property of quantum computing is entanglement. Unlike classical bits, whose value can be set independently of other bits, qubits can have entangled states. In an entangled state, the properties of the qubits are bound together despite their physical separation. This means that measuring one qubit alters the properties of the other qubits that are in the same entangled state. Entanglement is a fundamental propriety that can exploited for dense coding and quantum simulation of correlated systems (Gill et al., 2020). Quantum computing will exploit the properties of both superposition and entanglement in such a way that the probability of the desired outcomes will increase while the probabilities of all other outcomes will decrease. Together, superposition and entanglement create computational power that can solve problems exponentially faster than classic computers.

### Applications

In the past few years, global research and development has focused on building quantum computers that support increasingly complex industrial applications. Some of the most important programs worldwide include the United States National Quantum Initiative to promote quantum research and development and increase the country's economic and national security; the Quantum Technologies Flagship initiative of the European Union, launched in 2018 and with an estimated budget of €1 billion; the UK National Quantum Technologies Program (NQTP) with ₤1 billion for collaboration between industry, academia, and government; the Center for Quantum Computation & Communication Technology in Australia; and the National Laboratory for Quantum Information Science that China is building and that has a US\$10 billion budget.

Big tech industry players are not far behind. Computer giants such as IBM, Microsoft, Alibaba, and Google are at the forefront of quantum computing developments, and new start-ups such as D-Wave Systems, Xanadu, Quantum Circuits, and Rigetti Computing compete to be the first to launch a scalable industrial computer. Ever since Google declared in 2019 that it had achieved quantum supremacy with Sycamore (a processor that could perform a calculation in 200 seconds that would take the world's fastest supercomputers 10,000 years to solve), there have been spectacular new announcements every so often. In December 2020, Chinese scientists at the University of Science and Technology in Hefei announced that they had built a quantum computer that could perform some calculations nearly 100 trillion times faster than the world's most advanced supercomputer. IBM has also announced that it has broken the 100-qubit barrier with its Eagle processor, and Microsoft has developed an open source programming language, Q#, that can develop and run quantum algorithms.

According to forecasts by the IT market intelligence company IDC, customer spending on quantum computing will grow from US\$412 million in 2020 to US\$8.6 billion in 2027. This represents a compound annual growth rate (CAGR) in 6 years of 50.9%. IDC anticipates that these large investments will see current limited quantum computing capabilities progressively overtaken by a new generation of more powerful quantum computing solutions, leading to new use cases and market segments adopting quantum computing as a source of competitive advantage (IDC, 2021). Applications of quantum computing are many and varied (e.g., modeling of commercial and passenger traffic, weather forecasting, blockchain, cryptocurrencies, etc.) and the number continues to increase every day. It is most likely that quantum computing will become a great ally of tourism firms in the future.

#### Machine Learning

Quantum computing promises to speed up machine learning algorithms to analyze classical data. Although it has not yet been fully demonstrated whether quantum machine learning can provide superior computational efficiency compared to classical methods, the results obtained in quantum principal component analysis and quantum neural networks look promising (Gill et al., 2020). Efficient searching and sorting of large data sets have become high-priority tasks for many large firms, including those in the tourism industry. Other already widespread machine learning applications such as voice, image, and handwriting recognition have become challenging tasks for traditional computers in terms of speed and accuracy. Here is where quantum computing could be of great help, improving pattern recognition and processing these complex problems in a time span that would take traditional computers hundreds of years (Jha, 2021).

However, classical database software is no longer sufficient to run quantum algorithms (e.g., Grover's algorithm). Furthermore, the use of AI and reinforcement learning could provide more computational power to manage, for example, the data generated by IoT devices. Nonetheless, it will still be necessary to develop new software that does the work of classical databases in the quantum world and to develop large machines with capacities of millions of qubits. On the other hand, quantum computers consume less energy than classical ones and, therefore, processing high data-intensive problems using quantum machine learning algorithms promises to see reduced energy costs.

#### Robotics

Robots use high graphics processing power (GPU) to solve computational tasks that are very data-intensive, such as vision, movement, optimal control, etc. and where quantum computing could help perform calculations at considerable speed. Quantum computing may improve the ability of robots to sense their environment and, by using cloud-based quantum computing, solve highly complex problems. In addition, the main kinematics issues associated with the mechanical movement of robots could be solved with quantum neural networks that recognize the moments of friction and inertia of the joints. Other typical issues of robot operation, such as identifying the reasons for the inconsistency between expected and observed behavior, could be solved using quantum algorithms. Quantum computing could also help reduce the complexity implicit in AI-based robotics by using quantum random walks to speed up response time and accuracy, rather than using information deduced from graph search.

#### Quantum cloud

Creating a safe and efficient environment for quantum computing in the cloud is an area that has great potential. A quantum cloud computer is a quantum computer that can be accessed over a network. Top tech companies like IBM (IBM Quantum), Google (GCP), Microsoft (Azure), and Amazon (Braket) have launched initiatives that combine quantum computers with cloud computing and that do not need to have a physical quantum computer installed. In this way, users have the opportunity to access quantum computers in the cloud to solve complex problems that require powerful computing (Soeparno & Perbangsa, 2021). The different quantum cloud computing services on offer today provide different architectures and performance levels. As competition continues to intensify among the big tech players, quantum cloud computing services will continue to offer specifications that promise ever better performance and faster runtimes.

#### Social networks

Social networks handle a huge volume of data every day as their use by millions of users continues to grow. Soon the amount of data in social networks will be so large that classic computing capabilities will no longer be able to process it easily and quickly in an acceptable time. Processing Social Big Data with relational databases where objects are semantically linked through multiple relationships is a major challenge. Mining such a relational database often requires enormous computing power in terms of hardware and software to deliver reasonably accurate and timely results. Therefore, to handle all this data and extract value from it, it will be necessary to have a large computing capacity that is also fast and efficient. Instead of the limitations presented by classical computing, quantum computing offers the ability to perform complex computation with social network data in an easy and efficient way, taking advantage, for example, of a graph theoretic representation of social network attributes to model sophisticated data structures and their interactions (Rao et al., 2015). Similar use cases include the modeling of different types of networks, such as telecommunications networks, traffic and transportation networks, tourist mobility networks, etc.

#### Quantum simulators

Although our capacity to predict complex systems has increased over time, state-of-the-art predictions still need new capabilities, especially in the field of social science applications. However, these developments have been restricted by the computational power that is currently available. Simulation models need to continuously calculate and recalculate visitor flow, optimal mobility routes, air traffic, prices and distribution, etc. Until now, simulations have used conventional computing tools and techniques, but with quantum computing it could be possible to solve these problems more easily and in less time in a controlled environment using small-scale "quantum simulators" of 50-100 qubits. Furthermore, quantum computing would allow for a higher degree of sophistication and levels of complexity in simulated systems, which could have a significant impact on simulation applications for science, and decision-making, including decisions related to tourism firms and destinations.

#### Quantum cryptography

Quantum cryptography is another application with great potential for the future of quantum computing. Quantum cryptography differs from traditional cryptographic systems in that the key element of its security model is based on the laws of quantum mechanics rather than classical mathematics. Since copying data encoded in a quantum state is not possible, the chances of being attacked by a cybercriminal are reduced. Furthermore, compared to traditional cryptography, quantum cryptography increases the probability of intrusion detection and improves performance. However, although with quantum computing firms could protect themselves better, it also adds the risk of being able to crack many of the conventional cryptographic systems used today, such as RSA, which uses the factorization of integers and is valid both for encrypting and for signing digitally. For example, by harnessing the power of quantum superposition with Shor's algorithm, it is possible to factor very large numbers in a matter of seconds and crack data encrypted in this way.

The rapid advance of quantum computing has also opened up the possibility of blockchain decryption using the Grover and Shor algorithms. These algorithms pose a threat to both public-key cryptography and the hash functions used by the blockchain, forcing the blockchain to be redesigned to resist quantum attacks, thus creating what are known as post-quantum or quantumproof cryptosystems (Fernandez-Carames & Fraga-Lamas, 2020). National organizations dedicated to cybersecurity, such as the US National Security Agency (NSA), have warned about the impact that quantum computing could have on IT products and recommends increasing the level of security through new approaches such as elliptic curve cryptography (ECC). On the other hand, since post-quantum schemes require high execution times, in addition to storage and computing resources that consume more energy, further research will be necessary to optimize cryptosystems that maximize computational and energy efficiency. Post-Quantum Bitcoin is an experimental example of a post-quantum digital signature scheme used with the main Bitcoin blockchain.

### Challenges

Although advances in quantum computing look promising and the tech industry is getting closer to "quantum supremacy" (solving a problem in a quantum computer that is intractable in a classical machine), there are numerous challenges ahead that will likely take years to resolve. One of the most important is how to build a large-scale, fault-tolerant universal quantum computer that can unleash the full potential of quantum computing in real-world applications. Key milestones have been achieved in this regard. For example, in late 2021, IBM introduced Eagle, its most powerful quantum system with a 127-qubit processor, and the first to break the 100-qubit barrier. The system contained new chip cooling and packaging technologies, including a new cryogenic platform to keep temperatures low and make the system more stable. These technologies will serve as the building blocks for IBM's next two quantum systems: the 433-qubit Osprey, scheduled for launch in 2022, and the 1121-qubit Condor, expected in 2023 (Scannell, 2021).

Developing a large-scale quantum computer has significant challenges, including the development of quantum hardware that reduces the effects of decoherence. Decoherence refers to the interactions that a qubit has with its environment and that can cause disturbances (or incoherent states) that collapse the superposition and lead to errors in the quantum information. For example, small variations in temperature or electric or magnetic fields can cause quantum information to degrade in the computer. Before any quantum computer can solve a complex problem, the industry will have to find a way to keep decoherence and other sources of error at acceptable levels; meanwhile the field of quantum error correction will remain one of the most active research areas in the field of quantum computing. Tests conducted with the NISQ (Noisy Intermediate-Scale Quantum) algorithm, specifically designed for quantum processors, seem promising to address these technical challenges.

Finally, it is noteworthy that quantum computing does not yet have its own high-level programming language. What this means is that the algorithms are processed by building quantum circuits to which available quantum gates or operations are systematically applied to find the desired solution. An example of industry efforts to address this issue is a visual programming tool provided by IBM for beginners to code and learn how to use a quantum computer.

## Connected and Autonomous Vehicles

Connected and autonomous vehicles (CAV) have the potential to disrupt transport-related industries, including tourism, by transforming urban spaces, modes of transport use, tourism employment, and the overall visitor economy. The arrival of CAVs on the market will generate a new world of business and social opportunities that, however, are not free from challenges and threats (Cohen & Hopkins, 2019). CAVs are much more than "autonomous taxis" and "constructive policy dialogue"; they raise concrete questions about how to design the cities in which we want to live and how tourist experiences will be designed in the future. At the epicenter of CAV innovation are urban environments, whose spatial morphology will have to gradually transform along with tourism activities to accommodate CAVs. CAVs also have the potential to shift current mobility practices, as well as impact the way public administrations raise revenue through vehicle taxes, the livelihoods of transport drivers, and, in general, the viability of transportation systems as we know them (Bissell, 2018).

CAV navigation will gradually relegate the driver to a "hands-off", "feet-off" role (with or without the ability to quickly regain control of the vehicle) to reach a fully automated mode in its most advanced stage. According to the most optimistic forecasts, CAVs could start to hit the mass market as early as 2025, first in parts of Asia, Europe, and the US, and later becoming the leading mode of road transport globally in the 2040s. This means that all transport-related industries will gradually transform, and the tourism sector is not going to be an exception. This potential for transformative change will create tremendous opportunities for new and existing players in the automotive industry and beyond. In fact, the world's leading vehicle manufacturers have been developing automated driving capabilities for years, and new entrants in the motor industry, like Google, Apple, and Uber, now compete to develop commercially viable advanced technologies for fully equipped automated vehicles. Still, CAVs need to overcome numerous challenges related to security, cost, and customer perceptions to achieve full implementation.

### Applications

Tourists will be among the first consumer groups to experience the CAV revolution. The role of tourists within urban mobility schemes is key to CAV innovation, which focuses on overcoming unsustainable practices and optimizing routes and flows of people according to environmental conditions. For example, CAVs have been tested as autonomous passenger shuttles to and from airports throughout Europe (e.g., Gatwick, Heathrow, Amsterdam, Brussels, Paris, Frankfurt, etc.), drastically reducing travel times and saving tons of carbon emissions (Cohen & Hopkins, 2019). New start-ups dedicated to the development of innovative mobility solutions are also emerging, such as CAVs specially designed for spaces that receive a large volume of visitors and workers, such as airports.

Many plans are underway around the world to continue expanding the use of CAVs in tourism environments, mainly as sustainable transport solutions that help overcome congestion and pollution in daily and daytime urban commutes. This ranges from airport shuttles and transfers, to taxis, car rentals, and vehicles used for guided city tours. CAVs are expected to provide "last mile solutions" that facilitate multimodality, such as moving urban tourists between transport stations (e.g., airport, train, bus, and maritime stations). By totally or partially removing the driver, the cost of transport could be significantly reduced, although at first it is likely that due to the novelty and the reduced supply and demand of the market, there will be an overprice in CAV mobility, as has happened in the electric vehicle market.

### Benefits

The benefits described below are those expected to anticipate the increase in consumer demand for CAVs, as well as to justify the public R&D funding programs that need to be carried out to boost these innovative technologies.

1.  First, there is the discourse of security as one of the main factors in favor of automated mobility. According to this argument, CAVs could eliminate up to 90% of driving accidents by reducing driver risks and driving errors. This is especially relevant in tourist contexts, in which due to ignorance of driving rules and the road environment, fatigue, and the playful nature of tourism transport, driving accidents with tourists occur.

2.  Second, CAVs will help reduce congestion because fewer accidents are expected, but also because fewer CAVs will be needed to meet mobility demands compared to human-driven cars (Kellerman, 2018). Nonetheless, this argument is debatable because it will largely depend on the property schemes that prevail in the market and on whether the CAV will replace the individual ownership model with one of shared ownership. In any case, it seems that due to the connected nature of these vehicles (vehicle-to-vehicle and vehicle-toinfrastructure), traffic flows could be optimized, leading to a reduction in mobility congestion.

3.  Third, CAVs can deliver environmental benefits, particularly in terms of fuel savings and reduced carbon emissions. This is mainly due to the electric traction of these vehicles and the elimination of unsustainable driving practices in favor of so-called "green driving", such as sudden braking or driving at high speeds.

4.  Fourth, CAVs promise to improve accessibility for non-drivers, whether they are elderly, low-income, or disabled, which will contribute to greater social equity in urban settings. While CAVs are likely to hit the market in the world's richest and most developed cities, in the long term and as their use becomes more popular, CAVs are expected to become a solution that favors the integration of mobility of the most disadvantaged groups.

5.  Finally, due to the non-polluting nature and low environmental impact of CAVs, they can be used in urban spaces where vehicles driven by people have already been prohibited due to their high impact. Likewise, the elimination of obstacles to driving and the transformation of the cabins, in which passengers will be able to read, eat, or access audiovisual content, will improve the experience of the tourist, who will be able to use CAVs as an innovative tool to create new tourism experiences.

Achieving some or all of these benefits will depend not only on the degree of intelligence and automation achieved by CAV technologies, but also on fundamental questions related to the governance of the new mobility framework, such as vehicle ownership models (i.e., shared versus private); the ratio of CAVs versus non-CAVs on the roads; the technical specifications of performance, autonomy, and consumption; and the public regulations that will govern the use of CAV (Cohen & Hopkins, 2019).

### Challenges

CAVs will transform tourism in the coming years and will contribute to reconfiguring the urban space, creating new challenges that will put the automobile industry, consumers, and those responsible for urban planning to the test. It is possible that by improving the travel experience and reducing travel costs, there will be an increase in the induced demand for mobility by residents and tourists. Higher levels of CAV use by urban tourists could negatively affect efforts made to encourage responsible use of public transport by visitors, potentially leading to "overtourism" in the form of hordes of small CAVs congesting urban tourist spaces. In a scenario like this, there would foreseeably be a shortage of urban land available for parking, which would call into question the planning of city centers. Better travel conditions could make people want to travel longer distances for work, entertainment, or for business or leisure trips, which could encourage people to move their places of residence to more distant places, taking advantage of lower property costs. This could lead to urban sprawl and further increase car dependency, with tourists perhaps turning to private vehicles and public or shared transport declining.

New urban tourism destinations could emerge as CAVs grow in popularity, either as new attractions that were previously difficult to access, or secondary cities now emerging as new destinations due to more affordable transport connectivity. The new mobility facilitated by the CAV could redefine what is the "commercial district" or the "center" of cities, by connecting urban spaces in ways never seen before. In short, CAVs could affect the flows and experiences of urban and interurban mobility. It has been argued that the location of the hotels would be less important among the selection criteria of tourists since it would no longer be so important that the hotels need to be connected by public transport (Bainbridge, 2018). The same would happen with other types of tourist facilities, such as tourist accommodation, bars, or restaurants, which in many cases could be easily reached through CAVs. It could also happen that travelers decide to spend the night in their CAV while it drives them to their final destination, instead of spending the night in a hotel. This idea of CAVs as "hotels on the move" would affect the behavioral patterns of travelers, and hotels and tourist accommodation.

The arrival of CAVs on the market is likely to threaten many tourism-related jobs in the future, notably those of professional drivers such as taxi and bus drivers, and those travel businesses that rely on human drivers, although it is likely that the replacement of professional human drivers would be gradual and in stages. There are also many questions about which business models will prevail in the CAV market. With the shared (on-demand) CAV model, up to ten privately owned vehicles could be replaced by each shared CAV, and trips would surely be more affordable and attractive to tourists. However, CAV users would be forced to spend time with strangers in the confined space of the cabin, which in some cultural contexts may be considered unacceptable due to the expectation of having to interact. On the other hand, the environmental benefits of CAVs will depend on the shared/private ownership models and the type of propulsion with which these vehicles are equipped. Although CAVs for urban use are most likely to be electric vehicles, it should not be forgotten that some electric vehicles have higher overall emissions than combustion engine vehicles, and that the true emissions reduction of electric vehicles depends on the production processes and fuels for electrification.

Finally, certain ethical, security, and privacy concerns have also been identified in the development and use of CAVs. Ethical questions arise, for example, when discussing the degree of protection that passengers traveling in a CAV should have and whether CAVs should be programmed to protect passengers above all else, even when the safety of those outside may be threatened. The recent death of some pedestrians due to accidents caused by CAVs in the USA has drawn the attention of the media and opened a public debate about the limits of the automation of these vehicles. Not to mention the possible malicious use that terrorists or people with murderous intentions could make of CAVs, which could be directed against the crowds in busy urban areas. Finally, there is also the issue of the privacy of the personal data recorded during the trips made in the CAVs, as well as the data related to the places visited, the routes taken, the travel times, the stops made, etc., which that could be used to direct advertising or marketing actions to the occupants.

## Discussion Questions

-   Is it a realistic scenario to think that machines will replace human beings in most of the tasks that involve human reasoning? Should we humans be worried?

-   What are the main ethical problems that currently affect the tourism firm in relation to smart technologies?

-   Can ethics contribute to increasing the firm's performance? How?

-   What main advantages (disadvantages) would adopting the "as-a-Service" model have for the tourism firm?

-   What potential practical benefits could quantum computing bring to the tourism firm? What factors will its adoption depend on?

-   What are the main impacts that the implementation of the CAV could have on tourism firms?

-   In what ways could CAVs affect the quality of the experience perceived by tourists?
