---
title: "Who Should Read This Book"
---

This book aims to serve as a reference and support book for owners and managers of tourism SMEs in the development and implementation of their strategies for smart transformation and organizational change, regardless of the size, geographic location, and sector in which they operate. Likewise, the book is aimed at graduate students in any of the branches of business management, change management, and digital transformation with a specialty in tourism, as well as graduate studies in tourism, hospitality, travel, and leisure management. The book may be useful to advanced undergraduate students who are approaching digital and smart technologies for the first time and who are willing to specialize in the latest trends of tourism and learn how to manage them. The materials in the book may also be suitable as part of the curriculum for courses in strategic business management, Big Data and analytics, digital transformation, and ICT management in the degrees of tourism, hospitality, travel, and leisure management.

Although this is a book in which smart technologies are prominent protagonists of the story, it has been written trying to make the language of technology and business management accessible to those who are not specialists in any of these fields. It must be said that this is not a book written for specialists in ICT management or systems engineers, nor is it meant for those who want to delve into the operation of specific technologies or become experts in their functionalities. There are very well-written works available out there that cover these subjects and to which the interested reader should turn. However, technology plays an instrumental role in the book insofar as it has an impact on organizational transformation and value creation in tourism firms. Therefore, a holistic and interdisciplinary perspective focused on management prevails in the book, rather than one specialized in technology.

## For Owners and Managers

The book is perfect for those owners and managers who are approaching the fundamentals of the Smart Revolution for the first time and want to acquire a comprehensive and holistic view of the consequences on the tourism firm from the perspective of organizational transformation and strategic management. In this case the book provides the reader an understanding of the key concepts that are shaping the Smart Revolution in tourism firms, as well as the factors that affect the creation and destruction of value in organizations and how to manage them.

For those owners and managers with a track record of managing technology disruption, change initiatives, or who have already embarked on digital/smart transformation processes, the book provides valuable guidance to further explore the management framework that is applicable to the tourism firm to succeed in implementing the smart transformation and unlock its benefits.

Although each chapter has been written to be read and understood on its own, it is highly recommended that beginning and experienced owners and managers alike first read the book from cover to cover before deciding to skip to specific chapters. This will allow them to get a more detailed insight into the key concepts, the relationships between them, and the consequences that arise for the management of the smart transformation in the tourism firm. Experienced owners and managers will thus be able to update their understanding of the main building blocks that shape modern smart transformation and the new management practices that have emerged to harness them. However, if owners and managers feel that they have enough knowledge and experience or are already familiar with the key ideas in this book, they are free to skip directly to the parts or chapters of the book that are of most help or interest to them.

## For Instructors

Instructors can use this book as a reference book in an introductory graduate, undergraduate, or professional course on digital/smart transformation, Big Data and analytics management, organizational change management, or IT management in tourism studies, hospitality, travel, and leisure. The book contains a sequence of parts and chapters with increasing complexity and depth that can be used as stand-alone or connected topics for specialized course sessions, whether they last a few weeks or a full semester. In some cases, instructors may prefer to use the book as supplemental material to a course for prospective tourism business owners, entrepreneurs, or managers, to encourage engaging class discussions, broaden the knowledge of more advanced students, and help students focus on their final coursework.

## For Students

Graduate and undergraduate students who are approaching smart technologies, smart transformation, organizational change, tourism trends, or any of the branches related to ICT management for the first time, will find in this book a valuable reference work that will accompany them both in their last years of studies and during the first steps in their professional career. The book offers them a broad and complex overview of the fundamental concepts that govern the Smart Revolution in tourism firms, as well as the key issues and applicable management practices that tourism firms can implement from a manager's perspective. Those students who are more proactive or interested in these subjects will find numerous references, case studies, and discussion questions in the book that will guide them to continue deepening their knowledge and broaden their vision of the sector in which they wish to work or, eventually, specialize.
