project:
  type: book

book:
  title: "Managing the Smart Revolution in Tourism Firms"
  author: "Francisco J Navarro-Meneses"
  date: "29/3/2023"
  chapters:
    - index.qmd
    - call_to_action.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  freeze: auto
  

