---
title: "Organizational Agility"
---

In the uncharted waters of smartization and the uncertainty of the tourism business environment, owners and managers struggle to determine the most appropriate strategies and how to implement them to sustain the firm's competitive edge in the long term. In light of this challenging prospect, what seems clear is that every tourism firm is going to need a new work structure to transform into a smart organization, i.e., become an organization capable of delivering products and services faster according to customer preferences and needs using (internal and external) intelligence. Such a restructuring will undoubtedly have an impact on the strategy, structures, and operational processes of the firm. Ultimately, a new organizational logic is going to be required, which reorganizes the resources and adapts the way of thinking and working of the firm to the world of digitalization and smartness.

In this chapter the concept of organizational agility is introduced as a main transformation management framework that can provide tourism firms the opportunity to embrace a more flexible operational style and respond more rapidly and proactively to the competitive risks and challenges posed by today's turbulent business and economic environment.

## What Is Organizational Agility?

Agile organizations can intentionally increase their flexibility and speed for efficient delivery of customer-centric products in an ever-changing environment. This means that agile organizations are able to swiftly react to predictable and unpredictable changes in their environment and take advantage of them through: 1) a strategic orientation towards sensing and response; 2) a functional alignment of knowledge and resources; and 3) agile operational teams that enable members to work effectively and efficiently (Akkaya & Tabak, 2020; Cepeda & Arias-Pérez, 2019; Greineder et al., 2020; Unhelkar, 2017). In other words, agility is a key driver for organizations to gain competitive edge in turbulent and highly uncertain market conditions by pursuing the following four core capabilities:

1.  A strategic orientation that revolves around the ability to sense and respond.

2.  The ability to deliver value to the customer or the end user by incorporating their tastes and desires in the development of products and services (customer agility).

3.  The ability to deploy agile processes and methods for the rapid development and delivery of customer-centered products and services, as well as its continuous improvement through innovation and learning.

4.  The ability to bridge the gap between strategy and operations by integrating sensing and responding capabilities with the delivery of customer-centric products and services.

In summary, agility is about the tourism firm being able to comprehend the dynamics of customers' preferences and expectations and improve its performance by developing tailored products that customers value, thus gaining competitive advantage (Attar & Abdul-Kareem, 2020; Burchardt & Maisch, 2019). Agile has been used very often as an umbrella term that ambiguously brings together different methodologies for developing products that meet customer requirements, each with its own process, terminology, and scope. To avoid ambiguity, in this chapter we will use the term Agile as a framework of values and principles contained in the Agile Manifesto, the Agile set of practices, and the Agile methodologies. The Agile framework (Fig. 18.1) thus systematizes the practical application of agility in an organizational context and provides guidelines to successfully tackle smart transformation.

The Agile framework has gained popularity in recent times as a management approach that can help create competitive advantages for firms, as well as drive improvements in customer satisfaction, and operational efficiency and effectiveness. Business firms are beginning to realize that organizational agility can be vital in delivering quality products and services to customers and to differentiating themselves in unique ways in an increasingly complex and uncertain hypercompetitive environment. In this vein, the impact of organizational agility on main business performance indicators, such as customer and employee satisfaction, market share, business success, or competitiveness has been documented by some surveys (Attar & Abdul-Kareem, 2020; Burchardt & Maisch, 2019). A study conducted by Capgemini Consulting (2017) on the agile organization shows that 83% of survey participants had plans for further transformation towards agile practices, with only 17% not seeing the need to move towards an agile environment in their organization. Moreover, 94% of the C-level executives interviewed by Accenture said that their current operating model puts the growth and performance of their organization at risk (Accenture, 2020), hence the need for organizations to move towards agility.

## Strategic, Functional, and Operational Agility

As an owner or manager maybe you are aware that organizational agility started with software development companies looking for ways to create software development processes that would allow them to deliver solutions quickly and tailored more accurately to their customers' needs. In its origins, agility consisted of a manifesto of 12 statements or principles (Beck et al., 2001) that enunciated the characteristics of Agile projects and guided development teams through efficient software development. Over time, these principles have been adapted to a growing number of firms outside the software industry and refined to become an operational framework for organizational transformation around three fundamental dimensions: strategic, functional, and operational (Greineder et al., 2020).

### Strategic agility

Strategic agility is the organization's ability to drive faster, more accurate, and less costly business processes, as well as enable the exploration and exploitation of innovation and opportunities. Hence, strategic agility encompasses the critical organizational capabilities needed to sense and respond to changes in the organization's environment that can affect business strategies.

Organizations sense insofar as they can monitor what is happening around their internal and external environment. Sensing involves knowing where to look, what to look at, and what to do with what you are looking at, thereby extracting what is relevant to support action-oriented decision-making. This sensing capacity continually generates knowledge flows that the organization needs to manage in some way. Developing these management skills implies that organizations have a knowledge acquisition and management system that allows them to interact with the actors in their business environment (i.e., customers, users, partners, suppliers, competitors) to acquire knowledge, and to exchange and exploit it. With the knowledge thus acquired, agile organizations are in a position to respond, which means that they can adopt a decision making process in which the knowledge acquired is first evaluated and then opportunities or threats to the organization are identified. Ultimately, agile organizations have the ability to bridge the gap between sensing and acting through people and teams who are empowered and have the autonomy to do so.

### Functional agility

Functional agility seeks to align strategic agility with operations through two interrelated capabilities: 1) the alignment and dissemination of knowledge generated; and 2) the flexible and fluid allocation of resources to allow the joint optimization of the organization's strategic and operational tasks. Knowledge alignment is the result of sharing knowledge and understanding between people and business units. Organizations that align knowledge can leverage the tacit and explicit knowledge of employees to create new business opportunities as the environment changes. The flexible and fluid allocation of resources is the ability of the firm to adjust its processes and deploy resources on time, where and how they are needed in response to environmental changes. The greater the knowledge alignment, the more positive impact there will be on the organization's sense and response capabilities. Likewise, the better the flow of resources, the greater the impact on the speed of delivery of customer-centric products and services.

It is recommended that all stakeholders develop such capabilities to ensure that the transformation strategy is as consistent as possible. However, for these capabilities to develop properly across the organization, IT needs to be embedded into the organization's core business processes. IT is a critical enabler for business processes to gather timely and accurate information for proper decision-making and monitor the behavior of customers and users (Cepeda & Arias-Pérez, 2019; Rialti et al., 2018). It is simply not possible to separate an agile organization from strong integrated information systems that streamline and automate business processes. By emphasizing the development of information technology capabilities, the agile firm can strengthen its internal and external networks, reducing costs. These capabilities allow information and knowledge flows between stakeholders to be more dynamic and spread among a greater number of people, enabling the firm to offer innovative solutions more quickly as the context changes. In the end, IT is a great ally for the agile firm to learn, stay connected, and innovate.

### Operational agility

Operational agility addresses the optimal use of operational and product delivery systems in accordance with changing environmental conditions. This usually involves reconfiguring the mix of resources of the firm, adapting business processes, and/or redesigning the organizational structure so that the customer can swiftly receive added value. Typically, the agile organization will need to set up a new work environment and implement new work systems that affect factors such as the structural characteristics of the organization, IT, customer interaction, knowledge, employee autonomy, etc.

One of the core transformational practices that agile organizations introduce is the decentralization of decision-making, which means that team members must be able to create their own insights and make their own decisions based on the best information available. Decentralization also means that organizations must provide the staff making decisions with the knowledge and skills necessary to understand the objectives pursued by the processes they lead (Unhelkar, 2017). This requires a clear determination on the part of firm leaders to work on continually improving workforce capabilities, especially when it comes to embedding data and intelligence into business processes. For example, the complexity inherent in managing Big Data requires firms to empower their people with new skills and analytical expertise, as well as tools and techniques to drive the decision-making process. Again, IT plays a central role in leveraging decentralized decision-making processes. Customer agility is another key agile capability, especially at the product development and delivery level. Customer agility relies on agile development methods that bypass plan-driven development processes and rapidly integrate product components as desired by the customer, allowing the organization to control, change, and improve production and delivery processes in real time. Figure 18.2 shows the dimensions and capabilities involved in organizational agility, as well as the effects they may have on the firm's adaptability, speed, and flexibility goals.

Tourism firms willing to move forward as agile organizations will need to strike a balance between each of the components of the organizational agility framework. Unfortunately, not much information is available on how firms can successfully transform into agile organizations and how agile practices can be mastered. Nor do scholars and professionals agree on the conditions under which it is good for firms to implement Agile practices. Therefore, it is strongly recommended that owners and managers first fully understand the smart transformation process globally before they determine what types of job tasks and processes can best be replaced by Agile practices to improve business performance.

## Practices and Methodologies

The principles of the Agile Manifesto lay the foundation for Agile values; nonetheless they are only statements that do not provide owners and managers with any concrete plan or process to guide the smart transformation process. This issue becomes more apparent when organizations embrace agility without properly understanding what the concept is or how they can measure or regulate it. Therefore, it is key that organizations learn as much as they can about how and why they should become agile (Attar & Abdul-Kareem, 2020).

Organizational agility entails proactive management practices that pursue continuous improvement; elimination of downtime and inefficiencies caused by organizational silos, overlaps, redundancies, and unnecessary routine tasks; efficient use of resources; flat organizational structures that avoid bureaucratic bottlenecks; and effective supply chain management. By consistently working on pursuing these objectives, the agile organization shall be better prepared to develop products and services adapted to demand and move swiftly to cope with changes in the environment. But what are the practices that the firm must implement to become agile?

In the absence of a commonly accepted framework that sets the ground for an Agile transition and moving beyond the 12 principles stated in the Agile Manifesto, Rialti et al. (2018) highlight a list of the 7 most relevant principles by which an organization can provide an agile response to a changing environment while exploring and exploiting opportunities.

1.  Customer satisfaction.

2.  Response to market changes.

3.  Organizational flexibility.

4.  Technical flexibility.

5.  Dynamic business process management.

6.  Effective strategic collaboration with partners.

7.  Stakeholder accountability.

Organizational agility involves, according to Akkaya and Tabak (2020), the development of four fundamental skills by the organization:

-   **Responsiveness:** It is the ability of organizations to grasp the changes that are taking place in the market (i.e., changes in customer tastes and preferences, new digital technologies, etc.) and provide effective and efficient responses quickly and targeted where they are needed. As far as tourism firms can respond effectively to changes in their environment they may be able to gain competitive edge.
-   **Flexibility:** It is the ability to respond to changes by offering an optimal combination of internal and external resources available to the firm. To meet changing customer needs, agile organizations are constantly reorganizing their resources (e.g., employees, equipment, facilities, technologies), accommodating new resources and skills, and adapting their product and service delivery to a variable scope.
-   **Speed:** It is about organizations making timely decisions when they are needed, and activating the organization's processes smoothly and accurately to deliver some expected results. In short, speed is about delivering products and services where, when, and how customers demand them. Speed and responsiveness are closely related, as it will be useless for firms to respond to changes in the environment when it is not necessary or after the window of opportunity has passed.
-   **Competence:** It is the ability to decide when and how to use the other three organizational agility skills (responsiveness, flexibility, and speed), either individually or in combination. Competence is also a process that requires the organization to be aware of all the internal and external competences within its reach, updating them over time, as well as identifying those that are missing and that it would be good to have.

Furthermore, according to Joiner (2019), operational agility is achieved when the organization establishes these three structural and cultural capabilities:

1.  Agile management methods in each of the functions of the organization so that work is carried out in short and fast iterative cycles to which feedback from stakeholders is added.

2.  Fast and flexible IT systems that improve the organization's speed and responsiveness to changes in the environment.

3.  Tear down silos, foster cross-unit/departmental collaboration, and strengthen relationships with external stakeholders.

### Agile methodologies

The values and principles of the Agile Manifesto and some successful Agile practices have been systematically packaged in the so-called Agile methodologies. Specific methodologies used for organizational agility include Scrum (for incremental team product development processes); Kanban (for managing workflows that improve organizational bottlenecks and balance demands with available capacity); Extreme Programming (for teams to improve delivery quality and responsiveness to new customer requirements); Test-Driven Development (to convert product requirements into test cases and embed continuous testing in work cycles); Feature-Driven Development (to break down customer requirements into tasks for on-time delivery of products); and Lean Manufacturing (to reduce production costs by eliminating wasteful processes, getting the right things done in the right place, at the right time, in the right quantity) (Leybourn, 2013). Some of these methods, such as Scrum and Extreme Programming, have become very popular across industries and are considered standard Agile methodologies. They typically include practices such as working in short time cycles (typically a few weeks), continuous product delivery through incremental improvements, and small teams of experts physically working together.

Among the Agile methodologies best known to data-intensive firms are Scrum, Extreme Scoping, and Agile Data Warehousing (Larson & Chang, 2016). Extreme Scoping specifically focuses on data integration within the organization's data and analytics projects. Data integration encompasses data-centric management activities whose goal is the acquisition and subsequent incorporation of data into data warehouses. Some related practices include acquiring and understanding data sources, cleaning data, organizing and modeling data, and preparing data for loading into a data warehouse.

Agile data warehousing is a collection of methodologies and philosophies that systematically encompass end-to-end activities for agile data warehouse delivery. These methodologies stem from the need to avoid the pitfalls that often lead to failed data warehousing projects that cost millions of dollars and take years to implement. These methodologies share a vision of the architecture, the quality of the data, the type of modeling and prototyping of the data throughout a project, the organization of the work by requirements, the documentation, and the participation of the stakeholders.

Scrum is the most popular Agile methodology in software development and business intelligence projects. Some key Scrum concepts that are used in data-driven projects include user stories (informal explanations of the features that a product must have from the perspective of a customer or end user); sprints (small projects that are executed in very short cycles to achieve product improvements that deliver value to the customer or user in a very short time); backlogs (lists of product requirements and/or sprint specifications to be developed from user stories); and Daily Scrum (daily meeting of about 15 minutes to synchronize team tasks and review progress). With Scrum the requirements of a data-driven project are broken down into smaller stories that are then developed, tested, and delivered to the customer or end user with input from stakeholders.

In addition to these market methodologies, some authors have suggested mixed frameworks based on Agile principles, such as in Unhelkar (2017) and the Composite Agile Method and Strategy (CAMS). This approach is aimed at firms that do not operate in the software industry but are interested in improving their capabilities to make fast and effective decisions using Big Data and analytics as support tools. CAMS seeks to balance agile flexibility with planning formality, i.e., an IT governance framework that is complemented by the flexible and collaborative principles of Agile. The same philosophy can be applied to all functions of the organization such as sales, human resources, project management, innovation, etc.

## Knowledge, Teams and Leadership

Organizational agility is closely associated with the organizational structure of the firm. The organizational structure includes the system of functional and hierarchical relationships contained in the organization chart of the firm, the resources, and the work and leadership styles necessary for human capital and talent to work in the desired direction. The organizational structure of an agile firm is characterized by its flexibility, operational decentralization, and a flatter hierarchy that fosters autonomy in decision-making, interdepartmental communication, and cooperation between teams and individuals (Attar & Abdul-Kareem, 2020). Agile organizations take a more open approach and build stronger connections with key internal and external stakeholders (i.e., they create work teams and alliances). In this way, the agile organization can continuously detect changes in the environment and provide responses. Not surprisingly, interpersonal and communication skills, flexible leadership, entrepreneurial mindset, and self-motivation and learning prevail in the agile organization.

Agile organizations create work teams that are able to swiftly provide solutions to the changes sensed in their environment. Agile teams are self-organizing groups of people who come together because of their shared interest in a project or because they think that a specific team is where they can contribute the most. In organizations with established agile practices, employees freely decide which teams they want to be a part of and how they can contribute most effectively, which in turn can result in higher employee satisfaction as they are more involved in decision-making and build mutual trust and respect (Rigby et al., 2016). Team creation/termination is flexible and depends on the environmental conditions around the firm. The same employee can be a leader in one project, a facilitator in another, and an expert technician in another (Setili, 2015). Agile team members are diverse in terms of age, gender, or training to better respond to the complexity of the environment in which they operate. Furthermore, recent research has found that the smaller and more informal the work environment, the higher the performance.

Agile teams execute projects with a limited scope in short iterations and test them before embarking on large transformation projects that involve higher costs and risks. Therefore, they are often engaged in short-term, fast decision-making processes (Berntsson Svensson et al., 2019). This is especially important when firms struggle to cope with the unpredictable changes in the business environment and when developing innovation. Since firms are very unlikely to anticipate what customers will demand or whether customers will like a new product or service that they have never seen or experienced before, the best thing to do is to experiment again and again. Testing new things quickly to find out with customers and users how they are going to use the innovations provided and whether the products and services are going to be valuable to them is key to the agile organization.

The way agile organizations manage work teams does not mean that they do not have well-defined leadership. What happens is that instead of associating leadership with certain people by their hierarchical position in the organization, leadership is a role that anyone can assume depending on the tasks involved. This emphasizes the autonomous and self-organized nature of the agile organizational structure where collaboration and cooperation are part of the firm's internal work processes (Burchardt & Maisch, 2019). Indeed, leadership style is a critical factor when navigating the transition to the smart organization. Transformational leaders create a vision that the organization must move toward, share that vision with people, encourage them to learn and innovate collaboratively, and make decisions that transform the organization in an ever-changing environment (Akkaya & Tabak, 2020). Therefore, a major challenge for any agile organization is to adapt the leadership style of owners and managers to the changing business environment, so that they can steer the organization in the most effective strategic direction at any time. In the end, agile leadership is about being able to deal with the changing and uncertain nature of today's business environment and foster flexible strategies that take broad perspectives into account (Attar & Abdul-Kareem, 2020).

A final key variable in the transition to organizational agility is knowledge management. Firms must equip themselves with the capacity to manage their knowledge and create the learning mechanisms necessary to exploit it. Without these capabilities, further implementation of knowledge management practices will not make sense. Knowledge management also has a great influence on leadership style, as business leaders increasingly need more and better knowledge to assess and understand their environment. Knowledge is also key for leaders to assess the competencies that firms lack and that are required to implement product delivery strategies that meet customer needs.

However, agile organizations not only make a living from efficient knowledge management and learning capabilities, but also develop decision-making processes that are flexible and seamlessly connected to the firm's knowledge base. In the end, becoming an agile organization is not easy, and neither is staying agile. Instead, it is a never-ending journey for which people must be prepared to proactively deal with the ambiguity and uncertainty of the environment around them. Engaging stakeholders in a joint effort and having a well-designed plan that can be implemented are key to successfully accomplish this process.

## Customer Agility

An essential component of organizational agility is the ability to sense and respond to changing customer needs to improve business performance. This is known as customer agility and requires that sensing provides enough accurate and timely information to the organization so that it can respond effectively to changing customer demands. Ultimately, customer agility is about achieving a higher level of customer satisfaction, thus laying the foundations for customers to buy a tourism product or service again (Fig. 18.3). Given that the factors that determine customer satisfaction and loyalty in tourism are highly variable and depend on the context, tourism firms must be equipped with the ability to constantly detect customer preferences and respond to them quickly and flexibly as they change. That said, there are a number of steps tourism firms can take to develop customer agility, the first of which is to align business strategy with customer strategy (Ngo & Vu, 2020). Firms must encourage employees to share the common goal of detecting changes in customer demands and responding effectively to them. This will typically require the commitment of the firm's top management, as well as the involvement of the human resources department. With the active engagement of both, the firm will be able to develop a customer-centric culture, build cross-functional customer service teams, and equip employees with the skills to spot customer changes and know what to do to respond to them.

Another key step for customer agility, very often overlooked by business owners and managers, is knowledge management. Generating knowledge and making the firm learn from it (i.e., developing an organizational culture and processes focused on continuous learning of all members of the organization), is a proper way to ensure that the smart firm knows how to proactively reconfigure its value offering. Knowledge is also a lever to unfold the firm's innovation capabilities, which are essential for building an organization that learns and gains competitive edge. More specifically, deep and accurate knowledge about the customer and the market is key for the firm to identify their needs and be able to respond to changes in their preferences. However, building customer insight is not a painless exercise. It simply cannot be reduced to creating a database to which only a few have access due to their hierarchical position in the firm and making some eye-catching reports. The dissemination of knowledge at all levels of the organization is a critical condition for achieving an organizational culture focused on learning. It is also the mechanism that allows knowledge to truly become a game changer that the customer can benefit from and ultimately improve business performance.

Finally, customer agility is about equipping the organization with enough technological capabilities to collect, store, organize, and analyze the vast amount of information that firms need about the customer. Tourism firms have been among the pioneers in generating customer information in large quantities and through multiple channels, both online and offline. Smart technologies play a crucial role in tourism firms when it comes to analyzing and exploiting that information and leveraging customer insights to inform the firm's decision-making process. Ultimately, technologies are key enablers for the firm to interpret changing customer demands and disseminate that knowledge to users in the organization responsible for making decisions. From the customer's perspective, technologies allow them to play a more proactive role in the design and configuration of the firm's value offering, either because they participate in product co-creation communities, or because they use any of the two-way communication channels available to them to create feedback loops between the firm and the customer. This more active participation of users and customers in value co-creation processes not only allows the tourism firm to be more responsive to changes in customers' demands, but also creates emotional and cognitive bonds with them that can have a positive impact on their evaluation of the quality of the products and services delivered by the firm.

When it comes to achieving greater customer agility, it should be noted that investments in technology are not as important as other factors. Owners and managers must keep in mind that technology does not play the central role in smart transformation, but rather technologies must be focused on providing timely support to gather information from customers, disseminate it, and manage the knowledge so generated across all levels of the organization to inform good decisions. In fact, tourism firms do not need large investments in state-of-the-art or highly sophisticated technologies to start providing customer agility. The three key customer data sourcing technologies (email, website, and database management technologies) can suffice if used effectively.

In the specific case of tourism SMEs, since their business model normally depends more on proximity to customers and on building personal relationships with them, they may be especially apt to detect changes in customer preferences. However, SMEs often lack the skills and resources to implement customer agility in the organization. Therefore, owners and managers must be aware of the limitations of their organization and implement strategies that allow them to continually make small organizational changes, one after another, to improve core business processes. Affordable and scalable new technologies, such as social media applications for customer service, can be of great help in this process.

## Discussion Questions

-   How are tourism firms doing in relation to organizational agility practices? What kind of practices and/or methodologies are firms implementing to achieve organizational agility?

-   What barriers or impediments prevent the development of Agile practices in tourism firms? What can be done to overcome them?

-   Are the owners and managers of tourism firms prepared to lead the transformation of their organizations following Agile principles?

-   How should the transition from a conventional organizational model to another based on Agile principles be approached from the perspective of business management? And from the operational and technological perspectives?

-   What potential downsides and risks can the implementation of organizational agility entail for the tourism firm? How can these drawbacks be minimized?

-   What are the technological implications of organizational agility for the tourism firm? How can they be anticipated and managed?How does the decentralization of decision-making affect tourism firms? In what cases is it positive (or negative) for the organization?
