---
title: "Towards the Data-Driven Organization"
---

Tourism is an extraordinarily information-rich industry. The shift in focus to the tourism "experience", coupled with the highly competitive environment, pushes tourism firms to focus more on information and data. The collection, storage, organization, processing, and dissemination of information thus become crucial parts of the performance of tourism firms. In this context, the success of tourism firms depends on the creation of new knowledge from the data and information that is available and, more specifically, on the rapid and timely integration of relevant knowledge for decision-making (Kaivo-Oja et al., 2015; Nikolskaya et al., 2021).

The use of data by firms is nothing new. It has always been at the root of successful business management. What has changed today is that data, which used to be expensive and scarce, is now everywhere (users and consumers generate data all the time), has new properties (since it is meta-tagged), it is produced in real time, and it comes from many different sources and in many varied formats (e.g., texts, images, videos, audios). Its size and relevance for business and society has reached such relevance that many call this moment the "data revolution" or the "Big Data Era", and include the set of innovative technologies and techniques focused on collecting, storing, managing, and analyzing large data sets that could not otherwise be dealt with by conventional data management methods (Bashkirova, 2016).

Industries around the world collect all sorts of data and information from customers, suppliers, partners, and even from competitors. There is also a growing need at the organizational level for new capacities to tackle the growing complexity of the tourism ecosystem and the needs arising from digitalization. Today, firms' digital touch points with customers are many and varied, allowing the entire customer life cycle (before, during, and after the purchase) to be recorded for later analysis. Distributed sensors can also record what is happening in a physical environment, transmitting information wirelessly or over a fixed broadband network wherever there is the ability to use it. Additionally, renewed interest in artificial intelligence and machine learning tools is accelerating business transformation due to their promise of stronger analytics capabilities and systems that are more powerful and can operate in a more automated way (Berntsson Svensson & Taghavianfar, 2020).

The result is a tremendously complex landscape with an exponential amount of data flowing through hundreds or even thousands of applications, which in turn is leading to an accelerated growth in the capabilities of the firms to do something with it, such as storing, processing, and presenting it (Andersen et al., 2018). For organizations this massive flow of data is proving very difficult to manage and extracting real value from it has become a daunting challenge, even more so for organizations with decades of history in IT management that have never managed data as an asset.

In this regard, the successful transformation to a data-driven organization involves the widespread application of the latest technologies in data storage, processing, and knowledge creation/ integration. Furthermore, any information related process in a modern organization relies on dozens or more applications that typically have their own internal data model, their own interfaces, and even require their own expertise. This very often far exceeds the capabilities of what any individual in an organization can comprehend. For this reason, many organizations have appointed chief data officers (CDOs), in charge of managing the data in the organization, and data scientists, who receive, examine, and analyze data of all kinds in search of value for the business.

Far from diminishing, the sheer volume of data will continue to grow in the coming years, regardless of the size and type of organization. Data calls for more data, thus forming an upward spiral in which data is constantly increasing and less understood (Chessell et al., 2018). Converting all this data, the vast majority of which is unstructured, into structured knowledge will be one of the main challenges for the aspiring smart firm. In addition, firms that want to gain market share should become familiar with knowledge management methods and systems (Bashkirova, 2016) that can help improve firm performance. Indeed, some authors have reported that there is a correlation between business performance and the organization's use of data analytics and knowledge, whether for efficiency, growth, or competitive differentiation. High-performing organizations are using data to make decisions more than twice as often as low-performing organizations, and for a wide variety of decisions, big and small (LaValle et al., 2011).

However, tourism SMEs still do not use data much to create value and there is still a long way to go in this regard (Del Vecchio et al., 2018). Nowadays, tourism firms seem more concerned with implementing digital technologies and infrastructures focused on their daily operations (e.g., reservation systems, websites, information management systems), despite the relevance that data is acquiring to improve the competitiveness of any tourism business. The penetration of these technologies is also very different within and between the different tourism subsectors, as well as their impact on the growth of tourism firms. This makes data a central issue that tourism firms need to start acting upon to continue creating value for stakeholders. Business owners and managers have no more time to lose and should start planning for the transition to a data-driven organization.

## The Value of Data

The transformation of traditional tourism firms into data-driven organizations mainly affects the organizational processes of the organization, the allocation of internal and external resources, and even the long-standing customs and culture of the people. Ultimately, these transformational changes aim to make the business more agile and responsive to customer demands, that is, more customer-oriented in every way.

Smart technologies can provide a major boost to the transformational effort of tourism firms if supported by proven standards embedded in technology platforms and everyday data-driven tools (e.g., tools and platforms that automate data storage, classification, and analysis). Furthermore, new technologies, such as artificial intelligence, real-time customer intelligence, analytics for prediction and personalization of services, to name a few, are already key to creating value and driving major changes throughout the tourism ecosystem.

But what exactly is "data" and why is it so valuable? Data is a collection of observations, measurements, facts, or even raw representations of phenomena that are not organized in any particular way and do not contain any apparent meaning. Data is the basic unit used to register events, activities, operations, or transactions. Data differs from typical organizational resources as it enables replicable services at almost zero marginal cost. It also provides great flexibility of use regardless of the device it runs on (Veit et al., 2014). However, data alone is useless unless it can be interpreted and made meaningful, and to make this possible, organizations must integrate data with analytics technologies. Data analysis thus activates a process of transforming the value of the data by which data pass through three different value states: "raw data", "information", and "knowledge" (Fig. 8.1). This is a sequential process where raw data is first collected, organized, and transformed into a stream of interpreted data called information, and subsequently transformed into usable knowledge through intellectual operations that provide more value to information (Monino, 2021). Through data analytics, organizations have the potential to harness data to uncover previously unseen market insights and business opportunities.

Tourism firms have used data, even big data sets, for a long time, and they have a natural tendency to store all kinds of data. What distinguishes the present moment from any previous one is the ability that firms now have to combine these vast amounts of data with innovative manipulation and knowledge generation techniques (e.g., Big Data, analytics, artificial intelligence, etc.) and consequently boost innovation and business performance (Tsaih & Hsu, 2018). Forecasts predict that the amount of data stored worldwide will increase fivefold, from 33 zettabytes in 2018 to 175 zettabytes in 2025 (Reinsel et al., 2018). The aftermath is a market for Big Data technology that is projected to grow from US\$41.3 billion to US\$116.1 billion in 2027 (Fortune Business Insights, 2020). Both are clear indicators that show tourism firms how the economic value of data is a key factor that cannot be ignored and that firms are experiencing an unequivocal transition from an economy based on tangible assets to one based on intangibles (Mihet & Philippon, 2018). Tourism firms should therefore not delay in adopting this process of change and start integrating data into all new and existing processes.

## Fundamentals of Data-Driven Organizations

A data-driven organization is one whose decision-making relies on data from a combination of sources in order to gain competitive advantage and create value (Berntsson Svensson & Taghavianfar, 2020). The three main components of a data-driven organization are as follows (Kiron, 2017).

1.  A high-quality, well-governed database.

2.  A culture where data is viewed (and treated) as a key organizational asset and continuously analyzed in search of insights that inform business strategy, new business value offerings, and increase customer and employee engagement.

3.  Data-driven capabilities that enable the use of analytics to support decisionmaking and strengthen the business model.

One good reason to become a data-driven organization is the need to do something with the constant influx of data generated by mobile phones, information systems, machines, the Internet of Things, and all kinds of applications. But also because of the constant requests from many owners and managers to be able to make decisions based on evidence that, ultimately, improve strategies and the effectiveness of actions (Hume & West, 2020).

In theory, a data-driven organization can use data for all types of decisions (e.g., strategic, tactical, operational) and for all types of analysis (e.g., descriptive, predictive, prescriptive). In practice, organizations use a combination of types of analysis and decisions based on their goals and the sort of value they expect from each decision. A good handful of organizations have already begun to use data in a highly systematic and calculated way to address strategic challenges and react to, and even anticipate, changes in the marketplace. What these organizations have in common is that they view data as a critical asset.

To create value from data, it is not enough that the right person receives the right information at the right moment. The information must also be relevant to the person making the decision. The problem is that in an age of information overload like ours, the ability to discern the correct information is undermined. Most decisions in tourism firms are still made based on the experiences, opinions, and intuitions (or a combination of them) of different stakeholders. Moreover, many decisions about which products or service to innovate, with which partners to ally, or how much to invest in a new market are influenced by politics and individual agendas rather than by the true value expected for the organization or for the customer. Even when data is available, too much information or lack of relevance of the data can puzzle the decision maker and ruin decisions (Berntsson Svensson & Taghavianfar, 2020).

In organizations where managers are used to making decisions based on their own experience and intuition, it is normal to think that they do so because they are the most appropriate people given their qualifications and the relevance of the information they possess. However, in data-driven organizations, business leaders are convinced that data analytics can help their organization improve its competitive edge and are therefore willing to use data systematically to support decisionmaking. Data analytics is not only used to prepare reports or make operational or tactical decisions, but to decide on key issues such as budget allocation, the creation of new products and services, and even the business model (Kiron, 2017). Furthermore, leaders pay close attention to the quality of data collection, data processing, and analysis techniques, aware that the quality of their decisions depends heavily on the quality of data sources and visualizations, as well as their ability to interpret the processed data (Berntsson Svensson et al., 2019).

All the above could lead business owners and managers to think that in the data-driven organization there is no place for experience or intuition, but the truth is that data cannot replace experience, nor experience data. The way data is created, processed, and analyzed is the result of many individual decisions that introduce personal biases. Data-driven evidence will continue to be weighted with experience, and as analytics becomes a more widespread tool for creating value for organizations, experience will continue to play an important role in determining what value can be extracted from data.

## Key Elements of the Data-Driven Organization

Although the potential benefits to be gained from data are huge, the number of tourism firms using data to successfully transform into data-driven organizations remains very low. Smart tourism firms are data-driven organization which rely on the efficient management of their data assets. For smart firms, data management and analytics become decisive success factors in developing the ability to create, acquire, classify, and generate knowledge, as well as apply it where it can create value and generate competitive advantage. However, there is a conspicuous lack of information on how an organization can manage to transform itself into a smart (data-driven) organization and what are the key elements to consider when transitioning towards a data-driven business model (Ghorbani et al., 2019). Some recent studies have tried to synthesize the highlevel dimensions that describe an organization based on data, which are these five (Fig. 8.2) (Hupperz et al., 2021).

### Digital transformation and data-driven culture

For new and existing processes in the organization to integrate data and take a step forward in smartization, it is necessary that the organization has adopted a digital transformation strategy. This requires that the organization has established a clear action plan that specifies the goals and stages to be followed for an effective transition from the current situation to one based on data. Formulating a digital transformation strategy is always challenging, but implementing the strategy is even more so, as time and resource constraints play a crucial role. The most effective way to succeed, though not always the fastest and easiest, is to build a data-driven culture that creates employee awareness of the vision and strategy to follow, and to integrate the organization into an ecosystem where the firm can engage with other stakeholders to address challenges in an open and innovative way.

### Data science and analytics

Data science brings together advanced knowledge and techniques to analyze and extract value from data. In essence, data science can add value to the organization by bringing greater transparency to firm processes and decisions, uncovering new needs, and identifying new opportunities to innovate. It can also enable more efficient management of the firm's resources and operations given its ability to make connections between various factors and predict what might happen. This requires the firm to have professionals with the knowledge and skills necessary to produce useful and enlightening insights for the business, which is a preliminary step for the organization to create competitive advantages.

Data analytics is the set of knowledge, techniques, and tools that drive the generation of business insights and the creation of value through data for the organization. It can be classified into the following three categories, which we will examine in more detail in Chapter 11 of this book (Berndtsson et al., 2018).

-   **Descriptive analytics:** collects and generates data through data repositories to explain what happened in the past.

-   **Predictive analytics:** uses data mining techniques (e.g., classification, clustering, association) to find patterns in data that were previously unknown to predict what is going to happen.

-   **Prescriptive analytics:** analyzes both descriptive and predictive business information (e.g., data on customers, sales forecasts, etc.) to help decide what can be done.

### Data-driven business model

To create true economic value for the firm and its stakeholders, the business insights produced by analytics must be transferred to the firm's business model. There are many possible ways to develop a data-driven business model, but perhaps one of the most compelling is to pay close attention to market demand and figure out how the organization is going to discover, create, and capture value, especially from its key resource: digital data. With that purpose in mind, organizations must focus on their core informational resources and capabilities, integrate processes and technologies to explore and exploit their data resources, and measure the value created and captured. In addition, organizations must continue to fine-tune the business model using internal and external operational data to ensure that it will continue to generate value in the future.

### Data-driven innovation

Data-driven organizations generate and collect vast amounts of data that should not only be used to transform business activities and make them more efficient, but also to innovate. To use data for innovation purposes, organizations need to constantly discover data, analyze it, and try to predict and optimize future events using algorithms. Once new business insights have been generated through the exploration and exploitation of data, the organization must have mechanisms to distribute all this information and knowledge to the different departments of the firm so that they can start creating value from them. The new capabilities that data brings to organizational innovation make research and development activities increasingly relevant to discovering business opportunities that might not otherwise be realized.

## Benefits

Some studies on non-data-driven organizations have come to identify as many as 23 potential benefits of migrating to a data-driven organizational model. The more data-driven an organization is, the more productive it becomes, specifically up to 5% more productive and 6% more profitable compared to the competition (McAfee et al., 2012). Berntsson Svensson & Taghavianfar (2020) have grouped these benefits into the following six categories.

-   Decisions

-   Understanding the customer and user

-   Creativity and innovation

-   Productivity

-   Market position

-   Growth opportunities.

Among the above benefits, the most relevant for the study participants were those related to decisions, customer/user understanding, and productivity. According to firms, organizational decisions improve significantly as a result of a more data-driven approach, and decisions become more accurate by combining internal data with external data (e.g., competitor data with market trends and sales). In addition, for some firms, decision-making also becomes faster and, therefore, they can react much sooner to changes in their environment.

Another key benefit noted by firms is improved customer satisfaction, as the data-driven organization develops insights that enable it to offer customers the products and services they need. In this way, firms can better understand customer/user behavior and where customer churn occurs. Improved productivity is another potential benefit identified by firms. Data-driven organizations can increase efficiency in product and service development and reduce time to market. Furthermore, because data processing enables automated operations, it's easier to identify problems, provide faster solutions, and get more done with fewer people.

## Challenges and Enablers

Some field studies have attempted to explain in recent years the main challenges that organizations face in their journey to become data-driven. For example, in a survey of over 3000 business executives, LaValle and colleagues reported that organizations have more data today than they can use effectively, and that organizational leaders want more computational power and analytics to exploit their growing data and become smarter. In other words, business leadersare willing to run their organizations on data-driven decisions (LaValle et al., 2011). They want to be able to simulate scenarios that provide advance guidance on what are the best actions to take when unexpected or disruptive events occur (e.g., unexpected competitors, earthquakes, pandemics). In the end, what owners and managers demand are ways to understand the optimal course of action to take, based on complex business parameters and scant information. For these expectations to be met, a lesson must be learned that the information generated through data analytics must be aligned with the business strategy.

Organizations should not collect data and analyze something simply because it is easy to do. They need to determine what their goals are and what kinds of questions need to be answered beforehand. In addition, the answers must be easy for end users to understand and make them available when needed. Ultimately, the above requires that knowledge be instilled in everything the organization does (i.e., development of new products and services, hiring of new staff, financing decisions, etc.).

### Challenges

Realizing that data-driven opportunities are critical to business growth, many business owners and managers are looking for the best place to start. However, often that entry point is elusive and the challenges too daunting. All in all, the firm must address three main challenges from the outset, regardless of whether everything else has been handled correctly (Berntsson Svensson & Taghavianfar, 2020):

-   **Data vs. Intuition:** Many organizations on the path to becoming data-driven struggle to figure out how to move from subjective decisions based on intuition, experience, and opinion, to data-driven decisions. Owners and managers must be aware that organizations do not make this transition overnight but go through a maturation process in which intuition and feelings gradually lose weight in decisions. Contrary to popular belief, the ultimate goal is not to suppress opinion-based decisions, but rather to strike a balance between data and intuition that minimizes errors and inaccuracies in decision-making and focuses on value creation for the business.

-   **Trust:** When the organization decides to focus on data, trust in the quality of the data and the insights gained from data processing is of paramount importance to decision makers. Without being sure that the data is reliable and relevant, and that the findings are interpretable and make sense, decision makers are likely to ignore the data or simply be unwilling to implement data-driven decision-making.

-   **Culture:** It is critical to transforming into a data-driven organization. Indeed, all organizational changes to becoming data-driven should be accompanied by an organizational culture aligned with those higher goals. Creating a data-driven culture is a process that cuts across all functions within the organization. It is never an easy job, and much less in organizations that are not very agile and have deep-rooted hierarchical leadership styles, as in data-driven organizations culture means that people are open to sharing data, are aware that data is a critical asset, and they understand why they do this.

Other authors have identified even more challenges to becoming data-driven, such as difficulty accessing reliable and relevant data, lack of a strategy, lack of adoption and understanding by middle management, insufficient organizational alignment, and employee resistance. Addressing the challenges posed by the data-driven model can also vary significantly by business type and size, as well by the type of activities (e.g., transport, accommodation, personal services). It also depends on the access to data sources, digital technologies available, financial resources, and qualified personnel. Other factors that may moderately affect progress towards a data-driven business include the location of the firm and the maturity of the tourism ecosystem and/or the destination in which the business operates, as well as leadership skills, which determine the way in which owners and managers perceive the opportunities in their environment and struggle to benefit from them.

### Enablers

Among the key enablers driving the transition to a data-driven organization, technology features prominently. As an example, data-driven and analytics-driven organizational transformation simply would not be possible without powerful computing power that is easily accessible and affordable (e.g., the internet, communication networks, and resourceful software and algorithms) (Kiron, 2017). Moreover, the interconnection between Big Data, analytics, the Internet of Things, information technology systems, and knowledge management practices is crucial in the data-driven environment, as is the role of artificial intelligence and cloud computing (Fletcher et al., 2020).

Fortunately, data-driven solutions and computational processing power are becoming more widely available to tourism SMEs through cloud computing, which democratizes access to platforms, infrastructure, and software (Samara et al., 2020). For example, small family-run hotels can store customer data in the cloud and make use of data-driven infrastructure and applications that would otherwise only be affordable for large hotel chains. Paradoxically, while these new technologies expand the pool of data that can support knowledge production and decision-making, they generate more and more insights that are increasingly difficult to interpret and understand by decision makers (Kaivo-Oja et al., 2015). This highlights that while data, knowledge management, and smart technologies are going to be key in the coming years, it is equally true that business managers are entering a new era of information saturation that they had better start learning how to govern.

Being able to accommodate all these new powerful techniques and tools in the tourism firm makes it essential to gather reliable data. If the organization does not obtain clean and reliable data, all analytics, artificial intelligence, and machine learning techniques are worth nothing. The firm would find itself in a scenario of the type "garbage goes in and garbage goes out". When data is unreliable, erroneous, or incomplete, this leads to bottlenecks in data processing and, ultimately, to failures in service with unfavorable consequences for the competitive performance of the organization. Yet this problem is not solved by removing empty spaces in data or fixing incorrect characters in datasets. This requires having a strong data governance practice in place, i.e., data must start to be treated as a core organizational asset of the firm as a preliminary step to gain a deep understanding of the relationships that exist between data, users, and organizational activities. Organizations must also develop a common vocabulary for data (Kiron, 2017) and appoint owners of various types of information (e.g., Chief Data Officers) who are responsible for creating reliable data and ensuring its accuracy. These data managers must take inventory of available data and determine how it should be collected. If the data does not exist, they will need to find alternative ways to collect it or access external data directly (Hume & West, 2020). The big question at this point is whether all tourism firms have the will and the resources to make those kinds of commitments.

Nobody doubts today that the role played by technology is fundamental; however, this is only part of the story. People are equally important, from leaders mobilizing the organization to embark on the Big Data and analytics journey, to front-line employees changing roles and responsibilities, to data scientists and IT engineers who collect and process a huge amount of information. Data-driven organizations need people with excellent analytical skills, the ability to manipulate and understand large data sets, and with the competences to interpret and apply the results. Without people who know what to do with data and how to leverage it, organizations cannot keep moving toward smartness.

Furthermore, people and technology need to be supported by management processes that guide the entire organization through the different stages that go from data collection to knowledge generation and dissemination. Without them, it simply won't be possible to make any noticeable progress. Many firms struggle to manage the information they have, even after they have collected, organized, and processed it. This is often due to a lack of robust processes to ensure the relevance, accuracy, and timeliness of information, which explains why so many data-driven initiatives fall short of expectations (Kiron, 2017).

One of the few antidotes that organizations can rely on to overcome these threats is leadership. The organization's leaders must be able to integrate data into decision-making with a blend of awareness, patience, expertise, and precise mobilization of resources and manpower. Leadership must focus not only on using data to improve the existing organization, but also on improving the customer experience; perform better operational processes; and design and implement new data-driven business models. Altogether, the harmonious combination of quality data and knowledge, people, technologies, and processes should lead tourism organizations to be more resilient. Resilience is a key feature of the smart organization that is not achieved by chance or accident, but through smart actions that stem from smart decisions made by smart leaders.

## Discussion Questions

-   What kind of difficulties do tourism firms routinely encounter when becoming data-driven organizations?

-   What are the main barriers that firms in each of the tourism activities face to create value from data? How are the tourism activities different from each other?

-   What kinds of public policies can be put in place to accelerate the transition from conventional tourism businesses to data-driven organizations?

-   To what extent does the social, economic, and business context encourage or discourage the transition to a data-driven model? What regional differences exist?

-   What business criteria should a tourism firm consider when deciding to implement a transformation strategy towards a data-driven organization?

-   How should leaders of tourism firms prepare themselves to successfully tackle the transformation towards a data-driven organization?
