---
title: "Smart Transformation Framework"
---

Smart transformation has become a pervasive theme in the discourse of tourism business leaders. The slogans associated with transformation are continually repeated in all kinds of contexts and forums, almost always lacking depth and clarity. Today it is almost impossible to find a C-level executive from a large or even medium-sized tourism firm that has not publicly committed to the need for a digital or smart transformation (Trenkle, 2019). However, it cannot be said for sure that owners and managers really understand what a smart tourism business means. Different stakeholders usually have very different, if not inconsistent, views on what it means to be a smart hotel or a smart tour operator. This makes it extremely difficult to implement truly smart business models. Some business leaders consider that "smartness" serves to improve the brand image and reputation of a business, others that it is related to the optimization of operations and cost reduction, and there are still some who think that it is a source of competitive advantages to attract customers (Mehraliyev et al., 2020).

The continual advancement of smart technologies and the transformational practices that make it possible to implement and extract value from them bring an untold number of challenges for firms of all sizes. Transformation is a complex process in which not only technologies and technology specialists are involved, but everything that the organization is and does comes into play. Dealing with smart transformation ultimately involves significant risks that are highly likely to end up resulting in failure for the organization. For this reason, business owners and managers must fully understand the nature of smart transformation and decide to tackle it early and with the help of tools that can guide them through this complicated landscape. One such tool available to owners and managers is the Smart Transformation Framework (STF).

Today, there are some STFs available for business leaders to analyze, diagnose, and establish a strategy to address smart transformation if by STFs we also mean digital transformation frameworks that are the precursors of STFs. These frameworks generally provide a blueprint or systematic plan that includes standardized dimensions, action areas, and work tasks to help a firm become a "smarter" organization. Choosing an STF to work across the smart transformation process is essential for the organization because this way it will have a clearer and more precise roadmap for how to address the technological and organizational disruption the organization will face, and how to adapt the structure, operations, technologies, culture, etc. to the changes to come.

An STF is not going to protect the organization from disruption, nor is its mission to encapsulate it to prevent change and its negative effects at all costs. It's quite the opposite. The mission of an STF is to showcase the options that the organization can take to tackle change and start a transformation process, trying not to leave anything important behind and avoiding making the mistakes that others have already made.

## Components of the STF

Smart transformation is a journey that involves a complex environment of tasks, resources, and capabilities, but one that can also create considerable opportunities for tourism firms that commit to change. When a firm embarks on smart transformation, it is seeking to become a "wiser" and more agile organization capable of responding to the changing needs of its customers and the environment through a superior ability to make faster and more accurate decisions. However, smart transformation initiatives can become quite a chaotic and risky enterprise if the organization does not have a roadmap that organizes the process and clearly sets forth the strategies to be pursued. Fortunately, firms have STFs at their disposal as a methodological tool that can assist them in this process of profound change, giving them greater confidence and certainty.

An STF is a structured model made up of management dimensions, areas of action, and monitoring processes that guide the organization's smart transformation efforts in an orderly and systematic manner. An STF is essential for tourism firms to work effectively in each phase of the transformation process and find answers to the challenges posed by the dynamics of change. It also empowers members of the organization to assess the status quo, understand the current state and capabilities of the organization, and identify where there are gaps and what are the key areas to start with to achieve the desired goal. Generally, an STF is the result of the analytical synthesis of the best practices developed to date in the field of digital/smart transformation, drafted by interdisciplinary teams made up of different stakeholders (i.e., members of the academy, specialists from the technology industry, business firms, consultants, government representatives, etc.). By distilling all this valuable insights from experience into a few key practices, the STF may illuminate the way forward for business leaders to drive smart transformation.

Based on the review of the literature carried out by several authors (Bumann & Peter, 2019; Teichert, 2019), six key dimensions or core action areas of an STF can be identified: strategy, organization, culture, technology, customers, and people (Fig. 22.1).

### Strategy

Formulating a smart transformation strategy is key for the tourism firm to achieve a successful transformation. However, experience shows that there is no consensus among academics, firms, vendors, and consultants on what is the best way to articulate this type of strategy or what relevance it should have for the organization. Opinions are varied and divided in this respect, between those who consider that the transformation strategy is just another IT strategy that must be subject to (and aligned with) the general business strategy of the firm; those who consider that transformation requires a strategy that merges the IT strategy and the business strategy; and there are still those who argue that smart transformation is so important that it requires a specific top-level strategy separate from other functional strategies of the firm and that coordinates the drivers of smart transformation.

As organizations approach the early stages of smart transformation, it's common for them to pay more attention to specific technologies (particularly those focused on operations) and be less concerned with developing an organizationwide strategy. These organizations are often more reluctant to invest in relevant skills for their employees. However, as firms mature in the transformation process, they become more collaborative and more likely to accept risks. They also feel better equipped to craft a transformation strategy and are even willing to have a dedicated person or team to lead transformation initiatives.

The transformation strategy should be well documented and communicated at all levels of the organization so that employees understand and internalize it. Moreover, the firm should ensure that the smart transformation strategy has committed enough resources to be implemented and that it is updated regularly to adapt to changes in the environment, and trends, and the lessons learned along the way. Finally, it is key that the strategy has the support and recognition of the firm's leaders, not only at the time of its conception, but especially when it is time to implement the planned actions.

### Organization

Because everything in the environment surrounding the tourism firm is changing faster than ever, the organizational model must also transform to support an ever-changing market and operating context. If firms continue to work according to traditional standards, they will have a hard time adapting to the Smart Revolution and will end up dying. Consequently, the way in which organizations are governed and work become key factors. Rigid processes and hierarchical structures are no longer useful to deal with the complexity around the firm, instead firms need to become more flexible and open. Organizations undertaking smart transformation must foster organizational agility and collaboration within and outside the firm. Firms should adopt open innovation practices that extend to all areas or units that produce innovation within the organization, and speed up development cycles and shorten time to market for products and services. It is no longer enough for firms to think of innovation as something they should do from time to time or when they see that everyone else is doing it or the market changes, but that innovation is a continuous process based on short development cycles (which will give the firm a greater capacity to adapt).

Tourism firms need to adopt an approach based on collaboration with third parties and partnership in networks and ecosystems through which they can build win--win relationships with stakeholders and leverage the capabilities of others. This also means that many firms will be inclined to implement Agile working methods and lean operations that, away from traditional hierarchies and overly formal processes, allow them to rapidly iterate the processes of designing, refining, and delivering products and services to customers. All these changes mean that employees will need to adapt accordingly, and new roles will have to emerge to take full responsibility for the smart transformation process. Many organizations will create new roles to meet this need, such as the Chief Digital Officer (CDO) or the Chief Transformation Officer (CTO), although in other cases, it will still be the Chief Information Office (CIO) who is at the forefront of the transformation. There will be organizations in which the roles (CDO/CTO and CIO) coexist and it is necessary to maintain a balance between them.

### Culture

Culture is a key factor in achieving a successful smart transformation. Smart firms have the capacity for rapid experimentation, invest in talent, and work with Agile practices focused on extracting value from data. These types of firms develop a culture that encourages freedom to experiment and offer their employees the chance to continuously test new ideas, thus increasing the chances of having an impact on the firm's performance. That's why, in addition to highly valuing hard skills (e.g., analytical and mathematical methods, computer science, etc.), they will also value soft skills, such as the ability to lead change initiatives, manage teams, perform tasks autonomously, make responsible decisions, creativity, etc.

Culture development implies a strong commitment on the part of the leadership team, which must always support the change strategy in the organization and communicate a clear idea of the target culture in line with the vision and purpose of the organization. Leaders must lead by example and show through their own behavior what changes need to be made and why they are necessary. This highlights how important it is for a firm that seeks to transform to have leaders who envision the future, know how to communicate their vision to others, and inspire and motivate people to pursue a purpose, being aware of the risks that all this entails.

### Technology and data

The use and development of technologies is another key action area within the STF. Smart firms have a strong focus on the implementation and use of technologies that makes them different from the rest. While for many organizations the technology dimension boils down to having a flashy front-end and a well-designed website, or doing a "facelift" here and there from time to time to feel up to date and on trend, for smart firms it means making an extra effort that includes the complete transformation of their technological capabilities. These organizations operate beyond "off-the-shelf" technology solutions that have a broad installed base, and instead explore and exploit a mix of emerging technologies such as Big Data, analytics, artificial intelligence (AI), and the Internet of Things (IoT). They also take advantage of modern architectures such as the cloud and application programming interfaces (APIs) to add cutting-edge technology capabilities in key areas of the business at very low cost. These implementations are often accompanied by the introduction of Agile work methods to gain flexibility and speed in responding to customer needs. In this way, smart firms break ties with legacy systems that hamper their innovation efforts and are a drag on their agility.

Additionally, with the growing threats of cybercrime, firms are increasingly concerned with IT security and protecting access to key assets and resources. This involves not only the personnel in charge of IT tasks, but all the employees of the organization, who must understand what is at stake and adhere to established security rules to ensure continuity of business operations and access to key business resources, including data. On the other hand, data is a key asset for smart tourism firms and their ability to use data to inform business planning and decision-making is critical. Exploiting data is particularly effective to improve revenue management and use dynamic prices, as well as to understand the type of products and services that customers demand, to identify new markets and potential customer segments, etc.

### Customer and value

Firms must leverage the new capabilities offered by smart technologies to make more effective and efficient use of their data, especially customer data. When data is used properly, organizations can tailor their products and services based on the data generated by their customers. Data not only affects the customer orientation of firms, but it can also be used to measure performance so that the organization can act accordingly. If something goes wrong, the firm can more easily trace the causes and provide solutions. That's why smart firms care about acquiring new capabilities and competencies that allow them to collect more data, turn it into insights, and use it for things like predicting customer behavior, delivering personalized products and services, and offering better customer experiences.

Increasingly, tourism customers expect firms not only to be able to respond to their needs when they need it and where they need it, but also to be able to remember them and anticipate their future demands. This enables customers to engage with firms across multiple touchpoints both digital and physical, leading firms to bridge the digital and physical worlds to offer hybrid interaction channels that provide flexibility and convenience to the customers. This poses significant challenges for tourism organizations as they must ensure that the customer experience is consistent across all touch points and that communication is designed to support a multi-channel strategy. Furthermore, since organizations are starting to involve customers in all phases of the product and service innovation process, customers increasingly play a relevant role as co-creators of the products and services that they later consume. Ultimately, the tourism firm must define its own value creation model, focusing on building a value network that will generate revenue (i.e., B2C, B2B, online sales, etc.). All the above are areas in which smart technologies are going to play a crucial role.

### People

In addition to the many technological resources that are necessary to achieve a successful smart transformation, it is crucial that tourism firms find ways to equip their employees with the necessary skills and competencies to compete in a smarter world. Developing people skills involves attracting more talent, enhancing expertise, implementing new technologies, and understanding and exploiting the opportunities that technology can offer (OECD, 2020). Smart organizations will have to develop and implement appropriate training schemes to expand the competencies and skills that their employees will need. This involves taking stock of the capabilities of the workforce and the resources available to the firm and assess whether there is room for upskilling. To do this, firms must actively seek collaboration with universities, incubators, and other institutions to gain access to the critical talent they need. Furthermore, organizations will need to create a workplace that is attractive and flexible for their future workers. This means offering flexible working hours, digital workspaces, mobile work, etc. that increase employee motivation and lower infrastructure costs, and attract digitally savvy millennials.

## Getting Started with Smart Transformation

Smart transformation can be approached through the sequence of phases contained in the STF (Fig. 22.2), each of which contains a set of key tasks to advance the change process. These phases are usually independent of the industry (although some industries may develop its own STF) and the size of the organization, and encompass generic topics that are applicable to most organizations. Using an STF helps organization members lay the groundwork for how they can work on smart transformation, as well as create an Agile way of thinking and acting. The STF also helps stakeholders better align and engage in the key activities of each phase. Figure 22.2 shows the five phases that can guide a tourism firm to start the smart transformation process. Once these five phases are completed, the firm must begin the implementation of the actions that have resulted from the STF.

## Understand the problem

Smart transformation must start with a collective brainstorming effort where everyone in the organization understands the problem they are facing and is aware of the challenges ahead. Sometimes this is not an easy task because, although most tourism firms are used to sensing the effects that occur in their business (i.e., customers stop buying, customers are not loyal), they often don't know the reasons.

In this first phase, the firm must assess its readiness and maturity to tackle the smart transformation process. To do this, hypotheses must be formulated about what is happening in the firm, the depth of the disruption that is taking place around it, and what may happen in the future. This phase should also include a collective reflection through which the firm's ambitions are made explicit, and a shared vision of its future is established. These hypotheses will have to be verified in the next phase once more information is gathered.

Collective creativity techniques can be used, such as visioning and brainstorming, in order to extract expert knowledge from the leaders and members of the organization. Workshops can be held with external experts from the tourism and technology industry to help create a holistic view of the transformation process. Once all this knowledge has been gathered, it is convenient to establish a research plan that lays the foundations for aggregating all the information that will have to be analyzed before defining the strategies and concrete actions of transformation.

It is also important that the work plan to be followed by the members of the organization is established and that the people who are going to participate in the work team are designated, in addition to deciding which are the main work milestones, the calendar, the decision-makers, etc. It is also highly recommended that at this stage a transformation control and monitoring unit is appointed to oversee the progress of the transformation process. This unit may be formed by a representation of the organization's leaders with the ability to decide on the resources and the course of action to be taken by the organization.

### Diagnose the situation

From all the information and expert knowledge gathered through the research work in the previous phase, the firm will be able to better understand where it comes from and where it can go. With this valuable information in its hands, it is time for the firm to make the most objective diagnosis possible about its current situation and its level of digital and smartness maturity, reimagining what its future could look like and how it could capture value from it. The work to be carried out in this phase includes an exhaustive evaluation of the organization's capabilities and the analysis of the functions that contribute to the creation of competitive advantages for the business. Through this diagnosis, the firm will obtain a clear picture of the change initiatives it is currently carrying out and its status. Furthermore, the diagnosis will allow the firm to define its opportunity space; in other words, determining what are the competitive advantages that the firm has and which ones it could focus on in the future to untap its potential, and identifying the existing gaps that it will have to fill in order to achieve its transformation ambitions.

### Define and prioritize strategies

Now is the time to make sense of the diagnosis and decide "what to transform", i.e., decide on the business model, the organizational structure, people, processes, value offerings, customer engagement model, etc. The firm must build its own strategic vision and develop a realistic roadmap that can be put into practice. Therefore, this is the moment in which the firm's teams must reflect broadly and critically on the different strategic alternatives available to the firm to make smart transformation a reality, and define the new futures that will serve as a context for decision-making.

Once the different alternative scenarios have been established, the firm must make its strategies explicit and determine the priority for their execution. Strategies should not only be focused on building a robust and reliable IT framework, but must pay attention to multiple variables, such as customer focus, exploring and exploiting data, creating value with stakeholders, and facilitating fast and efficient decision-making. Without these elements in place, it will be difficult for the strategies to have any relevant effect on the firm's smart transformation. Transformation strategies should cover a whole set of functional (e.g., human resources, ICT, finance), operational (e.g., processes, sales, marketing, products), and corporate strategies (e.g., business models, organizational structure, leadership). All these strategies must be integrated into a road map that shows the way forward towards the organization's vision.

The firm must draft business cases that outline the way in which the required investments are going to be made and the benefits that are expected to be obtained from each strategic line. Early investments are unlikely to generate returns in excess of the cost of capital, while shareholders and the board of directors are likely to expect immediate results. Therefore, the ideal is to devise short-term change initiatives that can generate quick results and, in the process, serve to finance the next long-term initiatives. Existing and emerging technologies that may have a greater impact on the firm should be identified, as well as the future technological architecture of the firm and how smart technologies will be used. This will require the firm to have a solid execution and performance measurement framework.

### Execute plan

In this phase, the firm establishes the deployment plan for the smart transformation strategies. This includes a change management program that ensures that the changes introduced by smart transformation can be integrated into the organization, and that employees are fully aware of what is going to change, why it is going to change, and what can be expected from change. As the organization begins to experience change and the benefits begin to materialize, its management and leadership model will need to adapt. That is why it is important that the firm has a 360-degree vision of the transformation process and is prepared for continuous learning.

The firm should lay the groundwork for a new governance model that supports the transition from the current situation to the future. This new model should contemplate how the firm's organizational framework will evolve and the skills and abilities that future employees must have, as well as the way in which employees will collaborate inside and outside the organization. It is also key that the firm establishes an objective operating framework that states how the processes are going to be organized and how the functions and responsibilities are going to be distributed within the organization. Finally, the firm will need to measure the value and impact of smart transformation initiatives and use the results to refine the change implementation processes.

Culture change among owners, managers, and employees will be a key indicator of the success of the smart transformation process. Without an innovative and data-centric culture, smart transformation will not bear fruit and will be doomed to failure. It will require strong leadership to direct the implementation of transformation strategies and empower the people who work in the organization to contribute, innovate and become more creative and productive. In short, a governance model will have to lay the foundations for a culture that supports high performance by people.

## The Role of Platforms

Digital platforms play a very important role in tourism today due to their innovative business model and their proven ability to concentrate supply and demand in a single place. Platforms business models are characterized by a high level of productivity that is the result of the innovative way in which multiple stakeholders have been engaged to co-create content, collect and exploit market data, and share value among users and customers (OECD, 2017a). In just a few years, platforms have experienced strong growth to the point that many tourism firms around the world now seek their place within these ecosystems, having to adapt their business models in accordance with the requirements that govern them.

Digital platforms such as Tripadvisor, Airbnb, and Booking.com are key to the daily operations of many tourism firms, but they are also key enablers of digital and smart transformation. These platforms provide firms with technical and business functionalities that go beyond online transaction processing, as they offer value-added functionalities related to data access, data analysis, and market intelligence that allow SMEs to learn more about their business and customers (L. Li et al., 2018). In this way, through the platforms tourism SMEs have an easier time overcoming many of the barriers in the effective use and adoption of digital and smart technologies and are encouraged to enter the culture of data and acquire new resources and analytical capabilities.

Furthermore, as digital platforms grow and evolve, platform providers are updating the services they offer and refining the terms of business to adjust them to the changing needs of customers and users. Platforms encourage firms to innovate to meet market and customer demands and to follow the rules set by the platform providers in order to maintain competitive advantages over their competitors (Jiao & Chen, 2019). Together, all these functions and capabilities provided by the platforms allow many tourism SMEs to increase their skills, grow their businesses in the digital world, and expand their markets. Additionally, some platforms offer management-oriented services, such as learning sessions, webinars, conferences, meeting events, etc., which are instrumental in helping tourism firms join open innovation ecosystems and prepare for digital and smart transformation. Without many of the services and support these platforms provide, it is likely that many owners and managers would not have cared about digital transformation and would still be far from understanding the true dimension of the Smart Revolution.

## Smart Transformation in SMEs

SMEs are a large part of the value creation units and the backbone of most economies in the world. However, more than two-thirds of SMEs are lowtech, which means that a very high proportion of them struggle daily to make progress in digital/smart transformation and still have years of work ahead to reach a level that allows them to be competitive in the new smart context (Hönigsberg & Dinter, 2019). Provided that smart transformation can be considered a radical innovation itself, since it implies a profound change in processes, in the firm's value proposition, in the relationships with customers and suppliers, and even in the business model, it still offers many opportunities to tourism SMEs. The other side of the coin is that smart transformation also imposes important obligations: having adequate financial resources to face change, having qualified personnel to lead and manage the process, overcoming resistance and organizational challenges, reformulating legacy technologies and the operations model, ensuring data access and reliability, etc. Many of these are also common obstacles to innovation.

There are many owners and managers who think that SMEs will be the most negatively affected by smart transformation due to the complexity of the process and the amount of resources it requires (Beliveau et al., 2018). There is no doubt that these factors are major obstacles, but it is also clear that SMEs are among the main beneficiaries of smart transformation. Very often SMEs are in a better position to deliver smart transformation faster than large firms and can more easily develop new smart IT frameworks from scratch. Owners and managers must be aware that SMEs and their organizational characteristics differentiate them from other types of firms, which makes smart transformation a distinctive process due to the following factors (Trenkle, 2019):

1.  **Leadership:** Which is usually exercised by the owner of the firm who is the one that makes most of the important management decisions that affect the business.

2.  **Organization:** Which is usually of a hierarchical type, with the owner and managers located at the top of the pyramid and accumulating various roles. The rest of the staff is at the base and is focused on executing the operational tasks of the business and supporting decision-making.

3.  **Process design:** With a low degree of work distribution, low openness to external collaboration, and a high dependence on "universal" technologies that are more focused on supporting business operations and with little orientation towards the creation and management of knowledge.

4.  **Sales and marketing:** Mainly focused on regional and/or local customer segments, who are offered specialized services in which personal and human relationships prevail.

5.  **Innovative capacity:** Usually without a formal R&D department with the right people and resources; scarce and very short-range R&D activities; limited financial resources; and a more reactive than proactive purpose.

Operational aspects and especially those that have to do with people (i.e., organizational structure, leadership) have a higher relevance in SMEs when compared to process frameworks and well-defined formal responsibilities, which predominate in large firms. The human component is key in the conception of smart transformation in SMEs and helps to better frame the context in which SMEs develop. Owners and managers, assisted by small management teams, are generally the ones who take responsibility for transformation actions. In SMEs there is normally no structure of C-level responsibilities as in large firms with perfectly defined roles and responsibilities. Hence, it is the owner or managers who must find a way to personally acquire the knowledge to improve their skills and understand the terms of the Smart Revolution. Below are some of the most relevant obstacles that are specific to SMEs and that every owner and manager should take into account when tackling the smart transformation.

### Economic and financial

Financing smart transformation activities is one of the hardest parts for SMEs, especially as their financial resources are often very limited. The volume of investments required for smart transformation is significant, both in monetary terms and in terms of people and time. Therefore, when dealing with smart transformation, it is always desirable to have a solid financial structure. However, it is quite common to see that banks are reluctant to lend money to SMEs for ambitious technology projects when there is no business case that can fully guarantee a level of performance. This problem is exacerbated when the ROI of smart technologies is often not clear, either because the potential of some technologies is not always evident, or due to the difficulties faced by SMEs when measuring or anticipating results. Most of the time, owners and managers have no choice but to seek other financing options to raise sufficient resources, and this includes, in addition to the firm's own funds, applying for public aid programs (e.g., digitalization programs, economic development programs, loan guarantees, R&D funds, etc.) and other less conventional private capital formulas such as venture capital and crowdfunding.

Another key economic/financial issue is that owners and managers seem to be very clear that when the products and services offered by the firm have a low value, it is not worth betting on smart technologies that are complex and expensive. This contrasts with the pressure they constantly have to keep margins stable (if not growing) and take action immediately when margins deteriorate for whatever reason. Smart transformation can offer owners and managers significant opportunities to increase efficiencies and exploit new revenue streams, so it would certainly be worthwhile to evaluate different financing options.

### Organizational and cultural

Smart transformation requires SMEs to reconsider their organizational structure and the principles and values on which the organizational culture is based. This usually drives SMEs to rethink the structure of the organization, redefine roles and responsibilities, and ensure that they have the appropriate employees and skills to successfully address the transformation process. Obstacles often appear as with leaders reluctant to make deep changes at the organizational level; organizations that oppose or are resistant to change; employees who fear losing their jobs or worsening their working conditions and do not want to get involved or committed; lack of understanding of the principles of the Smart Revolution and its implications for business, etc.

Recent studies suggest that the best way to assign responsibilities at the forefront of digital transformation is to share them between the CDO and CIO (Singh & Hess, 2020). However, in SMEs there is not usually this diversity of roles, and most often it is the owner or manager of the firm who becomes the person in charge of the smart transformation process. This is not necessarily a problem, as having a single person in charge is generally considered a success factor (Hönigsberg & Dinter, 2019). The fact that the firm has a person responsible for the transformation is not a guarantee of success either -- it all depends on how this person exercises responsibility with vision, commitment, and leadership. Furthermore, SMEs often assess how the digital/smart transformation process will integrate within the firm's existing structures, and they will rarely create an autonomous entity to manage the transformation, except when the transformation initiative becomes very ambitious. SMEs are also more limited than large firms when it comes to acquiring skills and talent, and they tend to focus more on developing their own staff and attracting young talent with digital skills.

### Competencies and resources

SMEs face the usual problem of lack of technical knowledge when dealing with transformation processes. In general, SMEs struggle to find qualified employees with the required technical competences that they need to incorporate into their teams and that have the necessary knowledge and skills. In addition to this lack of qualified employees, there is also the barrier of high effort involved in coordinating the tasks and activities associated with the transformation to ensure that the entire organization pursues the same objectives.

### Legal

In many developed and developing countries bureaucracy and restrictive laws and regulations are a major obstacle to implementing smart transformation. Among the legislation that most affects the development of smartization is that related to the privacy of personal data, data security, and consumer protection. In other countries, however, legal barriers are less relevant.

### Technical

The pro-technological ambition of the owners and managers of the firm to adopt the latest smart technologies is crucial to anticipate the intensity in the implementation of smart transformation and the benefits for the organization. This personal characteristic is often the result of the knowledge and previous training of the owner/manager, the entrepreneurial and dynamic character, personal experience, existing skills in the workforce (and in the firm's networks), and the financial situation of the firm. Some owners and managers consider that smart technologies are facilitators of the strategic objectives of the firm and by implementing them, new business opportunities can arise. These individuals actively seek out new technological advances and constantly scan the technology landscape for new opportunities. Other owners and managers perceive smart technologies more as necessary tools to support business operations, and as such these technologies are important to remain competitive. Still there are other owners and managers who choose to stay as far away from the technology as possible, and consider it a no-go field that they prefer to leave in the hands of second-level IT technicians. Last but not least, SMEs often have quite different ICT systems in place, and their data is stored in different silos that often do not communicate with each other, which is a major obstacle to smart transformation. Technological immaturity is common in SMEs and this is reflected in the great uncertainty about the reliability of systems and data, as well as in the weak IT infrastructure and the interoperability issues that arise between systems and applications.

### Implementation process

SMEs generally lack a methodical approach when it comes to implementing smart transformation. Often this is due to the very novelty of the smartization phenomenon and the fact that there is not yet enough experience and knowledge that can be crystallized into a commonly accepted methodological approach or, if it exists, it is not easily adapted to the specific needs of SMEs. On other occasions, the reasons are that many owners and managers are unaware of the existence of STF approaches and that the number of best practices is still small.

## Discussion Questions

-   What methodological approaches could be more valuable for tourism firms to successfully address smart transformation? What elements should these approaches include consider to be adopted by tourism firms?

-   What factors, other than financial constraints, may have a larger influence when prioritizing smart transformation strategies?

-   What factors does the tourism firm depend on to develop an organizational culture that accelerates smart transformation?

-   What factors differentiate smart transformation in SMEs and in large firms?

-   Do you know of any good practice from an SME that shows how smart technologies have been successfully adopted? Describe the fundamental aspects that characterize it.

-   What role do you think platforms such as Tripadvisor, Airbnb or Booking.com will have in the future as tourism firms become smarter?

-   Which of the specificities discussed in this chapter do you think are shaping most the transformation process of tourism SMEs?
