---
title: "Fundamentals of the Smart Firm"
---

Tourism is transforming at an accelerated pace that has never been seen before, impacting consumers, businesses, and destinations alike. However, the reasons that are driving this moment of profound change are neither new nor exclusive to tourism. Throughout history, both society and businesses have witnessed other moments of dramatic change that paved the way for new structures, cultures, and behaviors to reach what we are today.

The First Industrial Revolution brought advances in the production of goods. The introduction of a new source of energy such as steam meant that many of the tasks that were previously carried out manually could be mechanized, leading to the emergence of production lines for the first time. At the end of the 19th century, the changes initiated in the First Revolution accelerated, giving rise to the Second Industrial Revolution, which led to the introduction of mass production. Since then, millions of consumers began to have access for the first time to thousands of products that were of good quality and affordable. Not many years passed until the Third Industrial Revolution, also called the Scientific-Technological Revolution, introduced the massive adoption of information and communication technologies (ICT) in the means of production, thus facilitating the emergence of new distribution channels that broke the limits of trade at a geographical level and expanded it to all corners of the planet through e-commerce and advances in transport networks (Gaurav & Kongar, 2021). Our time in history is sustained by the unstoppable digital advance that has caused a drastic reduction in employment in the agricultural and manufacturing sectors, while employment in the service sector has skyrocketed.

Has the history of human progress ceased since then? Of course not. History has not stopped being written for a single moment and has run its course inexorably, to the point that today we take for granted that the Third Industrial Revolution has been far surpassed and that we are living the dawn of a new revolution: the Fourth Revolution.

What makes our time different from other past times? Our time is distinguished by the massive incorporation of information and knowledge in everything we do, buy, or produce. We individuals have become accustomed to others doing the work for us, or at least making it easier for us -- with someone recommending us those products and services that best fit our personality, state of mind, or moment in life. We make decisions based on the experience that others before us have had when they bought a product or service, and we expect firms to do everything possible to adapt their services to our preferences and demands.

Have we all become spoiled children? Surely not. Still, we'd better examine how we got to this stage, which certainly hasn't been a bed of roses.

## The Origins of Smart Tourism

The road to where we are today has been littered with disruptive changes that previous generations had to respond to and adapt to, no doubt. Those people had to struggle to find the right mix of entrepreneurship, innovation, and technology adoption that would allow them to leap forward. Is it something different now? Not at all. Now it is our turn to do the same because we have entered a comparable historical moment.

In tourism, the rapid development of ICT has led to similar phases of progress that nonetheless have their own particularities. Until now, traditional tourism activities were based on close personal relationships, mutual trust, and personal attention. At a business level, the tourism ecosystem was dominated by a few large companies that influenced tourists' decisions almost at will, monopolizing value offers in the world's main tourism markets. On the other hand, consumers did not usually complain and accepted the conditions imposed by the big operators, grateful to be able to enjoy a vacation without unpleasant surprises and at prices adjusted to their purchasing power.

The advent of Google changed the rules of the game. The swift popularization of search engines allowed prospective tourists to access information from hundreds of tourism service providers and compare them in a matter of seconds. That was only the beginning of a story of sweeping changes to come in the way tourism consumers and businesses interacted, which continues to this day. Unimaginable new business models began to emerge that replaced many of the traditional models and sought to satisfy entirely new market niches and facilitate consumer decision-making. It was in these times that travel blogs, recommendation sites, and price comparison systems started to appear (Zsarnoczky, 2018).

The accelerated adoption of digital and online media by consumers meant that tourism firms had to start thinking very seriously about the need to change and adapt their "analog" products and services, if not to create them from scratch. Designing products from the perspective of the "new tourist" began to become a necessity. Since then, getting to know the "new tourist" in depth has become an integral part of the design of business models, and of products and services. Nowadays it would be simply unthinkable for a tourism firm to survive in the market without having this knowledge.

Challenged by this avalanche of sweeping changes in the way tourism firms are required to operate, many firms have simply been unable to keep up with the pace of change and have been left out of the market. This would explain the renewal that the tourism ecosystem has experienced in recent years at the business level. Figure 5.1 illustrates the evolution described, from traditional tour operators with a low level of digitalization to the present day, characterized by the digital transformation of operators and the growing but unstoppable integration of smart technologies in tourism firms.

### Phase 1: Traditional tourism

This phase is characterized by the pervasive influence of tourism service providers on consumer decision-making, as they dominate the tourism ecosystem at a global level. The adoption of ICT by tourism firms is still very low and most are largely unaware of the individual tastes and preferences of their customers.

Instead, management's focus is more on continuous quality improvement, the efficient operation of processes, and the generation of economies of scale to improve commercial margins.

### Phase 2: e-Tourism

This second phase (1990--2000) is marked by the integration of the internet into the daily lives of consumers and tourism firms. Firms realize the need to be on the internet to serve a growing number of potential customers and the great potential of the World Wide Web as a sales and marketing tool.Nonetheless, communication with customers remains rudimentary and mostly one-way (e.g., via phone, email, and electronic forms). The websites of tourism firms become shop windows open 24 hours a day to any customer in the world regardless of their physical location, and owners and managers begin to see the electronic channel as a promising source of income generation. Paper is replaced as the main support in communications with customers and tourism firms starting to mass-produce digital content, aware that it can be delivered instantly to the people. New electronic and online marketing tools emerge that contribute to improving business performance.

### Phase 3: Digital tourism

In the next decade (years 2000--2010), the internet consolidates as the main source of information for tourists, and the main channel through which information is shared between consumers and firms. New internet technologies open up the possibility for consumers to search and compare information for their trips in a matter of seconds and for firms to create transactional gateways for their products and services. New intermediaries appear that develop business models unknown until this moment. The consumer becomes a co-creator of content and has a much more influential role in decision-making. Traditional operators are forced to transform their business models if they want to survive, meaning that they need to establish much closer ties with their customers and be willing to personalize their product and service offerings. On the other hand, customers begin to think of tourism as an experience that they themselves are willing to create, and the traditional view of the product or service that cannot be controlled is surpassed.

### Phase 4: Smart tourism

Starting from 2010, advances in mobile technologies, communication networks, and cloud computing, accompanied by increasing integration and interoperability between the physical and digital worlds, lay the foundation for the transition to the era of smart tourism. Combined with social networks and Web 2.0 platforms that facilitate two-way communication with consumers, the possibility of co-creating new experiences with users becomes a reality in this phase. All the above creates the opportunity for firms to obtain an amount of data like never before. From now on, the ability to exploit data and turn it into actionable knowledge becomes a crucial factor for firms to create competitive advantages and thrive in the marketplace.

## Definition of Smart Tourism

No one doubts that the term smart has become a buzzword nowadays. It is not only used as an adjective to describe people or animals, but we can practically find it in anything that incorporates some technology with which we can interact in a more "intelligent" way, that is, faster, automatic, intuitive, or more efficient (e.g., a television, a sports watch, a motor vehicle, etc.) (Poslad, 2011). The Oxford English Dictionary defines the term smart as something "smart" "controlled by a computer, so that it seems to act intelligently". So we can ask ourselves, how is the term intelligent defined? In the case of a person, it is the ability to understand and learn things. In the case of a computer or program, it is the ability to store information and use it in new situations.

Although these definitions give us a rough idea of what the term smart means, the truth is that intelligent and smart have some differences that should be considered, especially when we are in a business context. "Smart" usually refers to the ability to adapt to changing situations caused by different customer needs, past experiences, or particular environmental conditions. In this context, technology is one of the key drivers that would enable organizations to speed up response to changing conditions. In "intelligent tourism", tourists become passive consumers who are offered various options among which they must "intelligently" choose the one that best suits their needs. Different levels of intelligence would thus lead to different types of services and experiences.

In this book, the term smart is used to refer to state-of-the-art information systems and processes that provide tourists and firms with relevant information, facilitate better decision-making, greater mobility, and a more pleasurable experience in accordance with the preferences and needs of the tourist at all times (Pinheiro et al., 2021). Smart information systems encompass a wide range of technologies, which can be very useful for the tourism firm depending on the environment and the stage of the experience cycle in which they are used. Some examples include recommendation systems, environmental sensing systems, and ambient intelligence systems. Notwithstanding the foregoing, owners and managers must be aware that the term smart not only covers information systems and digital technologies, but also denotes a process that we will call "smartization", which transcends the mere technological dimension and implicitly affects other core organizational components such as innovation, leadership, and human capital (Boes et al., 2015). In a similar fashion, when we talk about the adoption of a higher degree of "smartness" through the transformation of the organization, we will be referring to a process that is intrinsically different from the implementation of conventional technologies, and that has a strong relationship with the management practices that must be used to accommodate change within the organization.

So, now that we have an idea of what smart means in this book, what do we mean by smart tourism? The notion of smart tourism is a reflection of the profound impact that smart technologies are having on the tourism consumer and on the products and services (Mehraliyev et al., 2020). The importance of smart technologies is increasing as the role of tourism consumers and firms is changing, and with it the boundaries of the tourism ecosystem. Smart tourism is a much broader notion than intelligent tourism, as it emphasizes the results that technology can offer tourists and that require a large amount of information and data to materialize. In smart tourism firms need tourists to be active all the time so that they can provide a huge amount of information that can be collected, processed, analyzed, and transformed into individualized knowledge by firms to deliver accurate products and services to tourists. Whereas smart tourism relies heavily on the availability of data and data processing capabilities to anticipate the needs of tourists, intelligent tourism provides a much more basic utility from the available data and information. As an example, the process of generating a travel route automatically from a small number of inputs provided by the user through a mobile application to which an optimization algorithm is applied, is intelligent. If in the same process information is added about the user's experience, information about the location where the user is or wants to go, or other information about the user's buyer profile, personality, etc., this is smart (Y. Li et al., 2017).

In summary, smart tourism involves the use of technologies to collect and exploit large amounts of data and provide real-time service delivery to tourists. These so-called smart technologies are not only the internet and mobile devices used to communicate, but also include the infrastructure that integrates hardware, software, and communications, as well as networks that provide real-time data to facilitate faster and more efficient decision-making for stakeholders (Dorcic et al., 2019; Gretzel et al., 2015a). Ultimately, the use of smart technologies by tourism firms largely depends on their ability to collect data in large quantities that can then be transformed into useful knowledge.

## What Is Smart Tourism For?

The debate in academic and professional forums is still ongoing in trying to reach a definitive and widely accepted conclusion of what smart tourism is and what its main components are. Unfortunately, on many occasions these discussions lead to ideas of little use to owners and managers, who are more concerned with understanding the phenomenon of smartization and how to benefit from it than with theoretical discussions that contribute little or nothing to improving the performance of their business.

The fundamentals of smart tourism lie in the tourist. The new applications of smart tourism are activated by the behavior of tourists, so changes in their needs and demands are the real driving force of smart tourism. Any benefits derived from smart tourism will arise from the needs of tourists and changes in their behavior (Y. Li et al., 2017). Consequently, the role of the tourist as an informational asset is essential, as evidenced by the fact that the value of information for tourists, tourism firms, and destinations has not stopped growing in recent years. Without tourist information there simply cannot be smart tourism.

### For tourists

Smart tourism provides tourists with access to more comprehensive, portable,and personalized information based on their needs, allowing them to organize and fine-tune the tourism experience more quickly and accurately. For more and better information to be accessible, tourists must provide relevant connected data about their behavior, demands, or personality, so that tourism firms can deliver accurate digital informational resources at their fingertips (e.g., text, pictures, video) through a variety of devices and technologies. The type of value that tourists obtain in exchange for the data they provide is independent of the way in which tourism firms collect and process that data about their behavior and needs.

### For owners and managers

Smart tourism is about building an integrated framework of services and technologies that is comprehensive and provides the tourist with a range of services that are accurate, convenient, and ubiquitous. From a technical perspective, such a framework allows for continuous interaction between the assets of the firm (more specifically between the digital representation of those assets) and the tourist needs to create more meaningful relationships with tourists. In this way, smart tourism provides tourists with entirely new ways of consuming tourism services, and tourism firms with new possibilities to create value through innovative combinations of tourism information, services, and technologies.

Readers should note that not all tourist information falls within the scope of smart tourism. Indeed, tourists can obtain valuable information from very different sources. Sometimes the information will come from websites; other times from social networks, or even from the tourist information offices of a destination. However, only the information that is ubiquitous and that is delivered to the tourist according to their individual requirements is what we will call smart tourism.

## Components of Smart Tourism

It is not an easy job trying to summarize in a few pages the most important components that characterize smart tourism and that distinguish it from conventional tourism. Nor could it be exhaustive because any attempt to do so would require much more extensive work. Most likely, it would not be of much value to the reader either since the very idea of smart tourism is not yet fully developed. Even so, the components with which every owner and manager should be familiar and that most directly affect the tourism firm are described below.

One of the main components of smart tourism is tourist information. In smart tourism, information is no longer that old static information aimed at poorly differentiated groups of consumers that was delivered through a few channels enabled by firms in a rather unstructured way. In contrast, the information in smart tourism is ubiquitous, and is created to meet the individual needs of the tourist. The ubiquity of information means that tourists can easily access information from anywhere, at any time, and through any type of media on the internet. Access to tourist information is provided through devices that are part of everyday life for most people and that provide tourists with a large portable computing capacity, such as mobile devices, portable devices, and other non-conventional means. The very idea of ubiquity implies that, through smart tourism, people have overcome the limitation of having to sit in front of a desktop computer to access tourist information and services. Instead, it involves a radically new way of shaping space and time to the individual needs of the tourist.

Ubiquity, however, not only encompasses information, but also the tourism firm itself, to the point that we could speak of the "ubiquitous firm". These are firms that have the ability to provide, optimize, and improve services as they are delivered, using ubiquitous marketing, ubiquitous supply chain, and ubiquitous management. The target of the ubiquitous firm is no longer the group of tourists (understood as a set of consumers who share certain attributes that make them similar in the eyes of the firm and for whom generic products and services are created), but the tourist as an individual. This means that smart tourism firms remain focused on individuals with special needs, who have an autonomous behavior that makes them different from other tourists and with the ability to establish their own preferences through the (ubiquitous and bidirectional) communication channels made available by the firm.

Smart tourism firms devote their resources (e.g., people, money, infrastructure, etc.) to create and capture value from the data generated by the behavior of tourists at any given time. This is what we call business development the smart way. In other words, smart tourism firms' development depends to a great extent on Big Data and their ability to extract value from it through more relevant relationships with tourists and improved products/services. To create more relevant relationships between tourists and firms another key component must be considered: the smart tourism ecosystem.

Smart tourism firms operate within an ecosystem in which tourism products/ services (and experiences) are created, managed, and delivered through smart technologies. These technologies are very special because they require the intensive use and constant exchange of information resources to, from, and between tourists, tourism firms, and destinations, to create shared value from the Big Data (Gretzel et al., 2015b). Smart technologies are basically those ICTs that allow constant communication and interaction with tourists, from whose behavior and demands data is extracted that can later be exploited by the tourism firm to generate useful knowledge for the business. Note that the smart tourism ecosystem would simply not work if the actors involved were isolated or separated from each other. They must be connected through (smart) technologies, with the tourist located in the center so that the smart ecosystem can work properly.

This tourist-centric approach that characterizes smart tourism is part of its idiosyncrasy and is another of the key components that differentiate it from conventional tourism. Business owners and managers should not forget that smart tourism is created with the aim of satisfying the individual travel, mobility, accommodation, catering, and leisure needs of tourists based on their personal preferences. The tourist-centric approach of tourism firms is made possible thanks to the rapid advances and intensive use of smart technologies (e.g., Big Data, analytics, artificial intelligence, cloud computing, mobile and network technologies with high computing capacity and connectivity). The adoption of smart technologies into the consumption habits of tourists has forever transformed the way they consume tourism products/services and enjoy tourism experiences.

Tourism firms' use of smart (customer-centric) technologies puts them in a privileged position to meet the individual demands of tourists and improve satisfaction levels. It also provides tourism firms with the opportunity to radically improve their products/services and revamp tourism experiences through the implementation of new and innovative management practices that optimize the use of internal and external resources and are aimed at co-creating value with tourists, destinations, and the ICT industry. In short, smart tourism with all its components constitutes a framework for action to improve the management of tourism firms that can contribute very significantly to improving their competitiveness and performance.

## Impact of Smart Tourism

The process of change towards smartization is a breakthrough that confirms the transition of the tourism sector towards a modern service industry. This process brings highly relevant impacts that will undoubtedly be the catalysts for the future developments of tourism in the coming years. As we have seen, smart tourism builds on top of earlier phases of social and business development, when everything was more focused on the informatization and digitization of the tourism business. That is why it is worth examining the most notorious impacts that smart tourism is having on consumers and firms.

### Impacts on tourism firms

One of the key benefits of smart tourism for firms is that it provides a two-way communication channel between tourism firms, tourists and the rest of the actors involved in the value chain. "Smart channels" are created that operate as high-speed highways through which a constant flow of data and information circulates and is disseminated in a rather personalized and efficient way among all tourism stakeholders. In this way, smart tourism strongly impacts the commercialization and marketing of tourism products/services, given the variety of media that can be used (e.g., text, images, videos, and hybrid combinations), the ability to monitor the demand and quality of the services provided, and the possibility of quantitatively measuring the performance of campaigns.

From a management perspective, smart tourism offers tourism firms the opportunity to configure their own value offer to the customer in a quite flexible way, activating a much deeper knowledge about the customer that translates into delivering information, products, and services in accordance with the location and the requirements of the customer. However, achieving "smartness" is not straightforward. It requires the firm to redesign its internal processes, so that integration with smart technologies is seamless and contributes to improving the operational efficiency of the firm's business. For example, a hotel can have room check-in and check-out done via radio-frequency identification (RFID) systems, or the tourist can read a menu, book a table, and have access to entertainment services in the room all through the same mobile device.

One consequence of the above is that the tourism firm can end up optimizing itself thanks to smart tourism while changing the way it relates to the customer. The customer, in turn, may change behavior when searching for information and consuming tourism products/services to enjoy all the advantages that smart tourism promises.

### Impacts on the tourist

Smart tourism and its components impact the tourist in several ways, including the experience, satisfaction, behavior, and decision-making (Mehraliyev et al., 2020). Smart tourism can enhance the tourist experience by fostering greater engagement and interaction with and between tourists, and promoting the exchange of experiences (Buonincontri & Micera, 2016). For example, today it is easy for tourists to share their travel experience in many different ways: they can post photos and videos of their trip, or write a review to share information with their family and friends on social media. Geocaching is another example that shows how the experiences of younger tourists can be enhanced by diversifying and gamifying the activities they enjoy in a destination (Skinner et al., 2018).

Smart tourism facilitates tourist planning and decision-making before and during travel, e.g., "smart travel guides" that allow interaction between content and the tourist in a highly dynamic way (Chuang, 2020; Ruíz et al., 2017). By using smart technologies, tourists are less constrained by the arrangements they make before they leave on a trip, as destination information is readily available wherever they are during their trip. Moreover, tourists can obtain relevant information for their trip through websites or mobile applications based on their previous behavior, consumption patterns, and browsing records on the networks and the internet. This allows tourists to adapt their consumption throughout the trip, as their needs change or they discover new information on an on-going basis (Y. Li et al., 2017). The result is that tourists can end up becoming much more unpredictable consumers than before. One consequence of the above is that the efforts made by tourism firms to improve tourist satisfaction (through smart technologies and process reengineering) are increasing day by day, for example, by implementing automatic billing processes in self-service restaurants through the use of neural networks (Aguilar et al., 2018), by installing lighting control systems in hotel rooms to improve the quality of service (Feng et al., 2017), by developing dynamic software tools that allow the characteristics of hotel rooms to be adjusted according to the activities carried out by the customer (Cetina et al., 2013), or by promoting the use of virtual and augmented reality systems to experience tourist attractions in a more enjoyable way.

Last but not least, another important impact is related to consumer preferences when it comes to adopting smart technologies and smart information. Although this is an area that needs more research, there are some studies that highlight that ease of use and perceived usefulness are key factors influencing consumer attitudes towards smart technologies (Bae et al., 2017; Chung et al., 2015). Other factors, such as informativeness, interactivity, accessibility, and personalization are also highly relevant (Chung & Koo, 2015). In conclusion, it is important that tourism firms are aware of the factors that affect their customers and users when adopting smart tourism, and that they understand how tourists prefer to enjoy tourism experiences (e.g., "more smart", "less smart"). This is a field of knowledge that will gradually gain in importance and that is very likely to change the way in which tourism firms segment and interact with customers.

## Criticism of Smart Tourism

The tacit consensus reached among most academics, consultants, and leaders from the technology industry reveals an overly optimistic view of the effects of smart tourism, both for tourism firms and tourists. It often happens that many of the benefits that are continually pointed out by industry and academia are poorly supported by empirical data, which advises owners and managers to be cautious in trusting the promised benefits and the ease of obtaining them. This does not mean that owners and managers should distrust smart tourism recommendations by default, but rather that many slogans have been widely criticized due to the lack of studies to support them.

The first criticism has to do with the limited empirical evidence that academic and industry research has provided in recent years on the benefits of smart tourism, beyond highly specific case studies. In addition, the little practical research that has been carried out in this respect has provided very limited theoretical advances, which prevents establishing broad generalizations that cover all tourism activities and firms, since they have no validity beyond the isolated case studies investigated.

A second criticism is that the study on smart tourism has been carried out on very few fronts (e.g., destinations, specific smart technologies, the tourist experience, combined effects with other technologies). This means that there is neither a solid body of empirical evidence nor an elaborate theoretical framework that is exclusive to tourism and on which we can base conclusions about the real impacts that smart tourism has on tourism firms. This lack of understanding about the business perspective of smart tourism means that the answer to the question of how smart tourism actually affects tourism firms, and what factors limit its adoption, remains open.

The third criticism relates to the lack of understanding about tourist preferences, as it is still hard to know for sure which aspects of smart tourism are most (or least) preferred by tourists, or which segments of tourists are those most/least likely to choose smart tourism. Ultimately, what owners and managers should note is that there is a general absence of solidly grounded discourse on the impacts and consequences of smart tourism. This leads us to point out the significant limitations that exist in determining the drivers, drawbacks, and costs associated with implementing a smart tourism strategy in the tourism firm. Therefore, business owners and managers should take a critical standpoint, aware that not all the effects of the Smart Revolution are positive for the tourism firm. There is still a long way to go in identifying, measuring, and mitigating the negative effects and drawbacks of smart tourism in real life, and only more and better empirical work will help clarify the pros and cons.

### e-Lienation

One of the most studied negative aspects of smart tourism is that of e-lienation, which highlights the negative impact that ICTs have on the consumer's own experience (Tribe & Mkono, 2017). According to these authors, there is sufficient evidence to affirm that the use of smart technologies can promote isolation and addiction on the part of the consumer, as well as self-marginalization, loss of routines, and even the breaking of social ties and misconduct when complying with rules, uses, and customs. These behavioral alterations that can affect the consumer, both in an individual and social context, can even pose a threat to the restorative purpose sought by the tourist with a trip or vacation. Circumstances like this are more frequent than most think and they happen when tourists have a hard time disconnecting from their work obligations and take their computer and mobile devices on a getaway or on vacation, or when they feel obsessed with chatting and sending emails to friends and family at home, or keep tweeting or posting on Facebook and Instagram to show the world their "perfect self in the perfect place".

These behaviors are a reflection of e-lienation and can negatively influence the quest for authenticity of tourist experiences to the point of reinforcing anxiety, narcissism, and addiction. Of course, not all the uses that tourists make of ICT have to end in e-lienation, but it seems evident that the more we use ICT in our leisure and tourism time, the more opportunities arise to suffer from e-lienation (Tribe & Mkono, 2017). Business owners and managers need to be aware of these circumstances and the negativities they can bring to the tourism experience. This means being able to identify the critical factors that can lead to e-lineation before deciding to undertake a transformation strategy that involves the implementation of smart technologies and organizational change.

## Discussion Questions

-   What kind of problems is smart tourism helping to solve related to your tasks and responsibilities? What types of real problems of tourism firms are the most suitable to be addressed by smart tourism?

-   What is the balance between the costs and benefits of implementing a smart transformation strategy in the tourism firm?

-   What factors specific to tourism (and non-tourism) are contributing most to making the term smart a buzzword?

-   How do business owners and managers in your local area conceptualize smart tourism? To what extent does it coincide with or differ from the definition of smart tourism provided in this chapter?

-   What benefits apart from those specifically examined in this chapter does smart tourism have?

-   Is smart tourism for all tourism firms? Are there certain types of tourism firms (depending on size, location, business model, etc.) that are more likely to succeed with a smart transformation strategy?

-   What negative effects other than those described in this chapter can smart tourism have for the tourism firm?
