# Introduction

Tourism business owners and managers are at a critical tipping point. The business environment in which they operate has not only become intrinsically more competitive and complex but keeping up with innovation and disruption, while still managing day-to-day operations effectively and efficiently, has become a real challenge. With the advent of the 21st century, people and organizations have realized that we all live in an increasingly VUCA world, an acronym that all tourism professionals should be familiar with and that describes the increasingly volatile, uncertain, complex, and ambiguous world in which we live. Scholars and professionals now accept that firms are dynamic in nature, that change can happen at any time and come from anywhere, and that we have lost the ability to predict what is going to happen next in business and in our lives. Furthermore, the speed at which change occurs is so high that it is extremely difficult to make the right decision about the direction that our organizations should take. In this context, the unexpected is king and the rules that govern how firms operate are unequivocally different.

There are many reasons that can help us understand how we have arrived at this stage, including globalization, digitalization, geopolitical balances, as well as countless social and economic interconnections that operate at the macro and micro levels. Notwithstanding the foregoing, there is still a key factor that is driving tourism firms towards this new era of rapid and accelerating change: technology. Advances in information and communication technologies (ICTs) are raising consumer expectations and disrupting tourism ecosystems at a breakneck pace, to the point where a new generation of non-traditional data- and technology-focused competitors are driving a radical transformation of tourism. Technology is now embedded in the things we normally see and touch, but also in the things we don't perceive (e.g., factory production lines, supply and delivery chains, etc.) having become ubiquitous. In fact, many analysts believe that we are already immersed in the Fourth Industrial Revolution, a new era characterized by cyber-physical systems that are creating radical breakthroughs in various fields of society at an extraordinary fast speed (Schwab, 2017).

See @knuth84 for additional discussion of literate programming.

```{r}
1 + 1
```
