---
title: "Smart Leadership"
---

Smart transformation is best managed when there are smart leaders who recognize the needs of the organization and are willing to guide it on the right direction. Leadership is a critical capability that smart firms need in order to address all the transformational changes required to build a data-driven culture in the organization. Furthermore, leadership is a critical competency to embrace Big Data throughout the organization and bring the benefits of data science to fruition (Unhelkar, 2017).

Paradoxically, as firms increase their reliance on data and algorithms for decision-making and the automation of routine, information-intensive tasks increases, so does the importance of interpersonal leadership skills between owners and managers. Smart firms need good leaders with a vision not only to improve some processes and make them work better, but to profoundly transform the organization around three key areas: customer experience, operational processes, and new business models (Kiron, 2017). What is at stake is not only how to manage data and implement data-driven technologies to get the most out of it, but to give the organization a new impetus that makes it stronger and more competitive. In the end, it is about making the tourism firm work in a more Agile way and be able to respond to the customer needs faster and precisely.

Today every smart leader understands that the world of technology and data is changing very rapidly, and they take very seriously how smart things are changing the way consumers and business behave. They are aware that Big Data, analytics, artificial intelligence (AI) and the Internet of Things (IoT) technologies are becoming ubiquitous and that a silent but powerful (Smart) Revolution is taking place that affects the management of organizations. Smart leaders have a clear mission: they work hard to make their organizations develop a smart mindset and be ready to respond to the disruptions caused by the use of smart technologies.

The huge demand for change brought about by the Smart Revolution makes it inevitable for organizations to build a greater capacity for innovation and transformation, and this fundamentally affects leadership functions. In other words, it is simply not possible for the firm's transformation process to unfold and the firm to be reborn as a smart organization without renewed leadership. It is the job of leaders to understand how transformation affects existing organizations and how they can be threatened if they do not change, and become flexible, and do not reorganize towards increasingly digital and smart business models (Burchardt & Maisch, 2019; Earley, 2014).

## Leaders and Smartization

In the last few years, business firms have gone from a lack of information as one of the main reasons for uncertainty to an overabundance of data that can now be quickly and affordably transformed into information and knowledge. Data offers organizations the potential to reduce risks in decision-making by enabling business leaders to access richer, more holistic insights into the challenges they face (Filatotchev & Nakajima, 2010). This means leaders will need to focus on Big Data and analytics skills and foster a data-driven decisionmaking culture with the right technologies to support it. In addition, the use of data by tourism firms strengthens organizational resilience, understood as the organization's ability to anticipate disruptions, adapt to disturbing events, and create lasting value in a turbulent environment (Kaivo-Oja et al., 2015).

The use of data and the possibility to create value for the organization is something that does not happen by chance or accident, nor is it something that can be easily achieved in a few weeks or months. Moreover, firms are unlikely to be more successful simply because they have access to good data. Becoming a smart organization requires well-defined leadership that shares a clear vision and goals and activates flexible talent management practices and an organizational culture that puts data at the center of the organization (Shamim et al., 2019). Smart leaders encourage the use of data and successfully guide the organization to extract value from Big Data and analytics, making it easier for data applications to consistently deliver their benefits to the organization. This requires smart organizational decisions and the commitment of visionary leaders who inspire a new data-centric culture by becoming role models in the use of data and with the skills and abilities to overcome the technical and organizational obstacles that arise when creating value from data (Brinch et al., 2021; Hume & West, 2020).

Smart firms' leaders view data as a key asset that all employees should have access to and know how to use. They believe that data and analytics can greatly enhance the organization's ability to innovate and respond to changing customer needs and preferences (Kiron, 2017) and ultimately view data as an asset key to a firm's competitive advantage. Smart leaders stand out because they emphasize the systematic use of data throughout the organization not only to address operational or tactical problems, or to create more compelling reports, but also to integrate data into decision-making processes that lead to the allocation of resources, put new products and services on the market, or promote changes in business models. To achieve their goals, smart leaders do not hesitate to build a flexible and decentralized organizational structure in which all its members collaborate and share their knowledge to extract value from data (Zeng & Glaister, 2018).

Smart leaders know how to connect the "big picture" questions that every business owner and manager asks, with the more specific, low-level questions that machines can answer, thereby reconciling machine-generated models with the nuances of human preferences (Andersen et al., 2018). Smart leaders are aware of the benefits of using data, but also know its limitations and adapt the role of data when formulating strategies and adjusting the expectations of data users in the organization. They never fail to communicate to the entire organization when data analytics reveals something insightful, because when the organization shares the insights generated by the data, it reinforces the importance and usefulness of the data and encourages people to pursue this line.

## New Leadership Profiles

One of the factors on which the success of smart transformation depends is, in addition to technology, the type of leadership and the strategies deployed by the leaders in the organization (Bala, 2018). Becoming a smart firm requires significant financial, human, and technological resources, but especially leaders who possess a balanced mix of skills, attitudes, and behaviors that guide the organization towards "smartness".

Organizations must ensure that they have the right people in place to create a culture that makes the smart firm a reality. They need people who are operationally responsible for the firm's smart strategy and who can implement management practices that prioritize change initiatives and transformation projects aligned with the business strategy (Matt et al., 2015). This does not mean that leaders need to be experts in every single technology and practice that the firm implements, but they do need to be digitally fluent and have a strong understanding of the value of the investments needed to guide the firm's future growth.

The debate on who should lead the smart transformation of the firm is open in the academic and professional communities, and there is no consensus on who is the best candidate. In addition to the Chief Executive Officer (CEO) and the Chief Information Officer (CIO), who have traditionally played the leading role in the firm's IT transformation and innovation projects, new roles are emerging as a result of digitalization, among which are the Chief Digital Officer (CDO) and the Chief Transformation Officer (CTO). Some of the differences between CIOs and CDOs are that CDOs are not responsible for running IT within the firm, nor are they in charge of data (which is increasingly the responsibility of Chief Data Officers), rather they are change agents working in close collaboration with partners to create digital solutions that transform business models and processes. While CIOs have traditionally focused on back-office tasks and ensuring IT service levels, CDOs focus more on the customer and look at the applied side of business technologies. It remains to be seen what kind of interface is best between CIOs and CDOs in a context where both roles coexist, and whether the CIO's role will be neutral or have some leadership role in the transformation process (Brown & Brown, 2019).

However, it seems that at the moment these new roles are being created in many organizations with a limited time frame in mind, suggesting that organizations think that digital or smart transformation is going to take a limited amount of time and that at some point sooner rather than later these roles will no longer be needed. This belief may be even more widespread in SMEs, where there is often not as much variety in leadership roles as in large firms, and where it is common for the CEO or owner of the firm to be responsible for organizational transformation. This should not be a problem, after all it is about having a well-defined and clearly assigned role in the organization that exercises responsibility and leadership over the transformation process (Hönigsberg & Dinter, 2019). Once assigned a leadership role, the SME leaders will have to define the roles and responsibilities of the rest of the managers and employees of the organization to respond to the needs that arise from smart transformation.

Whoever ultimately takes the lead, it is critical that they focus on ensuring that the firm's technologies are used appropriately and remain aligned with the organization's business objectives, leveraging concrete smart strategies and fostering close collaboration between business and IT. Nevertheless, due to the expected long duration of the smart transformation processes, it is perhaps best that leadership is performed by a single role over time and that the responsibilities of the leader are agreed upon jointly with the firm's senior management from the outset, thus overcoming the usual resistance coming from the different areas of the organization. The above does not mean that in some firms the role of leader is not performed by a single role, but by several roles that share different responsibilities, for example, the CIO and the CDO.

## Smart Leaders' Skills

Smart transformation has a strong impact on the leadership style of organizations. Taking the lead in firms that rely on data and knowledge to make decisions requires skills that differ substantially from conventional leadership skills focused on intuition and personal experience. Therefore, smart leaders need a new set of skills to tackle the deep transformation process that their organizations are about to undertake.

Smartization is not driven by technology. Deploying reliable and robust IT data systems is yet another component of the smart transformation process. It is not enough for leaders to be tech savvy, but they must also have extensive management skills to integrate IT processes and tools with business processes, and be able to recognize possible areas of synergy and friction between the two (Hanelt et al., 2021; Morabito, 2015). Just as important is that leaders focus their attention on multiple perspectives, such as customer centricity, systems that are flexible and easy to use, and information that is accessible and can be rapidly transformed into insights by the members of the organization. Without this mixed approach, it will be difficult for the organization to harness the business value of data centricity and smartness.

Smart leaders do not need to master all the technologies that are going to be needed, but they do need to be bilingual in both the "human" language and the language of machines, or put another way they must be able to communicate and work effectively with smart machines and with smart humans (Andersen et al., 2018). It is also vital that smart leaders recognize data as a critical organizational asset, thereby establishing a hierarchy of roles accordingly (e.g., data scientists, data analysts, project managers, business analysts) and locating decision-making according to the strategic nature of the data. All of these are essential skills for the leader to build a culture based on data, whose implementation in the smart organization will facilitate achieving an adequate return on investments in talent (Hupperz et al., 2021).

### Communication and interpersonal skills

The smart transformation of tourism firms requires the active participation of all affected stakeholders. This makes communication skills paramount to ensure that they are all aware of the direction the organization will take and what future they can aspire to. Furthermore, smart leaders know that making people embrace change and share a vision is not easy. People will prefer the stability of the status quo to the uncertainty that comes with change. That is why it is very important that smart leaders stand out for their interpersonal and communication skills and know how to deal with resistance that may appear.

Engaging active followers to transform the organization implies convincing employees of all the good that awaits them if, working together, they manage to bring the vision into action. Initially, the leader's vision will be nothing more than an inspiring and well-crafted promise to attract the interest of others. But nice words are not enough -- soon the leader will have to demonstrate the benefits of the vision and build trust with others, otherwise no one will be willing to work hard for years to come (Friedman, 2020).

Owners and managers must be aware that some ethical considerations may arise when engaging followers. For this reason, it is highly recommended that the leader presents herself not only as someone focused on the financial performance of the firm, but as an ethically responsible and authentic leader, communicative and inclusive, and concerned with the sustainability of the firm and the environment. Once trust among followers is achieved, the leader should be able to harness the creativity, knowledge, and collective wisdom of their co-workers to achieve her vision. Unfortunately, keeping this process on track is often hampered in the tourism firm due to the high proportion of seasonal and low-skilled workers, who pose an even greater challenge to the smart leader's abilities to orchestrate workforce motivation.

Not least important is that smart leaders have the skills to collaborate with external partners and suppliers. Being innovative and able to rapidly create new products and services when customer preferences change requires strong coordination skills both at the organizational level and with partners. This becomes even more apparent when the tourism firm is committed to open innovation as a model to foster collaboration with external actors seeking to provide the firm with more opportunities to exchange knowledge and deliver innovative responses. Team culture also plays an important role in maintaining knowledge exchanges and innovation performance in the smart tourism firm. Smart leaders will strive to shape this culture by acting as facilitators, mentors, and role models to others (Pesonen, 2020), mastering the double language of technology and business to provide the organization with valuable tools with which to increase the potential for knowledge exchange and collaboration. The construction of open and collaborative spaces that favor innovation will be greatly facilitated by the implementation of smart technologies, in the same way that these spaces will encourage the development of smart technologies, thus creating synergies between the two.

### Transformational awareness

Given that the context of the tourism firm is complex and constantly changing, leaders must also develop transformational awareness in relation to the organization's processes and strategies (Hanelt et al., 2021). Smart leaders not only need to know how to sense and respond to changes within competitive dynamics, but they also need to be aware of the complex web of variables that influence the process of business transformation internally and how these are intertwined with the changes that occur in the market, the consumer, and technologies. This means that leaders must draw on the broadest and most diverse data sources and perspectives possible to fully assess the contextual conditions of the firm and incorporate complexity into their decisions. New tools and applications (e.g., Agile methodologies, design thinking) are constantly emerging to help leaders manage these new needs and support smart leadership.

Transformational awareness is closely related to the ability of smart leaders to accelerate organizational transformation strategies. This entails the ability to always be open to experimenting with new processes and conceiving innovative products and services based on available internal and external resources (Brown & Brown, 2019; Hanelt et al., 2021). The smart leader is constantly learning from customers and what is happening in the marketplace, driving continuous innovation and facilitating organizational adaptation, rather than spending her time planning and performing ex ante analysis that are of little or no use in a highly dynamic business ecosystem where opportunities and competitive advantages are fleeting.

## Benefits of Smart Leadership

Having competent leaders is something that can provide significant benefits in the context of smart transformation and the development of a data-driven culture in the tourism firm. Below are some of the most significant benefits that the organization can gain in return (Fig. 20.1).

-   **Increased customer focus,** which can translate into a better user experience and higher customer satisfaction as the smart organization consistently generates more insightful knowledge about customers.

-   **Greater agility to deliver products and services,** through the development of an open mindset that leads the members of the firm to collaborate with partners and external actors and to engage in a culture of open innovation and continuous exchange of knowledge. By fostering more open and productive relationships, the firm will be in a better position to offer more innovative products and services and expand in the market.

-   **Increased process optimization,** as smart leaders emphasize the need to embed new digital and data-driven technologies into key business processes and automate repetitive processes, allowing the organization to run in a more agile and decentralized mode.

-   **Greater employee satisfaction,** since they are an important part of the leader's vision and should know what can be expected from their effort. Additionally, as employees are encouraged to participate in the process of defining and implementing technologies that meet their daily needs, they feel more motivated and prone to make their own decisions about how to organize their work and deliver benefits for the organization.

-   **Greater focus on the social benefits obtained from the firm's actions,** since smart leaders have access to more information and knowledge of the environment and analyze more complex perspectives than conventional leaders. This in turn enables smart leaders to integrate broader perspectives into their decisions (e.g., insights, metrics, reports) and adopt more community-and environment-focused strategies and behaviors.

## Smart Leaders and SMEs

Very often leaders in SMEs, especially those with a family structure, become a barrier for the organization to transform, especially when leaders are risk averse, which can end up affecting the organization's capacity for innovation and the development of a culture focused on data and knowledge. The personal qualities of leaders, their sociodemographic attributes, and even their educational level are factors that can influence risk appetite and affect the decision-making of owners and managers (Zapata et al., 2020).

In general, organizations with low risk-taking capacity are less likely to be innovative, with leaders often deciding what kinds of risks the organization can take (Pesonen, 2020). On many occasions, leadership in SMEs is highly centralized around the figure of the owner of the firm, and it is rare that the final decisions are made by other people or teams (Trenkle, 2019). This means that in SMEs, power is often highly concentrated in a single person who is the one who makes most of the important business decisions and has the decisive role in transformation decisions.

In addition, leadership in SMEs often suffers from a poor definition of responsibilities, a wrong vision of the future, or even an unwillingness to take risks, all of which hinder the potential competitive development of the firm. Very often SMEs remain focused on the idea of managing their daily operations instead of considering the organizational implications of transformation, so redefining leadership in the firm is not a priority for them. This may explain why many tourism SMEs continue to struggle with their digital transformation initiatives, indicating a lack of leadership in this key area (Hönigsberg & Dinter, 2019).

## Agile Leaders

The leadership styles that have been working until now are no longer valid to tackle the challenges of the Smart Revolution. Simply put, leadership styles prior to the Smart Revolution were not designed to embrace data-driven technological breakthroughs, nor were they equipped to effectively manage the ultra-fast pace at which society and firms are transforming and technological change is occurring. This indicates that the landscape of leadership in business organizations is unequivocally changing forever.

In the highly uncertain and complex environment in which tourism firms operate today, it is quite difficult, if not impossible, for leaders to accurately predict potential future opportunities and threats. Gone is the idea of the "wise" leader on which organizations used to rely to devise the appropriate responses to challenges, and find solutions to all business problems. Nowadays, organizations struggle to learn around the clock and make change flow naturally and fast throughout the organization. It is thus not surprising that the role of the leader in business organizations is transforming to accommodate a more "agile" style and that "agile smart leaders" are emerging strongly.

Agile leaders apply the values and principles of Agile management to their own leadership style. They seek to mobilize the organization towards higher levels of organizational agility and orchestrate its resources for an effective transition in that direction. They are visionaries and create the right conditions so that the members of the organization are motivated and willing to seize the opportunities that come their way, sharing their knowledge and creativity along the way.

Agile leaders are transformational leaders, meaning they focus all their efforts on pursuing the crucial mission of driving profound change in the organization. They tap into the hopes and aspirations of organization members to gain their support and commitment to work together towards a high-flying vision (Gagel, 2017). As transformational leaders, they leverage followers to transcend their personal or departmental interests through inspiration, motivation, individual recognition, and intellectual stimulation, making their interests stay aligned with those of the leader. In a way, transformational leaders turn followers into disciples of change, so that change can permeate every corner of the organization.

Agile leaders do not lead by authority, but by example with open-mindedness, self-discipline, continuous self-evaluation, creativity, and capacity for innovation, thus being able to lead effectively in conditions that can change quickly and unpredictably. Agile leaders seek to eliminate bureaucratic constraints within the organization, and do not hesitate to tear down the silos that fuel internal conflict and foster subcultures that protect the interests of a few areas and departments of the firm. Instead of silos, they inspire people to become agents of change and strive to implement a culture of openness and creativity in which areas and departments openly share information and knowledge, while encouraging innovation and continuous experimentation (Attar & Abdul-Kareem, 2020; Forbes Coaches Council, 2018). Furthermore, they are aware of the importance of using broader and more diverse perspectives to address business problems and deliver solutions swiftly. This makes Agile leaders develop a keen eye to realize when something is not working and when the time comes to change things.

How can smart firms identify Agile leaders? Although no one has been a leader in a smart world until now, it is doubtful that the same criteria used in traditional organizations to recognize leaders (i.e., demonstrated leadership potential, proven track record) will continue to be useful for Agile leaders. HR departments will need a clear understanding of what Agile leadership is all about, which is key to unequivocally identifying Agile leaders, as well as promoting and scaling a true Agile organizational culture. Furthermore, owners and managers hiring Agile leaders should focus on recognizing Agile attributes, such as an innovation-oriented mindset, a passion for continuous learning, adaptability, and an entrepreneurial spirit. As can be seen, all these characteristics of Agile leaders are substantially different from the "wise" leader stereotype who used to rule conventional business organizations for decades by relying on their own knowledge, expertise, and the guts to make decisions based on instinct.

## Discussion Questions

-   What type of leadership style predominates in tourism firms? What factors reinforce this type of leadership?

-   How do cultural differences and the size of the organization influence the type of leadership practiced in tourism firms?

-   Who typically plays a leadership role in tourism firms? Is leadership exercised by one or several roles? What kind of roles are the most common and why?

-   Are today's tourism firms leaders well prepared to face the challenges of smart transformation? Why? If not, what would it take for leaders to be well prepared?

-   Are tourism firms sensitive to the emergence of new leadership roles as a result of the Smart Revolution? What new roles have consolidated?

-   What skills of the tourism business leader are different from business leaders in other industries? What are the reasons for these peculiarities?

-   What differences are there between an Agile leader and another who is not? Is the Agile leadership style applicable to tourism SMEs?
