---
title: "The Need for This Book"
---

The increasingly influential and sophisticated field of transformation and technology uses a specialized terminology that is often difficult for non-specialists to understand. Stop for a moment and think about all those acronyms, abbreviations, and jargon that are constantly heard and read, such as IoT, AI, Analytics, Big Data, or 5G. It is often difficult to know what they really mean. For many of the owners and managers who are approaching this growing field of knowledge and practice for the first time, or who are still at a beginning level, the language itself becomes a barrier to understanding the key issues. This not only happens with those who do not have prior technical training, but also with the most experienced practitioners due to constant innovation and the new practices and technologies that emerge every day.

Despite these obvious difficulties, a large part of the reference books and training available on the subject are highly technical or academic and focus primarily on information technology or systems management. By doing so, most authors and trainers miss out on helping business owners and managers understand the terminology and fail to guide them through the process of business transformation and organizational improvement. In addition, owners and managers have grown accustomed to hearing about the phenomenal benefits that some "magic" technologies are bringing to companies, consumers, and society in general, but few people tell them about the failures and bad experiences of those who have tried it before and have not experienced the expected returns despite having invested large amounts of time and money in the process.

To fill this gap the book provides readers with an up-to-date framework to understand the key concepts, technologies, and management practices that are crucial to tackle the challenges of smartization and the underlying organizational transformation. Always using an eminently practical approach attached to reality and an perspective independent of the technology industry and consultants, the book highlights both the good things that smart technologies can bring to the tourism firm and the not-so-good things. Special attention is also devoted to the barriers and limitations that owners and managers will encounter in the transformation process and the mistakes that should be avoided.

The book delves into the world of digital and smart technologies from a managerial perspective, keeping technical details to the minimum necessary to facilitate understanding of concepts and ideas. It also highlights the opportunities that may arise from the implementation of more than ten key smart technologies, including Big Data, analytics, artificial intelligence, Internet of Things, augmented and virtual reality, etc. and how they can shape the tourism firm's strategy and operations. Furthermore, the book emphasizes the crucial role that people and organizational leaders play in harnessing smart technologies and enabling the organization to pursue efficiency, improve the tourism experience, and gain agility for sustainable competitive advantage. To conclude, an implementation framework that draws on best practices is provided that owners and managers can use as a roadmap to take the first steps in smart transformation and start reaping its benefits. Finally, the author offers his personal vision of what could be the next wave of innovation and disruption that is yet to come in the field of smartization and transformation and that could mark the future of tourism firms.

A variety of discussion questions are provided throughout the chapters of the book to allow current and future business leaders to engage with the concepts and internalize the importance of the ideas presented. In cases where the book is used by groups of undergraduate or graduate students, this material can help stimulate class discussion about the relevance of the ideas presented by the instructor and thus achieve a more collaborative and experiential learning.

After reading the book, anyone running a tourism SME should have a broader understanding of the relationships between organizational transformation, smart technologies, and the management practices that can unlock the wealth of opportunities that they offer. Whoever reads the book carefully should also be prepared to set a plan that optimizes the firm's strategy and its operations in the context of the Smart Revolution and lead the organization towards the technological developments that are to come. Those readers will also understand that a successful smart transformation process does not depend solely on technology, but that the role that leadership and people play in mobilizing the organization and aligning it with common goals is essential. Ultimately, owners and managers who read the book will be more confident the next time they find themselves in a position to lead a transformation project within their organization or are asked by senior management to lend their support on transformation initiatives. They will surely be better equipped than others to serve as agents of change and contribute to increasing the firm's performance by keeping up with the accelerated pace of change and innovation that characterizes the era of smart tourism.
