---
title: "Part 1: Introduction to Smart Firms"
---

Part 1 of the book introduces the key concepts and ideas that are shaping the Smart Revolution in tourism, as the by-product of a longstanding process of deep change that has been impacting the business ecosystem, consumers, and tourism firms for years. Over the next four chapters, business owners and managers are going to learn about the main components that qualify the Smart Revolution as a substantial step forward in creating innovative opportunities and addressing new challenges for tourism management, making clear the main drivers that will guide the transformation of their organizations in the coming years. Emphasis has been placed on using clear and concise language that allows business leaders to get past the confusion surrounding the smartization process once and for all. The aim is to provide the reader with an up-to-date stock of knowledge about the far-reaching consequences that the Smart Revolution is having on tourism firms, stressing the need to address this process through intense data-centric organizational transformation. Given the complexity and length of the topics covered, an approach focused more on breadth than on depth has been chosen in which those factors that are essential to consolidate sustainable competitive advantages and reap the benefits of the Smart Revolution are highlighted.
