---
title: "Part 4: What's Next"
---

Readers who have reached this part of the book have a broad perspective of what the Smart Revolution is all about, the technologies that are making it possible, and the management practices that are necessary to successfully tackle the smart transformation process. But where to start? What are the first steps an owner or manager should take, and in what direction, to build a smart organization? What's more, now that the reader understands the true magnitude of the challenge ahead for the tourism firm, what's next? Are such radical changes going to continue in the future? How can my organization be prepared for the ongoing challenge? Although the Smart Revolution has just begun and there is still not enough expertise and models of good practice to guide owners and managers on what works and what does not, in this part of the book the author ventures to suggest a framework of action that can be used to undertake the transition from a conventional firm to a smart one. Furthermore, those technological and non-technological trends that are very likely to shape the future capabilities of tourism firms are examined, along with their potential to create and sustain competitive advantage.
