---
title: "Part 3: Management Practices"
---

One of the biggest concerns of owners and managers of tourism firms, and their stakeholders is how to successfully tackle the transformation process towards a smart organization. The answer is clear: the conventional management practices used until this point are no longer useful for a world dominated by data and the high speed at which things happen, so it is necessary for tourism firms to implement new practices according to the environment in which they operate today. Tourism firms need smart leaders with a vision that everyone can buy into and which becomes a roadmap that guides the organization's efforts and culture toward change. A new culture is needed that motivates the organization to be agile, innovative, and to act swiftly whenever customer preferences change or the environment transforms. This chapter provides owners and managers with a synthesis of the key management practices and skills that should help them successfully drive organizational smart transformation. By learning about these practices, business leaders will be able to assess how close their organization is to realizing the benefits pledged by the Smart Revolution, as well as reflect on the strategic nature of smart transformation and the need to set an agenda for change.
