# References {.unnumbered}

::: {#refs}
Abbate, T., & Souca, M.L. (2013). Open innovation and online intermediaries: A review of theory and its implications for tourism. Proceedings of the International Conference Marketing -- From Information to Decision, 6, 9--22. http://search.ebscohost.com/login.aspx?direct=true&db=bth&AN=93425296&site=ehost-live (accessed 23 June 2022).

Accenture. (2017). The future of food: New realities for the industry. In FMI. The Voice of Food Retail. https://www.fmi.org/docs/default-source/midwinter-2018/kurt-salmon-and-fmifuture-of-food-report-(2).pdf?sfvrsn=c35c796e_0 (accessed 12 April 2022).

Accenture. (2020). Busting the Myths of Agile: How the pandemic accelerated the adoption of the intelligent operating model (August).https://www.accenture.com/\_acnmedia/PDF-132/

Accenture-COVID-19-Busting-MythsAgile-transformation.pdf (accessed 23 June 2022).

Adamopoulou, E., & Moussiades, L. (2020). Chatbots: History, technology, and applications. Machine Learning with Applications, 2(July), 100006. https://doi.org/10.1016/j.mlwa.2020.100006

Adukaite, A., Reimann, A.M., Marchiori, E., & Cantoni, L. (2013). Hotel mobile apps. The
case of 4 and 5 star hotels in European German-speaking countries. In Information and
Communication Technologies in Tourism 2014 (pp. 45--57). Springer.

Aguilar, E., Remeseiro, B., Bolaños, M., & Radeva, P. (2018). Grab, pay, and eat: Semantic food detection for smart restaurants. IEEE Transactions on Multimedia, 20(12), 3266--3275.

Akkaya, B., & Tabak, A. (2020). The link between organizational agility and leadership: A research in science parks. Academy of Strategic Management Journal, 19(1), 1--17.

Alahmari, A., & Duncan, B. (2020). Cybersecurity risk management in small and medium-sized enterprises: A systematic review of recent evidence. 2020 International Conference on Cyber Situational Awareness, Data Analytics and Assessment, Cyber SA 2020, June. https://doi.org/10.1109/CyberSA49311.2020.9139638

Alberts, C., Dorofee, A., Stevens, J., & Woody, C. (2003). Introduction to the OCTAVE Approach. In Networked Systems Survivability Program. Carnegie Mellon Sofware Engineering Institute. https://www.fmi.org/docs/default-source/midwinter-2018/kurt-salmon-and-fmi-future-of-food-report-(2).pdf (accessed 30 July 2022).

Ambler, S. W., & Lines, M. (2016). The disciplined agile process decision framework. In International Conference on Software Quality (pp. 3--14). https://doi.org/10.1007/978-3-319-27033-3_1

Andersen, E., Johnson, J. C., Kolbjørnsrud, V., & Sannes, R. (2018). The data-driven organization: Intelligence at SCALE. In A. Sasson (Ed.), At the Forefront, Looking Ahead (pp. 23–42). Scandinavian University Press.

Antoniadis, I., Spinthiropoulos, K., & Kontsas, S. (2020). Blockchain applications in tourism and tourism marketing: A short review. In A. Kavoura, E. Kefallonitis, & P. Theodoridis (Eds.), Strategic Innovative Marketing and Tourism (pp. 375–384). Springer International Publishing. https://doi.org/10.1007/978-3-030-36126-6_41

Ashton, K. (2009). That “internet of things” thing. RFID Journal, 22(7), 97–114. Atlam, H.F., Walters, R.J., & Wills, G.B. (2018). Fog computing and the Internet of Things: A review. Big Data and Cognitive Computing, 2(2), 10.

Attar, M., & Abdul-Kareem, A. (2020). The role of agile leadership in organisational agility. In B. Akkaya (Ed.), Agile Business Leadership Methods for Industry 4.0. Emerald Publishing Limited. https://doi.org/10.1108/978-1-80043-380-920201011

Attaran, M. (2017). The Internet of Things: Limitless opportunities for business and society. Journal of Strategic Innovation and Sustainability, 12(1), 11. AWS. (2022). What is a data lake? https://aws.amazon.com/es/big-data/what-is-a-data-lake/ (accessed 23 June 2022).

Azuma, R.T. (1997). A survey of augmented reality. Presence: Teleoperators & Virtual
Environments, 6(4), 355–385. 

Baculard, L.-P., Colombani, L., Flam, V., Lancry, O., & Spaulding, E. (2017). Orchestrating a Successful Digital Transformation. Bain & Company. https://www.bain.com/contentassets/dd440ca288d34c16ba8cd3ab6ef69a04/bain_brief_orchestrating_a_successful_digital_transformation.pdf (accessed 30 July 2022).

Bae, S.J., Lee, H., Suh, E.-K., & Suh, K.-S. (2017). Shared experience in pretrip and experience sharing in posttrip: A survey of Airbnb users. Information & Management, 54(6), 714–727.

Bageac, D., Reynaud, E., Fortun-Auad, S., & Thi, N.T.V. (2020). Organizational aspects of open innovation. Institut de Socio-Économie Des Entreprises et Des Organisations (Écully,
Rhône). Recherches en Sciences de Gestion, 138, 41–68. https://www.proquest.com/scholarly-journals/organizational-aspects-open-innovation/docview/2444524837/se-2?accountid=14475 (accessed 23 June 2022).

Bainbridge, A. (2018). Autonomous Vehicles & Auto-Tours. What is an auto-tour and how will autonomous vehcicles impact tours, attractions & cities? http://www.destinationcto.com/docs/AutoTour.pdf (accessed 15 April 2022).

Bala, M. (2018). Digital transformation: Review of concept, digital framework, and challenges. In V.P. Gupta and D. Bansal (Eds.), Theoretical and Empirical Development in Management and IT (pp. 133–152). Swaranjali Publications.

Barkan, M., & Tapliashvili, N. (2018). Cryptocurrency use in medical tourism. Scientific and Practical Cyber Security Journal (SPCSJ), 2(4), 104–110.

Bashkirova, O. (2016). Knowledge-Based Business-Model (The Concept of Smart Organization). https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2842509 (accessed
30 July 2022).

Bazzaz Abkenar, S., Haghi Kashani, M., Mahdipour, E., & Jameii, S.M. (2021). Big Data analytics meets social media: A systematic review of techniques, open issues, and future
directions. Telematics and Informatics, 57(March), 101517. https://doi.org/10.1016/j.
tele.2020.101517

Beck, K., Beedle, M., Van Bennekum, A., Cockburn, A., Cunningham, W., Fowler, M., Grenning, J., Highsmith, J., Hunt, A., & Jeffries, R. (2001). Manifesto for Agile Software Development. https://agilemanifesto.org (accessed 30 July 2022).

Beliveau, M., De Santa-Eulalia, L. A., Mosconi, E., & Cadieux, N. (2018). How can SME embarkin a digital transformation in the context of the 4th Industrial Revolution? 2nd International Symposium on Supply Chain, 4(0), 37

Berger, R. (2015). The Digital Transformation of Industry. Study commissioned by the Federation of German Industries (BDI), Munich. http://www.Rolandberger.Com/Publications/Publication_pdf/Roland_berger_Digital_transformation_of _industry_20150315.Pdf.

Berndtsson, M., Forsberg, D., Stein, D., & Svahn, T. (2018). Becoming a data-driven organisation. ECIS 2018 Proceedings, 1–9.

Berntsson Svensson, R., Feldt, R., & Torkar, R. (2019). The unfulfilled potential of data-driven decision making in agile software development. International Conference on Agile Software Development, 69–85.

Berntsson Svensson, R., & Taghavianfar, M. (2020). Toward becoming a data-driven organization: Challenges and benefits. In F. Dalpiaz, J. Zdravkovic, & P. Loucopoulos (Eds.), International Conference on Research Challenges in Information Science (pp. 3–19). Springer International Publishing.

Bissell, D. (2018). Automation interrupted: How autonomous vehicle accidents transform the material politics of automation. Political Geography, 65, 57–66. https://doi.org/https://doi.org/10.1016/j.polgeo.2018.05.003

Boes, K., Buhalis, D., & Inversini, A. (2015). Conceptualising smart tourism destination dimensions. In Information and Communication Technologies in Tourism 2015 (pp. 391–403).
Springer. Bogers, M., Chesbrough, H., Heaton, S., & Teece, D.J. (2019). Strategic management of open innovation: A dynamic capabilities perspective. California Management Review, 62(1), 77–94. https://doi.org/10.1177/0008125619885150

Brandão, A., Mamede, H.S., & Gonçalves, R. (2018). Systematic review of the literature, research on blockchain technology as support to the trust model proposed applied to smart places. In Á. Rocha, H. Adeli, L.P. Reis, & S. Costanzo (Eds.), World Conference on Information Systems and Technologies (pp. 1163–1174). Springer International Publishing.

Brinch, M., Gunasekaran, A., & Fosso Wamba, S. (2021). Firm-level capabilities towards
big data value creation. Journal of Business Research, 131(July), 539–548. https://doi.
org/10.1016/j.jbusres.2020.07.036e 

Brown, N., & Brown, I. (2019). From digital business strategy to digital transformation – How: A systematic literature review. Proceedings of the South African Institute of Computer Scientists and Information Technologists 2019, 1–8.

Brunswicker, S., Bertino, E., & Matei, S. (2015). Big Data for open digital innovation – A research roadmap. Big Data Research, 2(2), 53–58. https://doi.org/10.1016/j.bdr.2015.01.008

Brunswicker, S., & Vanhaverbeke, W. (2015). Open innovation in small and medium-sized enterprises (SMEs): External knowledge sourcing strategies and internal organizational facilitators. Journal of Small Business Management, 53(4), 1241–1263.

Bumann, J., & Peter, M. (2019). Action fields of digital transformation – A review and comparative analysis of digital transformation maturity models and frameworks. Digitalisierung und andere Innovationsformen im Management, 2(November), 13–40.

Buonincontri, P., & Micera, R. (2016). The experience co-creation in smart tourism destinations: A multiple case analysis of European destinations. Information Technology & Tourism, 16(3), 285–315.

Burchardt, C., & Maisch, B. (2019). Digitalization needs a cultural change – Examples of applying Agility and Open Innovation to drive the digital transformation. Procedia CIRP, 84, 112–117. https://doi.org/10.1016/j.procir.2019.05.009

Busulwa, R., Evans, N., Oh, A., & Kang, M. (2020). Hospitality Management and Digital
Transformation: Balancing efficiency, agility and guest experience in the era of disruption. Routledge.

Caddeo, F., & Pinna, A. (2021). Opportunities and challenges of blockchain-oriented systems in the tourism industry. 2021 IEEE/ACM 4th International Workshop on Emerging Trends in Software Engineering for Blockchain (WETSEB), 9–16.

Calvaresi, D., Leis, M., Dubovitskaya, A., Schegg, R., & Schumacher, M. (2019). Trust in
tourism via blockchain technology: Results from a systematic review. Information and
Communication Technologies in Tourism 2019, 304–317.

Çapar, H. (2020). Using cryptocurrencies and transactions in medical tourism. Journal of
Economic and Administrative Sciences. https://doi.org/10.1108/JEAS-07-2019-0080e

Caralli, R.A., Stevens, J.F., Young, L.R., & Wilson, W.R. (2007). Introducing Octave Allegro: Improving the information security risk assessment process. Carnegie-Mellon University Software Engineering Institute.

Carbone, C. (2018). Google revises code of conduct, removes “Don’t be evil”. New York Post, 22 May. https://nypost.com/2018/05/22/google-revises-code-of-conduct-removes-dont-beevil/ (accessed 23 June 2022).

Castaldi, L., Iscaro, V., Maresca, P., & Mazzoni, C. (2019). Digital transformation and internationalization: A complexity approach. Paper delivered at conference, Digital Transformation and Internationalization of Firms: Prospects, Challenges and Future Agenda, University of Rome LUMSA, Palermo, 7–8 February.

Castellani, D., Rullani, E., & Zanfei, A. (2017). Districts, multinationals and global/digital networks. Economia e Politica Industriale, 44(4), 429–447.

Centobelli, P., & Ndou, V. (2019). Managing customer knowledge through the use of Big Data analytics in tourism research. Current Issues in Tourism, 22(15), 1862–1882. https://doi.org/10.1080/13683500.2018.1564739

Cepeda, J., & Arias-Pérez, J. (2019). Information technology capabilities and organizational agility: The mediating effects of open innovation capabilities. Multinational Business Review, 27(2), 198–216. https://doi.org/10.1108/MBR-11-2017-0088

Cetina, C., Giner, P., Fons, J., & Pelechano, V. (2013). Prototyping dynamic software product lines to evaluate run-time reconfigurations. Science of Computer Programming, 78(12), 2399–2413.

Chen, C.L.P., & Zhang, C.-Y. (2014). Data-intensive applications, challenges, techniques and technologies: A survey on Big Data. Information Sciences, 275, 314–347.

Chen, F., Deng, P., Wan, J., Zhang, D., Vasilakos, A.V, & Rong, X. (2015). Data mining for the internet of things: Literature review and challenges. International Journal of Distributed Sensor Networks, 11(8), 431047.

Chen, Z., Alfred, R., & Eboy, O.V. (2021). Modeling tourism using spatial analysis based on social media big data: A review. Computational Science and Technology: 7th ICCST 2020, Pattaya, Thailand, 29–30 August, 2020, 724, 437.

Chesbrough, H. (2003). Open Innovation: new imperative for creating and profiting from technology. Harvard Business Press.

Chesbrough, H., & Bogers, M. (2014). Explicating open innovation: Clarifying an emerging
paradigm for understanding innovation. In New Frontiers in Open Innovation (pp. 3–28).
Oxford University Press.

Chesbrough, H., Vanhaverbeke, W., & West, J. (2006). Open Innovation: Researching a new
paradigm. Oxford University Press on Demand.

Chesbrough, H., Vanhaverbeke, W., & West, J. (2014). New Frontiers in Open Innovation.
Oxford University Press.

Chessell, M., Scheepers, F., Nguyen, N., van Kessel, R., & van der Starre, R. (2014). Governing and managing big data for analytics and decision makers. IBM Redguides for Business Leaders. IBM Redbooks.

Chessell, M., Scheepers, F., Strelchuk, M., van der Starre, R., Dobrin, S., & Hernandez, D. (2018). The Journey Continues: From data lake to data-driven organization. IBM Redbooks. 

Chiheb, F., Boumahdi, F., & Bouarfa, H. (2019). A new model for integrating Big Data into phases of decision-making process. Procedia Computer Science, 151(2018), 636–642. https://doi.org/10.1016/j.procs.2019.04.085e

Christen, M., Blumer, H., Hauser, C., & Huppenbauer, M. (2019). The ethics of Big Data
applications in the consumer sector. Applied Data Science, 161–180. https://doi.org/10.
1007/978-3-030-11821-1_10

Chuang, C.-M. (2020). A current travel model: smart tour on mobile guide application services. Current Issues in Tourism, 23(18), 2333–2352.

Chui, M., Manyika, J., & Miremadi, M. (2016). Where machines could replace humans – and
where they can’t (yet). McKinsey Quarterly (July 8). https://www.mckinsey.com/business-
functions/mckinsey-digital/our-insights/where-machines-could-replace-humans-andwhere-
they-cant-yet (accessed 30 July 2022).

Chung, N., Han, H., & Koo, C. (2015). Adoption of travel information in user-generated content on social media: The moderating effect of social presence. Behaviour & Information Technology, 34(9), 902–919.

Chung, N., & Koo, C. (2015). The use of social media in travel information search. Telematics and Informatics, 32(2), 215–229.

Cloudera. (2022). Apache Hadoop Ecosytem. https://es.cloudera.com/products/open-source/
apache-hadoop.html (accessed 4 October 2022).

Cohen, S.A., & Hopkins, D. (2019). Autonomous vehicles and the future of urban tourism.
Annals of Tourism Research, 74, 33–42. https://doi.org/https://doi.org/10.1016/j.
annals.2018.10.009

Collier, K. (2012). Agile Analytics: A value-driven approach to business intelligence and data warehousing. Addison-Wesley.

D’Aveni, R.A., Dagnino, G.B., & Smith, K.G. (2010). The age of temporary advantage. Strategic Management Journal, 31(13), 1371–1385.

Dahlström, P., Desmet, D., & Singer, M. (2017). The seven decisions that matter in a digital transformation: A CEO’s guide to reinvention. McKinsey Digital. https://www.mckinsey.com/business-functions/mckinsey-digital/our-insights/the-seven-decisions-that-matter-in-a-digital-transformation (accessed 30 July 2022).

Damnjanovic´, V., Loncˇaric´, D., & Dlacˇic´, J. (2020). Teaching case study: Digital marketing strategy of Accor Hotels: Shaping the future of hospitality. Tourism and Hospitality Management, 26(1), 233–244.

Davenport, T.H., & Ronanki, R. (2018). Artificial intelligence for the real world. Harvard Business Review, 96(1), 108–116.

De Saulles, M. (2016). The Internet of Things and business. In The Internet of Things and Business. Routledge https://doi.org/10.4324/9781315537849

Del Giudice, M. (2016). Discovering the Internet of Things (IoT) within the business process management: A literature review on technological revitalization. Business Process Management Journal, 22(2), 263–270. https://doi.org/10.1108/BPMJ-12-2015-0173

Del Vecchio, P., Di Minin, A., Petruzzelli, A. M., Panniello, U., & Pirri, S. (2018). Big Data for open innovation in SMEs and large corporations: Trends, opportunities, and challenges. Creativity and Innovation Management, 27(1), 6–22. https://doi.org/10.1111/caim.12224

Del Vecchio, P., Mele, G., Ndou, V., & Secundo, G. (2018a). Creating value from Social Big Data: Implications for smart tourism destinations. Information Processing and Management, 54(5), 847–860. https://doi.org/10.1016/j.ipm.2017.10.006

Del Vecchio, P., Mele, G., Ndou, V., & Secundo, G. (2018b). Open innovation and social big data for sustainability: Evidence from the tourism industry. Sustainability (Switzerland), 10(9). https://doi.org/10.3390/su10093215

Deng, L., Tang, H., & Roy, K. (2021). Understanding and bridging the gap between neuromorphic computing and machine learning. In Frontiers in Computational Neuroscience. Frontiers Media SA. https://doi.org/10.3389/978-2-88966-742-0

Donker-Rostamy, M. (2019). Agile Facilitates Data-Driven Solutions. Open University of the Netherlands.

Dorcic, J., Komsic, J., & Markovic, S. (2019). Mobile technologies and applications towards smart tourism – state of the art. Tourism Review, 74(1), 82–103. https://doi.org/10.1108/ TR-07-2017-0121

Dredge, D., Phi, G., Mahadevan, R., Meehan, E., & Popescu, E.S. (2019). Digitalisation in Tourism: In-depth analysis of challenges and opportunities. Executive Agency for Small and Medium-Sized Enterprises (EASME), European Commission. https://ec.europa.eu/
docsroom/documents/33163/attachments/1/translations/en/renditions/native (accessed
30 July 2022).

Dreyfus, H.L. (1972). What Computers Can’t Do: The limits of artificial intelligence. Harper & Row.

Duan, Y., Edwards, J.S., & Dwivedi, Y.K. (2019). Artificial intelligence for decision making in the era of Big Data – Evolution, challenges and research agenda. International Journal of Information Management, 48, 63–71. https://doi.org/10.1016/j.ijinfomgt.2019.01.021

Earley, S. (2014). Agile analytics in the age of big data. IT Professional, 16(4), 18–20. 

Elgan, M. (2020). Why it’s unethical for businesses to use Facebook. Insider Pro, 30 September. https://www.idginsiderpro.com/article/3584055/why-its-unethical-for-businesses-to-usefacebook.html (accessed 23 June 2022).

Facts and Factors. (2022). Online Travel Booking Market. https://www.fnfresearch.com/
online-travel-booking-market (accessed 23 June 2022).

Fang, H. (2015). Managing data lakes in big data era: What’s a data lake and why has it became popular in data management ecosystem. 2015 IEEE International Conference on Cyber Technology in Automation, Control, and Intelligent Systems (CYBER), 820–824.

Feng, J., Yang, Y., Shen, H., & Cai, Z. (2017). Development of lighting control system for smart hotel rooms. International Journal of Performability Engineering, 13(6), 913.

Fernandez-Carames, T.M., & Fraga-Lamas, P. (2020). Towards post-quantum blockchain: A review on blockchain cryptography resistant to quantum computing attacks. IEEE Access,
8, 21091–21116. arXiv:2004.07917. https://doi.org/10.1109/ACCESS.2020.2968985

Filatotchev, I., & Nakajima, C. (2010). Internal and external corporate governance: An interface between an organization and its environment. British Journal of Management, 21(3), 591–606.

Fleisch, E., Weinberger, M., & Wortmann, F. (2015). Business models and the Internet of
Things. In Interoperability and Open-Source Solutions for the Internet of Things (pp. 6–10). Springer.

Fletcher, G., Groth, P., & Sequeda, J. (2020). Knowledge scientists: Unlocking the data-driven organization. https://doi.org/10.48550/arXiv.2004.07917

Forbes Business Insights. (2021). Cyber Security Market, 2021–2028. https://www.fortunebusinessinsights.com/industry-reports/cyber-security-market-101165 (accessed 23 June 2022).

Forbes Coaches Council. (2018). What Does it Mean to Be an Agile Leader? Forbes. https://www.forbes.com/sites/forbescoachescouncil/2018/06/29/what-does-it-mean-to-be-an-agile-leader/?sh=7fb4cd54db4f (accessed 23 June 2022).

Forman, E.H., & Selly, M.A. (2001). Introduction: management decision-making today. In
Decision by Objectives: How to convince others that you are right (pp. 1–14). World Scientific. https://doi.org/10.1142/9789812810694_0001

Fortune Business Insights. (2020). The Global Big Data Technology Market Size. https://www.fortunebusinessinsights.com/industry-reports/big-data-technology-market-100144 (accessed 23 June 2022).

Friedman, H.H. (2020). Organizational Agility, Visionary Leadership in the Age of VUCA. https://doi.org/10.2139/ssrn.3728372

FTC. (2015). The Internet of Things: Privacy and Security in a Connected World. Federal Trade Commission.

Gagel, G. (2017). The intersection of organizational agility and transformational leadership: A literature review. Academy of Management Proceedings, 2017(1), 10895. https://doi.org/10.5465/ambpp.2017.10895abstract

Gaurav, J., & Kongar, E. (2021). Value creation via accelerated digital transformation.
IEEE Engineering Management Review, 49(2), 63–72. https://doi.org/10.1109/EMR.2021.3054813

GeeksforGeeks. (2021). Hadoop Ecosystem. https://www.geeksforgeeks.org/hadoop-ecosystem/
(accessed 23 June 2022).

Gestrin, M.V., & Staudt, J. (2018). The Digital Economy, Multinational Enterprises and
International Investment Policy. https://t4.oecd.org/investment/the-digital-economy-multinational-enterprises-and-international-investment-policy.htm (accessed 26 July 2022).

Ghemawat, S., Gobioff, H., & Leung, S.-T. (2003). The Google file system. Proceedings of the Nineteenth ACM Symposium on Operating Systems Principles, 29–43.

Ghorbani, A., Danaei, A., Zargar, S. M., & Hematian, H. (2019). Designing of smart tourism organization (STO) for tourism management: A case study of tourism organizations of South Khorasan province, Iran. Heliyon, 5(6), e01850. https://doi.org/10.1016/j.heliyon.2019.e01850

Ghule, V., & Sakhare, S. (2017). Smart organization. 2017 IEEE 7th International Advance
Computing Conference (IACC), 826–830.

Gill, S.S., Kumar, A., Singh, H., Singh, M., Kaur, K., Usman, M., & Buyya, R. (2020). Quantum computing: A taxonomy, systematic review and future directions. Journal of Sotware: Practice and Experience, 52(1), 66–114. https://doi.org/10.1002/spe.3039

Gillet, F. (2018). Boost CX Quality by Using IoT in Customer Journeys. https://www.forrester.com/report/Boost-CX-Quality-By-Using-IoT-In-Customer-Journeys/RES137069 (accessed 23 June 2022).

Grecuccio, J., Giusto, E., Fiori, F., & Rebaudengo, M. (2020). Combining blockchain and IoT: Food-chain traceability and beyond. Energies, 13(15), 3820.

Greineder, M.J., Blohm, I., & Leicht, N. (2020). Conceptualizing the agile work organization: A systematic literature review, framework and research agenda. BLED 2020
Proceedings, 25.

Gretzel, U., Sigala, M., Xiang, Z., & Koo, C. (2015a). Smart tourism: Foundations and developments. Electronic Markets, 25(3), 179–188.

Gretzel, U., Werthner, H., Koo, C., & Lamsfus, C. (2015b). Conceptual foundations for understanding smart tourism ecosystems. Computers in Human Behavior, 50, 558–563.

Gudivada, V.N., Pankanti, S., Seetharaman, G., & Zhang, Y. (2019). Cognitive computing systems: Their potential and the future. Computer, 52(5), 13–18.

Guttentag, D.A. (2010). Virtual reality: Applications and implications for tourism. Tourism Management, 31(5), 637–651.

Hamm, S., & Kelly, J. (2013). Smart Machines: IBM’s Watson and the era of cognitive computing. Columbia University Press. https://doi.org/10.7312/columbia/9780231168564.001.0001

Hanelt, A., Bohnsack, R., Marz, D., & Antunes Marante, C. (2021). A systematic review of the literature on digital transformation: Insights and implications for strategy and organizational change. Journal of Management Studies, 58(5), 1159–1197.

Harari, Y.N. (2016). Homo Deus: Breve historia del mañana. Debate.

Henriette, E., Feki, M., & Boughzala, I. (2015). The shape of digital transformation: A systematic literature review. MCIS 2015 Proceedings, 10, 431–443.

Hoffman, D.L., & Novak, T. (2015). Emergent experience and the connected consumer in the smart home assemblage and the Internet of Things. https://doi.org/10.2139/ssrn.2648786

Högberg, K. (2021). Strategic responses to digital disruption – an exploratory study of digital transformation in hospitality. AMICS 2021 Proceedings, 10. https://aisel.aisnet.org/amcis2021/org_transform/org_transform/10/ (accessed 4 October 2022).

Hönigsberg, S., & Dinter, B. (2019). Toward a method to foster the digital transformation in SME networks. ICIS 2019 Proceedings, 9. https://aisel.aisnet.org/icis2019/business_models/business_models/19 (accessed 30 July 2022).

Hume, E., & West, A. (2020). Becoming a data-driven decision making organization. The CPA Journal, 90(4), 32–35.

Hupperz, M., Gür, I., Möller, F., & Otto, B. (2021). What is a data-driven organization? AMCIS 2021 Proceedings, 6. https://aisel.aisnet.org/amcis2021/strategic_is/strategic_is/6 (accessed 30 July 2022).

IATA. (2022). Air passenger numbers to recover in 2024. https://www.iata.org/en/pressroom/2022-releases/2022-03-01-01/ (accessed 23 June 2022).

IBM. (2022). What is data science? https://www.ibm.com/cloud/learn/data-science-introduction (accessed 23 June 2022).

IDC. (2021). IDC forecasts worldwide quantum computing market to grow to $8.6 billion in 2027. 29 November. https://www.idc.com/getdoc.jsp?containerId=prUS48414121 (accessed 23
June 2022).

Iglesias-Sánchez, P.P., Correia, M.B., & Jambrino-Maldonado, C. (2019). Challenges of open innovation in the tourism sector. Tourism Planning and Development, 16(1), 22–42. https://doi.org/10.1080/21568316.2017.1393773

Information Threat Group. (2017). Insider Threat: Spotlight report. http://crowdresearchpartners.com/wp-content/uploads/2017/07/Insider-Threat-Report-2016.pdf (accessed 30 July 2022).

Intel. (2022). Neuromorphic and probabilistic computing. Beyond today’s AI. https://www.intel.es/content/www/es/es/research/neuromorphic-computing.html (accessed 23 June 2022).

Irdeto. (2019). New 2019 Global Survey: IoT-focused cyberattacks are the new normal. https://resources.irdeto.com/global-connected-industries-cybersecurity-survey/new-2019-globalsurvey-iot-focused-cyberattacks-are-the-new-normal (accessed 23 June 2022).

Ivanov, S., & Webster, C. (2019). Conceptual framework of the use of robots, artificial intelligence and service automation in travel, tourism, and hospitality companies. In Robots, Artificial Intelligence, and Service Automation in Travel, Tourism and Hospitality (pp. 7–37). Emerald Publishing Limited. https://doi.org/10.1108/978-1-78756-687-320191001

Jandail, S., & Ratan, R. (2014). A proposed novel approach for sentiment analysis and opinion mining. International Journal of UbiComp (IJU), 5(1/2), 1–10. https://doi.org/10.5121/iju.2014.5201.

Jankel, N. (2015). AI vs human intelligence: Why computers will never create disruptive
innovations. Huffington Post. https://www.huffpost.com/entry/ai-vs-human-intelligence-_
b_6741814 (accessed 23 June 2022).

Javornik, A. (2016). Augmented reality: Research agenda for studying the impact of its media characteristics on consumer behaviour. Journal of Retailing and Consumer Services, 30, 252–261.

Jesse, N. (2018). Internet of Things and Big Data: The disruption of the value chain and the rise of new software ecosystems. AI and Society, 33(2), 229–239. https://doi.org/10.1007/s00146-018-0807-y

Jha, N. (2021). Short review on quantum computing and it future trends. International Journal of Research in Engineering and Science (IJRES), 9(7), 71–75.

Jiao, E.X., & Chen, J.L. (2019). Tourism forecasting: A review of methodological developments over the last decade. Tourism Economics, 25(3), 469–492. https://doi.org/10.1177/1354816618812588

Jingen Liang, L., & Elliot, S. (2021). A systematic review of augmented reality tourism research: What is now and what is next? Tourism and Hospitality Research, 21(1), 15–30.

Jöhnk, J., Ollig, P., Oesterle, S., & Riedel, L.-N. (2020). The complexity of digital transformation – Conceptualizing multiple concurrent initiatives. Proceedings of the 15th International Conference on Wirtschaftsinformatik (WI), 1051–1066. https://doi.org/10.30844/wi_2020_j8-joehnk

Joiner, B. (2019). Leadership agility for organizational agility. Journal of Creating Value, 5(2), 139–149. https://doi.org/10.1177/2394964319868321

Joy, B. (2000). Why the future doesn’t need us. Wired (1 April). https://www.wired.com/2000/04/joy-2 (accessed 30 July 2022).

Juc, N., & Misrahi, Ti. (2021). Travel & Tourism Economic Impact 2021. https://wttc.org/Portals/0/Documents/Reports/2021/Global%20Economic%20Impact%20and%20Trends%202021.pdf?ver=2021-07-01-114957-177 (accessed 23 June 2022).

Jung, T.H., & tom Dieck, M.C. (2017). Augmented reality, virtual reality and 3D printing for the co-creation of value for the visitor experience at cultural heritage places. Journal of Place Management and Development, 10(2), 140–151. https://doi.org/10.1108/
JPMD-07-2016-0045

Kaivo-Oja, J., Virtanen, P., Jalonen, H., & Stenvall, J. (2015). The effects of the Internet of Things and Big Data to organizations and their knowledge management practices. International Conference on Knowledge Management in Organizations, 495–513.

Kaplan, A., & Haenlein, M. (2019). Siri, Siri, in my hand: Who’s the fairest in the land? On the interpretations, illustrations, and implications of artificial intelligence. Business Horizons, 62(1), 15–25.

Kaspersky Lab. (2018). Damage Control: The cost of security breaches (IT security risks
special report). https://media.kaspersky.com/pdf/it-risks-survey-report-cost-of-securitybreaches.pdf (accessed 30 July 2022).

Kauffmann, E., Peral, J., Gil, D., Ferrández, A., Sellers, R., & Mora, H. (2019). A framework for Big Data analytics in commercial social networks: A case study on sentiment analysis and fake review detection for marketing decision-making. Industrial Marketing Management, 90(August), 523–537. https://doi.org/10.1016/j.indmarman.2019.08.003

Kellerman, A. (2018). Automated and Autonomous Spatial Mobilities. Edward Elgar Publishing. 

Kelly, E. (2015). Introduction: Business ecosystems come of age. Deloitte Insights (16 April), 3–16. https://www2.deloitte.com/us/en/insights/focus/business-trends/2015/business-ecosystems-come-of-age-business-trends.html (accessed 30 July 2022).

Kemp, R. (2014). Legal aspects of managing Big Data. Computer Law and Security Review,
30(5), 482–491. https://doi.org/10.1016/j.clsr.2014.07.006

Kiron, D. (2017). Lessons from becoming a data-driven organization. MIT Sloan Management
Review, 58(2). https://sloanreview.mit.edu/case-study/lessons-from-becoming-a-data-
driven-organization (accessed 30 July 2022).

Kounavis, C.D., Kasimati, A.E., & Zamani, E.D. (2012). Enhancing the tourism experience
through mobile augmented reality: Challenges and prospects. International Journal of
Engineering Business Management, 4(1), 1–6. https://doi.org/10.5772/51644

KPMG. (2015). FEEL FREE Cyber Security Dashboard: Monitor, analyse and take control
of cyber security. KPMG Advisory NV. https://silo.tips/download/cyber-security-dashboard-monitor-analyse-and-take-control-of-cyber-security (accessed 30 July 2022).

Kung, L., Kung, H.-J., Jones-Farmer, A., & Wang, Y. (2015). Managing Big Data for Firm
Performance: A configurational approach. AMCIS 2015. https://doi.org/10.13140/
RG.2.1.4847.9843

Kurzweil, R. (2005). The Singularity Is Near: When humans transcend biology. Penguin.

Kurzweil, R., Richter, R., Kurzweil, R., & Schneider, M.L. (1990). The Age of Intelligent Machines (Vol. 580). MIT Press.

Larson, D., & Chang, V. (2016). A review and future direction of agile, business intelligence, analytics and data science. International Journal of Information Management, 36(5), 700–710.

LaValle, S., Lesser, E., Shockley, R., Hopkins, M.S., & Kruschwitz, N. (2011). Big Data, analytics and the path from insights to value. MIT Sloan Management Review, 52(2), 21–32.

Law, R., Chan, I.C.C., & Wang, L. (2018). A comprehensive review of mobile technology use in hospitality and tourism. Journal of Hospitality Marketing & Management, 27(6), 626–648.

Laxamanan, G., & Rahim, R.E.A. (2020). A systematic literature study from 2013 to 2018: The role of knowledge in open innovation. International Review of Management and Marketing, 10(2), 84–95. https://doi.org/10.32479/irmm.9337

Lee, I. (2019). The Internet of Things for enterprises: An ecosystem, architecture, and IoT service business model. Internet of Things, 7, 100078.

Lee, I. (2020). Internet of Things (IoT) cybersecurity: Literature review and IoT cyber risk management. Future Internet, 12(9). https://doi.org/10.3390/FI12090157

Leybourn, E. (2013). Directing the Agile Organisation: A lean approach to business management. IT Governance Ltd.

Li, J., Xu, L., Tang, L., Wang, S., & Li, L. (2018a). Big Data in tourism research: A literature review. Tourism Management, 68, 301–323.

Li, L., Su, F., Zhang, W., & Mao, J.Y. (2018b). Digital transformation by SME entrepreneurs: A capability perspective. Information Systems Journal, 28(6), 1129–1157. https://doi.org/10.1111/isj.12153

Li, M., Yin, D., Qiu, H., & Bai, B. (2021). A systematic review of AI technology-based service encounters: Implications for hospitality and tourism operations. International Journal of Hospitality Management, 95(May), 102930. https://doi.org/10.1016/j.ijhm.2021.102930

Li, X., & Law, R. (2020). Network analysis of Big Data research in tourism. Tourism Management Perspectives, 33, 100608. https://doi.org/10.1016/j.tmp.2019.100608

Li, Y., Hu, C., Huang, C., & Duan, L. (2017). The concept of smart tourism in the context of tourism information services. Tourism Management, 58, 293–300.

Liao, S., Liu, Z., & Ma, C. (2019). Direct and configurational paths of open innovation and organisational agility to business model innovation in SMEs. Technology Analysis and Strategic Management, 31(10), 1213–1228. https://doi.org/10.1080/09537325.2019.1601693

Liebana-Cabanillas, F., Carvajal-Trujillo, E., Villarejo-Ramos, Á.F., & Higueras-Castillo, E. (2020). Antecedents of the intention to use NFC mobile applications in tourism. Journal of Hospitality and Tourism Technology, 11(2), 369–383.

Lu, Y., Papagiannidis, S., & Alamanos, E. (2018). Internet of Things: A systematic review of the business literature from the user and organisational perspectives. Technological Forecasting and Social Change, 136, 285–297.

Lv, H., Shi, S., & Gursoy, D. (2021). A look back and a leap forward: A review and synthesis of big data and artificial intelligence literature in hospitality and tourism. Journal of Hospitality Marketing & Management, 31, 145–175.

Lytras, M.D., & Visvizi, A. (2021). Artificial Intelligence and Cognitive Computing: Methods, technologies, systems, applications and policy making. Multidisciplinary Digital Publishing Institute.

Ma, M., Wang, P., & Chu, C.-H. (2013). Data management for Internet of Things: Challenges, approaches and opportunities. 2013 IEEE International Conference on Green Computing and Communications and IEEE Internet of Things and IEEE Cyber, Physical and Social Computing, 1144–1151.

Maalem Lahcen, R.A., Caulkins, B., Mohapatra, R., & Kumar, M. (2020). Review and insight
on the behavioral aspects of cybersecurity. Cybersecurity, 3(1). https://doi.org/10.1186/s42400-020-00050-w

Madera, J.M., Dawson, M., Guchait, P., & Belarmino, A.M. (2017). Strategic human resources management research in hospitality and tourism: A review of current literature and suggestions for the future. International Journal of Contemporary Hospitality Management, 29(1), 48–67.

Mahraz, I., Benabbou, L., & Berrado, A. (2019). A systematic literature review of digital transformation. In Proceedings of the International Conference on Industrial Engineering and Operations Management. IEOM Society International.

Makridakis, S. (2017). The forthcoming artificial intelligence (AI) revolution: Its impact on society and firms. Futures, 90, 46–60.

Mang, C.F., Piper, L. A., & Brown, N.R. (2016). The incidence of smartphone usage among tourists. International Journal of Tourism Research, 18(6), 591–601.

Mariani, M.M., Buhalis, D., Czakon, W., & Vitouladiti, O. (2016). Tourism Management, Marketing, and Development: Performance, strategies, and sustainability. Springer.

Mariani, M., Baggio, R., Fuchs, M., & Höepken, W. (2018), Business intelligence and Big Data in hospitality and tourism: A systematic literature review. International Journal of Contemporary Hospitality Management, 30(12), 3514-3554. https://doi.org/10.1108/IJCHM-07-2017-0461

Markoff, J. (2016). Machines of Loving Grace: The quest for common ground between humans
and robots. HarperCollins Publishers.

Matt, C., Hess, T., & Benlian, A. (2015). Digital transformation strategies. Business & 
Information Systems Engineering, 57(5), 339–343.

McAfee, A., Brynjolfsson, E., Davenport, T.H., Patil, D. J., & Barton, D. (2012). Big Data: The management revolution. Harvard Business Review, 90(10), 60–68.

McCarthy, J. (2007). What is artificial intelligence? http://jmc.stanford.edu/artificial-intelligence/what-is-ai/index.html (accessed 21 March 2022).

Mehraliyev, F., Chan, I.C.C., Choi, Y., Koseoglu, M.A., & Law, R. (2020). A state-of-the-art review of smart tourism research. Journal of Travel & Tourism Marketing, 37(1), 78–91.

Mihet, R., & Philippon, T. (2018). The Economics of Big Data. Mimeo. Mirarab, A., Mirtaheri, S.L., & Asghari, S.A. (2019). Value creation with big data analytics for enterprises: A survey. Telkomnika (Telecommunication Computing Electronics and Control),
17(6), 2790–2802. https://doi.org/10.12928/TELKOMNIKA.v17i6.11962

Miraz, M.H., Ali, M., Excell, P.S., & Picking, R. (2015). A review on Internet of Things (IoT), Internet of Everything (IoE) and Internet of Nano Things (IoNT). 2015 Internet Technologies and Applications (ITA), 219–224. https://doi.org/10.1109/ITechA.2015.7317398

Mirzaalian, F., & Halpenny, E. (2019). Social media analytics in hospitality and tourism: A systematic literature review and future trends. Journal of Hospitality and Tourism Technology, 10(4), 764–790. https://doi.org/10.1108/JHTT-08-2018-0078

Monino, J.L. (2021). Data value, Big Data analytics, and decision-making. Journal of the Knowledge Economy, 12(1), 256–267. https://doi.org/10.1007/s13132-016-0396-2

Morabito, V. (2015). Managing change for Big Data driven innovation. In Big Data and Analytics (pp. 125–153). Springer.

Morakanyane, R., Grace, A., & O’Reilly, P. (2017). Conceptualizing digital transformation in business organizations: A systematic review of literature. 30th Bled EConference: Digital Transformation – From Connecting Things to Transforming Our Lives, BLED 2017, 427–444. https://doi.org/10.18690/978-961-286-043-1.30

Müller, V.C., & Bostrom, N. (2016). Future progress in artificial intelligence: A survey of expert opinion. In Fundamental Issues of Artificial Intelligence (pp. 555–572). Springer. 

Murphy, J., Hofacker, C.F., & Gretzel, U. (2017). Robots in hospitality and tourism: A research agenda. In V.C. Müller (Ed.), Fundamental Issues of Artificial Intelligence. Synthese Library Vol. 376. Springer. https://doi.org/10.1007/978-3-319-26485-1_33

Nagle, T., Sammon, D., & Co-Directors (2013). Fast and flexible: Exploring agile data analytics. Cutter Benchmark Review, 13(2), 5.

Neuhofer, B., Buhalis, D., & Ladkin, A. (2014). A typology of technology-enhanced tourism experiences. International Journal of Tourism Research, 16(4), 340–350. New York Times. (2021). Bitcoin uses more money than many countries. How is that possible?
New York Times, 3 September. https://www.nytimes.com/interactive/2021/09/03/climate/
bitcoin-carbon-footprint-electricity.html (accessed 23 June 2022).

Ng, I.C.L., & Wakenshaw, S.Y.L. (2017). The internet-of-Things: Review and research directions. International Journal of Research in Marketing, 34(1), 3–21. https://doi.org/10.1016/j.ijresmar.2016.11.003

Ngo, V.M., & Vu, H.M. (2020). Customer agility and firm performance in the tourism industry. Tourism: An International Interdisciplinary Journal, 68(1), 68–82.

Nikolskaya, E.Y., Zakharova, E.V., Galkin, D.V., Kovaleva, N.I., & Panova, N.A. (2021). The impact of digital technologies on the transformation of the tourism and hospitality industry. Revista Geintec-Gestao Inovacao E Tecnologias, 11(4), 623–632.

Noor, A.K. (2015). Potential of cognitive computing and cognitive systems. Open Engineering, 5(1), 75–88. https://doi.org/10.1515/eng-2015-0008

Noor, M.N., & Haneef, F. (2020). A review on big data and social network analytics techniques. Researchpedia Journal of Computing, 1(1), 39–49.

Nord, J.H., Koohang, A., & Paliszkiewicz, J. (2019). The Internet of Things: Review and theoretical framework. Expert Systems with Applications, 133, 97–108.

OECD. (2017a). Enhancing the contributions of SMEs in a global and digitalised economy.
Meeting of the OECD Council at Ministerial Level. OECD Publishing.

OECD. (2017b). Key Issues for Digital Transformation in the G20. Report prepared for a joint G20 German Presidency/OECD Conference. https://www.oecd.org/g20/key-issues-for-digital-transformation-in-the-g20.pdf (accessed 30 July 2022).

OECD. (2019). SME and Entrepreneurship Outlook 2019. OECD. https://doi.org/10.1787/
34907e9c-ene 

OECD. (2020). Preparing tourism businesses for the digital future. In OECD Tourism Trends and Policies (pp. 59–85). OECD. https://doi.org/10.1787/6b47b985-en

Olszak, C. M., & Zurada, J. (2019). Big Data-driven value creation for organizations. Proceedings of the Annual Hawaii International Conference on System Sciences, January, 164–173. https://doi.org/10.24251/hicss.2019.021

Ozdemir, A.I., Ar, I.M., & Erol, I. (2020). Assessment of blockchain applications in travel and tourism industry. Quality & Quantity, 54(5), 1549–1563.

Palattella, M.R., Dohler, M., Grieco, A., Rizzo, G., Torsner, J., Engel, T., & Ladid, L. (2016). Internet of things in the 5G era: Enablers, architecture, and business models. IEEE Journal on Selected Areas in Communications, 34(3), 510–527.

Paraskevas, A. (2020). Cybersecurity in travel and tourism: A risk-based approach. Handbook of E-Tourism (pp. 1–24). https://doi.org/10.1007/978-3-030-05324-6_100-1

Parloff, R. (2016). From 2016: Why deep learning is suddenly changing your life. Fortune, 28 September. https://fortune.com/longform/ai-artificial-intelligence-deep-machine-learning (accessed 30 July 2022).

Pasca, M.G., Renzi, M. F., Di Pietro, L., & Guglielmetti Mugion, R. (2021). Gamification in tourism and hospitality research in the era of digital platforms: A systematic literature review. Journal of Service Theory and Practice, 31(5), 691–737. https://doi.org/10.1108/JSTP-05-2020-0094

Payne, A.F., Storbacka, K., & Frow, P. (2008). Managing the co-creation of value. Journal of the Academy of Marketing Science, 36(1), 83–96.

Pellizzoni, E., Trabucchi, D., & Buganza, T. (2019). When agility meets open innovation: Two approaches to manage inbound projects. Creativity and Innovation Management, 28(4), 464–476. https://doi.org/10.1111/caim.12337

Pesonen, J. (2020). Management and leadership for digital transformation in tourism. In Z. Xiang, M. Fuchs, U. Gretzel, & W. Höpken (Eds.), Handbook of e-Tourism (pp. 1–34). Springer. https://doi.org/10.1007/978-3-030-05324-6_68-1

Peterlin, J., Meško, M., Dimovski, V., & Roblek, V. (2021). Automated content analysis: The review of the Big Data systemic discourse in tourism and hospitality. Systems Research and Behavioral Science, 38(3), 377–385.

Petzold, B., Roggendorf, M., Rowshankish, K., & Sporleder, C. (2020). Designing Data
Governance That Delivers Value. McKinsey & Company.

Pinheiro, A.B., Pinto, A.S., Abreu, A., Costa, E., & Borges, I. (2021). The impact of artificial intelligence on the tourism industry: A systematic review. Smart Innovation, Systems and Technologies, 208, 458–469. https://doi.org/10.1007/978-981-33-4256-9_42

Pogue, C. (2018). The Black Report 2018. Decoding the minds of hackers. https://www.nuix.com/sites/default/files/report_nuix_black_report_2018_web_us.pdf (accessed 23 June 2022).

Poslad, S. (2011). Ubiquitous Computing: Smart devices, environments and interactions. John Wiley & Sons.

Pramanik, P.K.D., Pal, S., & Choudhury, P. (2018). Beyond automation: The cognitive IoT.
Artificial intelligence brings sense to the Internet of Things. In Cognitive Computing for Big Data Systems Over IoT (pp. 1–37). Springer.

prnewswire.com. (2021). 38% of Americans plan to travel more after the pandemic, nearly 1 in 4 plan to use crypto to pay for a part of their travel. 11 April. https://www.prnewswire.com/news-releases/38-of-americans-plan-to-travel-more-after-the-pandemic-nearly-1-in-4-plan-to-use-crypto-to-pay-for-a-part-of-their-travel-301267684.html (accessed 23 June 2022).

PWC. (2017). 2017 Global Digital IQ Survey: Blockchain. http://usblogs.pwc.com/emerging-
technology/2017-digital-iq-blockchain (accessed 29 October 2019).

Rao, B., Mohapatra, S., Saha, U., & Mitra, A. (2015). Applications of social network using quantum computing. Conference on Inter Disciplinary Research in Engineering and
Technology (ICIDRET 15), 144, 1144.

Reagin, M.J., & Gentry, M. V. (2018). Enterprise cybersecurity. Frontiers of Health Services Management, 35(1), 13–22. https://doi.org/10.1097/hap.0000000000000037

Reddy, S.K., & Reinartz, W. (2017). Digital transformation and value creation: Sea change ahead. GfK Marketing Intelligence Review, 9(1), 10.

Reinsel, D., Gantz, J., & Rydning, J. (2018). The Digitization of the World – From edge to core (November). https://www.seagate.com/files/www-content/our-story/trends/files/ idc-seagate-dataage-whitepaper.pdf (accessed 23 June 2022).

Reis, J., Amorim, M., Melão, N., & Matos, P. (2018). Digital transformation: A literature review and guidelines for future research. World Conference on Information Systems and Technologies, 411–421.

Rialti, R., Marzi, G., Ciappei, C., & Caputo, A. (2018). Reframing Agile Organization: Do Big Data analytics capabilities matter? Paper delivered at conference, Big Data and Managing in the Digital Economy, University of Surrey Business School, 18–20 April.

Riasanow, T., Setzke, D.S., Böhm, M., & Krcmar, H. (2019). Clarifying the notion of digital transformation: A transdisciplinary review of literature. Journal of Competences, Strategy & Management, 10(1), 5–31.

Rigby, D.K., Sutherland, J., & Takeuchi, H. (2016). Embracing agile. Harvard Business Review, 94(5), 40–50.

Roxo, M.T., & Brito, P.Q. (2018). Augmented reality trends to the field of business and economics: A review of 20 years of research. Asian Journal of Business Research, 8(2). https://doi.org/10.14707/ajbr.180051

Ruíz, M.A.C., Bohorquez, S.T., & Molano, J.I.R. (2017). Colombian tourism: Proposal app to foster smart tourism in the country. Advanced Science Letters, 23(11), 10533–10537.

Russom, P. (2013). Managing Big Data. TDWI Best Practices Report, TDWI Research, 1–40. Samara, D., Magnisalis, I., & Peristeras, V. (2020). Artificial intelligence and Big Data in tourism: A systematic literature review. Journal of Hospitality and Tourism Technology, 11(2), 343–367. https://doi.org/10.1108/JHTT-12-2018-0118

Santoro, G., Vrontis, D., Thrassou, A., & Dezi, L. (2018). The Internet of Things: Building a knowledge management system for open innovation and knowledge management capacity. Technological Forecasting and Social Change, 136, 347–354.

Santos-Júnior, A., Almeida-García, F., Morgado, P., & Mendes-Filho, L. (2020). Residents’ quality of life in smart tourism destinations: A theoretical approach. Sustainability (Switzerland), 12(20), 1–24. https://doi.org/10.3390/su12208445

Scannell, E. (2021). Recent quantum computing advances point to brighter future. TechTarget Search Data Center. 10 December. https://www.techtarget.com/searchdatacenter/ feature/Recent-quantum-computing-advances-point-to-brighter-future (accessed 1 March 2022).

Schwab, K. (2017). The Fourth Industrial Revolution. Crown Business. 

Schwartz, E.I. (2002). Digital Darwinism: 7 breakthrough business strategies for surviving in the cutthroat web economy. Currency.

Schwertner, K. (2017). Digital transformation of business. Trakia Journal of Sciences, 15(1), 388–393.

Sebei, H., Hadj Taieb, M.A., & Ben Aouicha, M. (2018). Review of social media analytics process and Big Data pipeline. Social Network Analysis and Mining, 8(1), 1–28. https://doi.org/10.1007/s13278-018-0507-0e

Seigneur, J.M. (2018). Towards geneva crypto-friendly smart tourism. Etats Généraux du
Tourisme. http://archive-ouverte.unige.ch/unige:103406 (accessed 4 October 2022).

Sestino, A., Prete, M.I., Piper, L., & Guido, G. (2020). Internet of Things and Big Data as enablers for business digitalization strategies. Technovation, 98, 102173. https://doi.org/10.1016/j.technovation.2020.102173

Setili, A. (2015). Does your leadership style destroy agility ... Or supercharge it? Leader to Leader, 2015(78), 56–61.

Shamim, S., Zeng, J., Shariq, S.M., & Khan, Z. (2019). Role of Big Data management in enhancing big data decision-making capability and quality among Chinese firms: A dynamic capabilities view. Information and Management, 56(6), 1–12. https://doi.org/10.1016/j.im.2018.12.003

Shamim, Saqib, Zeng, J., Shafi Choksy, U., & Shariq, S.M. (2020). Connecting Big Data management capabilities with employee ambidexterity in Chinese multinational enterprises through the mediation of Big Data value creation at the employee level. International Business Review, 29(6). https://doi.org/10.1016/j.ibusrev.2019.101604

Shim, J.P., Avital, M., Dennis, A.R., Rossi, M., Sørensen, C., & French, A. (2019). The transformative effect of the internet of things on business and society. Communications of the Association for Information Systems, 44(1), 5.

Shoval, N., Isaacson, M., & Chhetri, P. (2014). GPS, smartphones, and the future of tourism research. In A.A. Lew, C.M. Hall, & A.M. Williams (Eds.), The Wiley Blackwell Companion to Tourism (pp. 251–261). John Wiley & Sons. https://doi.org/10.1002/9781118474648.ch20

Singh, A., & Hess, T. (2020). How chief digital officers promote the digital transformation of their companies. In Strategic Information Management (pp. 202–220). Routledge.

Singh, M., Halgamuge, M.N., Ekici, G., & Jayasekara, C.S. (2018). A review on security and privacy challenges of Big Data. In Cognitive computing for big data systems over IoT (pp.175–200). Springer.

Skinner, H., Sarpong, D., & White, G.R.T. (2018). Meeting the needs of the Millennials and Generation Z: gamification in tourism through geocaching. Journal of Tourism Futures, 4(1), 93–104. https://doi.org/10.1108/JTF-12-2017-0060

Soeparno, H., & Perbangsa, A.S. (2021). Cloud quantum computing concept and development:
A systematic literature review. Procedia Computer Science, 179, 944–954. https://doi.org/10.1016/j.procs.2021.01.084

Stylos, N., Zwiegelaar, J., & Buhalis, D. (2021). Big Data empowered agility for dynamic, volatile, and time-sensitive service industries: The case of tourism sector. International Journal of Contemporary Hospitality Management, 33(3), 1015–1036. https://doi.org/10.1108/IJCHM-07-2020-0644

Tableau. (2022). What Is data visualization? Definition, examples, and learning resources. https://www.tableau.com/learn/articles/data-visualization (accessed 12 February 2022).

Tabrizi, B., Lam, E., Girard, K., & Irvin, V. (2019). Digital transformation is not about technology. Harvard Business Review, 13(March), 1–6.

Tajeddini, K., Ratten, V., & Merkle, T. (2019). Tourism, Hospitality and Digital Transformation: Strategic management aspects. Routledge.

Teece, D.J. (2007). Explicating dynamic capabilities: The nature and microfoundations of (sustainable) enterprise performance. Strategic Management Journal, 28(13), 1319–1350.

Teichert, R. (2019). Digital transformation maturity: A systematic review of literature. Acta Universitatis Agriculturae et Silviculturae Mendelianae Brunensis, 67(6), 1673–1687. https://doi.org/10.11118/actaun201967061673

Theoharidou, M., Kokolakis, S., Karyda, M., & Kiountouzis, E. (2005). The insider threat to information systems and the effectiveness of ISO17799. Computers & Security, 24(6),
472–484.

Thrassou, A., Vrontis, D., Chebbi, H., & Yahiaoui, D. (2012). A preliminary strategic marketing framework for new product development. Journal of Transnational Management, 17(1), 21–44. 

Torchia, M., & Calabrò, A. (2019). Open innovation in SMEs: A systematic literature review. Journal of Enterprising Culture, 27(02), 201–228. https://doi.org/10.1142/s0218495819500080

TravelPort. (2017). The Global Digital Traveler Research. https://marketing.cloud.travelport.com/gdtr-en-uk-download (accessed 30 July 2022).

Trenkle, J. (2019). Survival in the digital age – A framework for formulating a digital transformation strategy in SME. Proceedings of the 19th International Conference on Electronic Business, 428–442.

Tribe, J., & Mkono, M. (2017). Not such smart tourism? The concept of e-lienation. Annals of Tourism Research, 66, 105–115. https://doi.org/10.1016/j.annals.2017.07.001 Trustwave. (2020). 2020 Trustwave Global Security Report. https://www.trustwave.com/en-us/resources/library/documents/2020-trustwave-global-security-report (accessed 30 July 2022).

Tsaih, R.H., & Hsu, C.C. (2018). Artificial intelligence in smart tourism: A conceptual
framework. Proceedings of the International Conference on Electronic Business (ICEB),
2018(December), 124–133.

Udovita, P. (2020). Conceptual review on dimensions of digital transformation in modern era. International Journal of Scientific and Research Publications, 10(2), 520–529. 

Ullah, R. (2019). Agile Analytics: How organizations can benefit from the agile methodology for smoother delivery of data-driven analytics projects. MSc thesis, Universität Koblenz-Landau. https://hbz.opus.hbz-nrw.de/opus45-kola/frontdoor/deliver/index/docId/1918/file/ RafiUllah_Masterarbeit.pdf (accessed 30 July 2022).

UNCTAD. (2018). Technology and Innovation Report 2018: Harnessing frontier technologies
for sustainable development. United Nations. https://unctad.org/en/PublicationsLibrary/
tir2018overview_en.pdf (accessed 23 June 2022).

Unhelkar, B. (2017). Big Data Strategies for Agile Business: Framework, practices, and transformation Roadmap. CRC Press. https://doi.org/10.4324/9781315120232

UNWTO. (2021). UNWTO World Tourism Barometer. https://doi.org/https://doi.org/10.18111/
wtobarometereng Vaska, S., Massaro, M., Bagarotto, E.M., & Dal Mas, F. (2021). The digital transformation of business model innovation: A structured literature review. Frontiers in Psychology, 11, 3557.

Veit, D., Clemons, E., Benlian, A., Buxmann, P., Hess, T., Kundisch, D., Leimeister, J.M., Loos, P., & Spann, M. (2014). Business models: An information systems research agenda. Business & Information Systems Engineering, 6, 45–53.

Vial, G. (2019). Understanding digital transformation: A review and a research agenda. The Journal of Strategic Information Systems, 28(2), 118–144. https://doi.org/https://doi.org/10.1016/j.jsis.2019.01.003

Viñan-Ludeña, M.-S. (2019). A systematic literature review on social media analytics and smart tourism. In V. Katsoni & M. Segarra-Oña (Eds.), Smart Tourism as a Driver for Culture and Sustainability (pp. 357–374). Springer. https://doi.org/10.1007/978-3-030-03910-3_25

Webster, C., & Ivanov, S. (2020). Future tourism in a robot-based economy: A perspective article. Tourism Review, 75(1), 329–332. https://doi.org/10.1108/TR-05-2019-0172 

Wei, W. (2019). Research progress on virtual reality (VR) and augmented reality (AR) in tourism and hospitality: A critical review of publications from 2000 to 2018. Journal of Hospitality and Tourism Technology, 10(4), 539–570. https://doi.org/10.1108/JHTT-04-2018-0030

West, J., & Bogers, M. (2013). Leveraging external sources of innovation: A review of research on open innovation. Journal of Product Innovation Management, 31(4), 814–831. 

World Economic Forum. (2017). Digital Transformation Initiative: Aviation, travel and tourism industry. No. 060117; White Paper. http://reports.weforum.org/digital-transformation/wp-content/blogs.dir/94/mp/files/pages/files/wef-dti-aviation-travel-and-tourism-white-paper.pdf (accessed 30 July 2022).

Xu, F., Nash, N., & Whitmarsh, L. (2020). Big Data or small data? A methodological review of sustainable tourism. Journal of Sustainable Tourism, 28(2), 144–163.

Yarali, A., Joyce, R., & Dixon, B. (2020). Ethics of Big Data: Privacy, security and trust. Wireless Telecommunications Symposium, 2020, April. https://doi.org/10.1109/WTS48268.2020.9198734

Yin, C.Z.Y., Jung, T., tom Dieck, M.C., & Lee, M.Y. (2021). Mobile augmented reality heritage applications: Meeting the needs of heritage tourists. Sustainability (Switzerland), 13(5), 1–18. https://doi.org/10.3390/su13052523

Yoo, Y., Boland, R. J., Lyytinen, K., & Majchrzak, A. (2012). Organizing for innovation in the digitized world. Organization Science, 23(5), 1398–1408. https://doi.org/10.1287/orsc.1120.0771

Yung, R., & Khoo-Lattimore, C. (2019). New realities: A systematic literature review on virtual reality and augmented reality in tourism research. Current Issues in Tourism, 22(17), 2056–2081.

Zapata, M.L., Berrah, L., & Tabourot, L. (2020). Towards the definition of an impact level factor of SME features over digital transformation. IFIP International Conference on Advances in Production Management Systems, 123–130.

Zeng, J., & Glaister, K.W. (2018). Value creation from Big Data: Looking inside the black box. Strategic Organization, 16(2), 105–140.

Zine, P.U., Kulkarni, M.S., Chawla, R., & Ray, AK. (2014). A framework for value co-creation through customization and personalization in the context of machine tool PSS. Procedia CIRP, 16, 32–37.

Zobel, A.-K., Balsmeier, B., & Chesbrough, H. (2016). Does patenting help or hinder open
innovation? Evidence from new entrants in the solar industry. Industrial and Corporate Change, 25(2), 307–331.

Zsarnoczky, M. (2018). The digital future of the tourism & hospitality industry. Boston Hospitality Review, 6, 1–9.

:::
