---
title: "Smart Technologies"
---

Part 2 of the book aims to help tourism firm owners and managers navigate the 
stormy waters of smart technologies that are changing the tourism ecosystem 
deeply and forever. The number, variety, and complexity of smart technologies has not stopped growing in recent years, as well as the increasingly powerful functionalities they offer to tourism firms. Not surprisingly, the world of smart technologies can be intimidating for many business leaders, as it happens to many specialists. However, all smart technologies have a common articulating factor: data. Therefore, this part of the book begins with a chapter that lays the conceptual foundations to understand data and that every owner and manager should know to enter the world of smart technologies. The following chapters will separate the wheat from the chaff as they place under the magnifying glass the critical technologies that are driving change in tourism firms: Big Data, data analytics, artificial intelligence, and the Internet of Things. At the end of this part, the reader will have a broad perspective on smart technologies and the opportunities that their applications offer, as well as the challenges and drawbacks that they pose for the management of tourism SMEs.
