---
title: "Smartization and Digital Transformation"
---

Undertaking the process of smartization in a tourism firm necessarily implies that digital transformation has taken root in the firm or is being carried out in parallel. Effective smartization involves a large-scale migration of the firm's operational and organizational model to another model based on data and knowledge. This requires that firms enforce management practices that involve data-driven processes and technologies and a more agile and efficient customer-centric organizational design that sustains activities over time (Dahlström et al., 2017).

So, you may be asking yourself, is smartization the same or is it different from digital transformation? Is there any true difference between the two? Smartization represents a big step forward beyond digital transformation. Nonetheless, smartization is not possible without digital transformation, and if you are not first familiar with the essentials of digital transformation, it will be more challenging for you to continue to dive into the basics of smartization. For this reason, this chapter examines the basic elements of digital transformation that every business owner and manager should know to successfully tackle the process of smartization in the tourism firm.

## Defining Digital Transformation

Just as happened when we defined the terms smart and smart tourism, defining digital transformation is not straightforward. The literature on digital transformation is vast and many authors and organizations have contributed their particular vision of the phenomenon in recent years, generally emphasizing those dimensions that most affected or concerned them. Although it is not within the scope of this chapter to theorize or try to establish a universal definition of what digital transformation is, it is worth stopping for a moment a make clear how the notion of digital transformation has been used in this book, so that we can share a common vocabulary.

The term "digital transformation" refers in this book to a process of profound and evolutionary change that affects all aspects of the organization, led by digital capabilities and technologies aimed at creating value. The fact that digital transformation is an evolutionary process indicates that the phenomenon of transformation is continuous; that is, it is maintained over time (Morakanyane et al., 2017). There are some authors, however, who argue that digital transformation involves more radical or disruptive change than simply an evolutionary process. This is a challenging academic discussion that has been going on for a long time in which the author cannot take sides because, in the end, both streams of thought are adequate lenses to tackle digital transformation (Riasanow et al., 2019). The idea of an evolutionary process accurately describes what happens most of the time in the digital transformation of businesses in real life, although it is also true that tourism firms must be prepared for disruptions in their routine activities and business processes when faced with digital transformation (Balaji & Lavanya, 2018).

Digital technologies play a vital role and are the foundation of digital transformation initiatives. However, digital transformation is not connected to any specific technology (e.g., cloud computing, mobile phones, social media, etc.); nor is it driven by any particular digital innovation. Even those who think that using digital technologies is enough to drive change and achieve transformation are wrong. Organizations fundamentally require a set of new skills, as well as a distinctive mindset and culture, to successfully tackle digital transformation. It is precisely into this set of new capabilities that digital technologies must be incorporated if the organization intends to reap the benefits of digital transformation.

Digital technologies, coupled with organizational capabilities, can create endless opportunities with the potential to transform tourism firms, especially when they are related to new business models, operating processes, and products and services. In the end, what owners and managers should seek is to create value both for the organization and for customers by generating operational efficiencies, improving the customer experience, reducing costs, improving the relationship with stakeholders, etc. In view of the above, there are three different but closely related dimensions that shape digital transformation (Reis et al., 2018):

-   The **technological dimension**, since digital transformation is based around the use of digital technologies that include infrastructures, networks, devices, as well as the software that makes digital applications possible.

-   The **organizational dimension**, since digital transformation itself entails a significant change in the organizational processes, and even in the culture and business model of the tourism firm.

-   The **social dimension**, since digital transformation is a process that affects consumer behavior and beliefs, both individually and in society (i.e., the way tourists consume tourism products and services, the reasons why tourists prefer some channels to others, the way tourists interact with friends and family, or how tourists enjoy a travel experience).

When it comes to digital transformation, the mere implementation of digital technologies in the organization is not enough. Rather, digital transformation encompasses far-reaching changes that extend to organizational management, the firm's operational processes, and its own organizational culture. This large-scale change process affects all members of the organization and their way of relating to the customer, leading to improvements in the firm's performance and the creation of competitive advantages.

## Essentials of Digital Transformation

Digital transformation is a challenging undertaking that takes time to complete
and is often more complex than expected. It makes products and services obsolete
faster, while encouraging the emergence of new ones that are accessible through a wide variety of channels, such as websites and social applications (Brown & Brown, 2019). Digital transformation redesigns the role of people in business organizations (Bala, 2018), and prompts business leaders to rethink strategy, leadership, and organizational culture (Mahraz et al., 2019).

These substantive transformational changes differ from the typical organizational changes of earlier stages in several respects. For example, the technologies involved today, such as Big Data, analytics, artificial intelligence, etc., differ substantially from previous technologies. In addition, the complexity of the environment in which tourism firms operate is much greater than it was before. Digital technologies provide more information, computing, and connectivity capacity than ever, thus enabling new patterns of collaboration between distributed networks of actors that are more diverse. New dependencies also emerge between actors whose interests may not be fully aligned (Vial, 2019). This means that digital transformation is not limited to a specific type of business or industry, or to the implementation of particular ICTs, but also encompasses much larger and more complex ecosystems and has major
organizational implications (Högberg, 2021).

Managing digital transformation requires orchestrating work within the firm to achieve better products/services and build business models that harness the benefits offered by digital technologies. It is thus important that tourism firms consider their own digital transformation very seriously, since those firms that fail to adapt to the digital environment will fall victim to “digital darwinism”. In other words, firms that resist digital transformation will surely end up disappearing and only those that adapt and respond to technological trends will survive and remain in the competitive arena (Schwartz, 2002).

Tourism firms face increasing pressures from customers, competitors, and employees to initiate or accelerate their pace of digital transformation, and constantly redefine their value proposition. Connectivity, automation, new data, and new digital customer interfaces are challenging traditional value chains as we knew them. Therefore, tourism firms need to carefully assess their product and service portfolios, and the skill set they have. This means starting to make
progress on their digital maturity (if they haven’t already started) to seize opportunities, develop better offerings, and bring them to market quickly. How and in what direction the firm can take effective steps remains unclear. In the end,everybody seems to agree that digital is better, deeper, and faster (Bala, 2018), but to benefit from digital transformation tourism firms must be able to put together a plan that is coherent and consistent.

The accelerated pace in the development of digital technologies and their wide-ranging effects on tourism firms make digital transformation processes so
uncertain that it is virtually impossible to predict which businesses will succeed in their transformation. Even so, it is becoming increasingly clear that competitiveness has long since ceased to depend solely on physical products, and now depends more on the integration of organizations in ecosystems of smart technologies and services. The new possibilities offered by digital technologies are ultimately pushing tourism firms to evaluate the potential to innovate their business models and constantly reinvent themselves. Digital transformation is now an inevitable and irreversible process, at full throttle in the economy and in society as you read these lines (Mahraz et al., 2019). But for digital transformation to gain momentum in tourism ecosystems, the heroic efforts of a few firms, however important they may be, are not enough. It is thus essential to organize concerted actions between all actors in the tourism ecosystem and policy makers to achieve a harmonized regulatory framework, powerful communications, fluid information infrastructures, and an environment that encourages investment to give a new impetus to the competitiveness of tourism firms through digital transformation and smartization.

## Digitization, Digitalization, and Digital Transformation