---
title: "Understanding Data"
---

Data are all kinds of values that reflect facts or events that occur in the context of the activity of the firm and that allow one to recreate or know a reality, either at the micro level of the organization (e.g, the firm, a department), or at the macro level (e.g., ecosystem, market). More specifically, the ISO/IEC-2382-2015 standard, focused on the information technology vocabulary, defines data as a "re-interpretable representation of information in a formalized manner suitable for communication, interpretation, or processing". Data is, therefore, a symbolic representation (numerical, alphabetic, algorithmic, spatial) of a quantitative or qualitative informational attribute or variable that represents an empirical fact, event, or entity, which can be reinterpreted. This means that the context surrounding the data is key for it to acquire its full meaning. Furthermore, data can come from different sources and take different forms. For example, data can be an image from a traffic camera, a message on social media, a voice in a conversation, the temperature of a room, the number of items sold by a store, or the exact time an order was delivered. In addition, data must be able to be communicated and processed, flowing from its source to a processing system. Eventually, all data has a life cycle within organizations that begins with collection, goes through storage and processing, and ends with the dissemination of the data converted into valuable information to users (Fig. 9.1).

The term data warehousing refers to back-end management, or those tasks, processes, and capabilities that support data management, including the tasks that need to be performed to prepare the data for analysis and which a user cannot access. Meanwhile, business intelligence refers to front-end (user-oriented) applications that provide data for analysis and decision-making support. The term analytics is concerned with advanced business intelligence methods that include quantitative data analysis (e.g., statistical analysis, predictive models, etc.) (Collier, 2012). As can be deduced from the data life cycle, each of the stages involved will require appropriate management practices, skills, competencies, and technologies to carry out efficient data management and meet the firm’s performance goals.

## Sources of Data

Tourism firms use different types of data that are differentiated by the way in
which they are created and the media on which they reside. For example, social
media have become one of the main platforms that contribute user-generated
data to tourism firms due to the wide support they have received from tourists
and society in general. Social media apps are convenient, easy to use, and consumers have them installed on their mobile devices. This greatly facilitates
interactivity with tourists, and that many want to share their lives on the internet.

But social media apps are not the only data sources that allow tourism firms to access new data. As more and more people share their lives online and interact with smart devices and sensors of all kinds, large-scale structured and unstructured data is emerging, ushering in the era of Big Data. Moreover, due to
the strong development of the Internet of Things (IoT), various sensors are being developed and used to track the movements of tourists and environmental conditions, providing vast amounts of spatio-temporal data (e.g., GPS data, mobile roaming data, Bluetooth data, etc.). In addition to this so-called unstructured data generated by devices, there is data from tourism operations, such as web searches, visits to web pages, online reservations, purchases, etc. (J. Li et al., 2018). These also represent large amounts of data of a transactional nature that have a high value for tourism firms to understand consumer behavior and improve their value offer to customers. Table 9.1 summarizes the main types of data to which tourism firms usually have access and which are generally divided into two categories (structured and unstructured data) and six subcategories (Lv et al., 2021).

### Structured data

Structured data is data that conforms to a standardized data model, has a well-defined structure and order, and is easily accessible to both humans and
machines. At the dawn of the information age, structured data was the main
source of information used by tourism firms, governments, and researchers – there wasn’t much more. Nowadays, the main sources of structured data come from business databases, government databases, and industry databases.

Firms usually create a business database to record data related to their operations, transactions, and those events that are important to improve business management, including customer and user data, competitor data, or financial accounting data. Traditionally, CRM tools have been one of the most important sources of data to examine the customer profile in tourism firms, accompanied by manufacturing, supply chain, and accounting information systems.

Government databases are created and maintained by national and regional governments and usually contain data on the economy and the productive sectors of the economy. Examples of this type of databases are census data, data on national and international visitors to a destination, hotel occupancy, etc. In the case of tourism, some of the most used database include those related to the licenses of vehicles registered for tourist transport, the traffic flow of motorways, airports and all types of transport, employment in the hotel industry, etc. These data have traditionally been used to forecast tourist demand at the level of tourist destinations, as well as to know the flows of tourists, or the environmental impact of tourism. Of course, there are many other sources of government databases that can be used, such as the energy consumption of the tourism branches, the flows of cross-border travelers, employment, income per tourist, the number and occupancy of hotels, etc. However, a typical problem with these data sources is that it is government owned information that is not always available or up to date.

Sectoral databases are those created and maintained by professional organizations belonging to the tourism sector. A good example is the tourism statistics database of the United Nations World Tourism Organization (UNWTO), which includes data such as the flow of tourists between markets of origin
and destination, or the demand and capacity of tourist accommodation. Since
this data is already structured, there is no need to carry out a data preparation process beforehand (e.g., data cleaning), so the data can be extracted and processed right away. Despite this great advantage, structured data does not usually adapt flexibly to the objectives pursued by tourism firms, so its effectiveness is generally very limited. This makes it common practice to combine structured data with unstructured data to take advantage of it.

### Non-structured data

Rapid advances in internet technologies in recent years have led to the creation
of unstructured data on a massive scale. Today’s users can easily post their
opinions about their last trip, share comments about what they think of this or
that hotel through social media and digital platforms, and express their likes or dislikes about any product or service they have consumed. This is why internet giants like Facebook, Twitter, or Tripadvisor have become authentic hubs of user-generated content (UGC) in the form of reviews, videos, geolocated
photos, etc.

All this UGC, together with the data generated through mobile devices and the data obtained through the digital footprint left by users on the web, has enormous value for firms that struggle to know their customers and users at an
individual level. Let’s take a closer look at each of these sources below.

### User-generated content (UGC) 

UGC typically includes two types of main data: 1) textual data related to the travel experience, such as those shared by tourists on social media and blogs; and 2) online photos and videos, such as those shared on Instagram and Flickr. Social networks, blogs, and online booking and review platforms (e.g., Tripadvisor, Booking.com, Airbnb, Ctrip, etc.) are powerful platforms through which tourists share a wide variety of information related to their tourist experiences, express their satisfaction or dissatisfaction with the tourist products and services consumed, or simply recommend a certain place or provider to other tourists. This type of data can be used by tourism firms as a primary source of information to analyze the movements and travel patterns of tourists. Nonetheless, they generally lack sufficiently detailed contextual information.

Review data is mainly used to assess tourists’ satisfaction with the tourism
products and services they consume (e.g., hotels, rural accommodation, restaurants, tourist attractions, etc.), as well as to inform changes that improve the experience of tourists. This data comes primarily from text data that tourists post on social media, as well as online reviews on travel blogs, accommodation booking sites, and travel websites. The volume of review data can range from several tens to hundreds of thousands depending on the location or attraction in question.

Blog data is used to analyze the sentiments of tourists and keep track of the
places that are most popular. This data is also used to find out the recommendations made by visitors to a destination. Twitter and Sina Weibo are some of the main social blog platforms and blog data sources. By processing blog data, tourism firms can obtain valuable information about the temporal and spatial distribution of tourists, their feelings, and the places they recommend going, or what to do when traveling to a particular tourist destination.

Online photo and video data shared by users on social media and online platforms (e.g., YouTube, Flickr, Pinterest, Instagram, Tripadvisor) also contain very rich and varied information, such as information on the location, time of the visit, or even personal notes of the tourists. This data also provides information on travel recommendations to certain places, travel routes, and user
preferences for certain accommodations or tourist attractions. In recent times,
this type of unstructured data has increasingly attracted the attention of tourism firms, destinations, and researchers, as it offers a new perspective to study the behavior of tourists and the recommendations they make, which can have an impact on value offerings aimed at the market, the design of tourist routes, and marketing.

Some recent studies have used geotagged data in combination with other data sets to compare visitor movements. For example, after comparing Twitter geotagged data on tourist flows between countries with official tourism statistics, similarities have been found between both data sources. Geotagged data allows
for detailed street-level accuracy, especially when compared to other traditionally used methods such as surveys or check-ins at accommodation. However, while this type of data can help tourism firms better understand the relationships between people and places, and provides insight into the context of visitors, it also raises issues related to the reliability of user-generated content, especially in the case of false reviews, or photos and videos that have been manipulated.

### Device-generated data (DGD)

Vast amounts of data are also generated today from devices integrated with
mobile signals (e.g., GPS positioners, Wi-Fi connections, etc.). Unlike traditional static data, such as that obtained through surveys and panels, device data is used to track the movements of tourists in space, thus allowing tourism firms to understand the behavior of tourists more accurately and efficiently in real time.

Mobile phone signaling data is increasingly being used to track the behavior of individual tourists. This type of data provides temporal and spatial information associated with certain data of mobile phone users that makes it possible to track the location of users and identify patterns of movement within and between tourist places (Xu et al., 2020). The signaling data usually includes the number of a station to which the mobile phone is connected, the time in which the connection takes place, and the identification number of the encrypted mobile phone. This can be useful to analyze the loyalty of tourists to a place, the temporal and spatial patterns of visitor movements, and the distances traveled by tourists. It can also be useful for marketing, as current technology allows mobile phones to be positioned, the origin of tourists to be tracked, and the temporal and spatial changes of visitors to be captured in real time both indoors and outdoors. However, there are several issues related to this data: it is difficult to access due to data privacy, and it often lacks accurate information on the location of users and their socioeconomic attributes, thus reducing its value for tourism firms. Additionally, on many occasions, this data does not distinguish between leisure tourists and business travelers, or between tourists and residents.

Data from GPS (satellite navigation system that provides geographic positioning
and time information to a receiver) and GPS-enabled services is another important source of unstructured data. Tourism firms can use this data primarily to examine the spatio-temporal behavior of visitors in places and events. For example, GPS data from taxis has been used to track the movements of tourists in a tourist destination.

GPS data comes mainly from two sources: 1) GPS loggers carried by volunteers
or installed in public devices used by tourists in a place (e.g., GPS
data from public bikes, or scooters shared on city streets); and 2) GPS-enabled
mobile apps installed on users’ own devices. The former can be used in ad hoc
analysis involving a small number of loggers or volunteers, like users who rent
an electric scooter, bicycle, or motorcycle on the streets. The latter can provide information on the trajectory of tourists, travel routes, and their behavior in a destination, which is useful for modeling and predicting the behavior of tourists in tourist destinations (Z. Chen et al., 2021). In addition, this data is more flexible and cheaper to obtain than the first type, making it the preferred GPS data source. Unlike mobile phone positioning data, GPS data provides more precise information on tourist behavior in time and space, since it is generated continuously and without intervals (Shoval et al., 2014). It is also not affected by weather conditions. However, GPS data sample sizes are often smaller, especially if participant-based samples are used, which inevitably introduces bias. One solution may be to use GPS-enabled mobile apps.

Bluetooth and Wi-Fi data are used much less frequently. Bluetooth is a wireless communication technology embedded in smartphones, laptops, and mobile devices that can monitor a large number of users without prior notice to device owners. Mobile devices carried by people can be detected by sensors equipped with Bluetooth technology that can thus track the individual behavior of a large number of tourists. Due to the very short radio range of Bluetooth data reception, this type of data is used in very small-scale contexts, such as
monitoring the movement of visitors in tourist activities or planned events (e.g., festivals, concerts, etc.). Bluetooth technology avoids the need for users to preregister (compared to mobile apps and other technologies), is low cost, and highly convenient. In addition, this data can be used in indoor environments where GPS or mobile phones may have problems due to weak signal.

Compared to Bluetooth, Wi-Fi data is more convenient and cost efficient as it is available on all modern smartphones. However, like Bluetooth data, Wi-Fi data has a very low coverage range compared to mobile data and allows users to be tracked without prior notice. Few tourism firms have used Wi-Fi data to date, although with the growth of Wi-Fi services in public spaces, expect Wi-Fi data to grow and become more accessible in the future. It should also not be forgotten that Bluetooth data and Wi-Fi data facilitate unannounced tracking of
users, which may conflict with the principle of opt-in data collection.

### Web search and transaction data